<?php   $sub_category = [   ['category_id' => 7, 'name' => 'Avtomobil oturacaqları'], // Uşaq aləmi
    ['category_id' => 7, 'name' => 'Oyuncaqlar'],
    ['category_id' => 7, 'name' => 'Qidalanma üçün uşaq oturacaqları'],
    ['category_id' => 7, 'name' => 'Uşaq arabaları'],
    ['category_id' => 7, 'name' => 'Uşaq avtomobilləri'],
    ['category_id' => 7, 'name' => 'Uşaq çarpayıları və beşiklər'],
    ['category_id' => 7, 'name' => 'Uşaq daşıyıcıları'],
    ['category_id' => 7, 'name' => 'Uşaq geyimi'],
    ['category_id' => 7, 'name' => 'Uşaq mebeli'],
    ['category_id' => 7, 'name' => 'Uşaq qidası'],
    ['category_id' => 7, 'name' => 'Uşaq sürüşkənləri və oyun meydançaları'],
    ['category_id' => 7, 'name' => 'Manejlər'],
    ['category_id' => 7, 'name' => 'Məktəblilər üçün'],
    ['category_id' => 7, 'name' => 'Yürütəclər'],
    ['category_id' => 7, 'name' => 'Digər'],
    ['category_id' => 5,'name' => 'Geyim və ayaqqabılar'], // Şəxsi əşyalar
    ['category_id' => 5,'name' => 'Saat və zinət əşyaları'],
    ['category_id' => 5,'name' => 'Aksesuarlar'],
    ['category_id' => 5,'name' => 'Sağlamlıq və gözəllik'],
    ['category_id' => 5,'name' => 'İtmiş əşyalar'],
    ['category_id' => 5,'name' => 'Elektron siqaretlər və tütün qızdırıcıları'],
    ['category_id' => 4,'name' => 'Təmir və tikinti'], // Ev və bağ üçün
    ['category_id' => 4,'name' => 'Mebellər'],
    ['category_id' => 4,'name' => 'Məişət texnikası'],
    ['category_id' => 4,'name' => 'Qab-qacaq və mətbəx ləvazimatları'],
    ['category_id' => 4,'name' => 'Ərzaq'],
    ['category_id' => 4,'name' => 'Bitkilər'],
    ['category_id' => 4,'name' => 'Xalçalar və aksesuarlar'],
    ['category_id' => 4,'name' => 'Ev tekstili'],
    ['category_id' => 4,'name' => 'Ev və bağ üçün işiqlandırma'],
    ['category_id' => 4,'name' => 'Dekor və interyer'],
    ['category_id' => 4,'name' => 'Bağ və bostan'],
    ['category_id' => 1,'name' => 'Audio və video'], // Elektronika
    ['category_id' => 1,'name' => 'Kompüter aksesuarları'],
    ['category_id' => 1,'name' => 'Oyunlar, pultlar və proqramlar'],
    ['category_id' => 1,'name' => 'Masaüstü kompüterlər'],
    ['category_id' => 1,'name' => 'Komponentlər və monitorlar'],
    ['category_id' => 1,'name' => 'Planşet və elektron kitablar'],
    ['category_id' => 1,'name' => 'Noutbuklar və Netbuklar'],/*39*/
    ['category_id' => 1,'name' => 'Ofis avadanlığı və istehlak'],
    ['category_id' => 1,'name' => 'Telefonlar'],
    ['category_id' => 1,'name' => 'Nömrələr və SİM-kartlar'],
    ['category_id' => 1,'name' => 'Foto texnika'],
    ['category_id' => 1,'name' => 'Smart saat və qolbaqlar'],
    ['category_id' => 1,'name' => 'Televizorlar və aksesuarlar'],
    ['category_id' => 6,'name' => 'Biletlər və səyahət'], // Hobbi və asudə
    ['category_id' => 6,'name' => 'Velosipedlər'],
    ['category_id' => 6,'name' => 'Kolleksiya'],
    ['category_id' => 6,'name' => 'Musiqi alətləri'],
    ['category_id' => 6,'name' => 'İdman və asudə'],
    ['category_id' => 6,'name' => 'Kitab və jurnallar'],
    ['category_id' => 6,'name' => 'Ovçuluq və balıqçılıq'],
    ['category_id' => 6,'name' => 'Tanışlıq'],
    ['category_id' => 2,'name' => 'Avtomobillər'], // Nəqliyyat
    ['category_id' => 2,'name' => 'Ehtiyat hissələri və aksesuarlar'],
    ['category_id' => 2,'name' => 'Motosikletlər və mopedlər'],
    ['category_id' => 2,'name' => 'Su nəqliyyatı'],
    ['category_id' => 2,'name' => 'Avtobuslar və xüsusi texnika'],
    ['category_id' => 2,'name' => 'Aqrotexnika'],
    ['category_id' => 3,'name' => 'Mənzillər'], // Daşınmaz əmlak
    ['category_id' => 3,'name' => 'Villalar, bağ evləri'],
    ['category_id' => 3,'name' => 'Torpaq'],
    ['category_id' => 3,'name' => 'Qarajlar'],
    ['category_id' => 3,'name' => 'Xaricdə əmlak'],
    ['category_id' => 3,'name' => 'byektlər və ofislər'],
    ['category_id' => 8,'name' => 'Vakansiyalar'], // İş elanları
    ['category_id' => 8,'name' => 'İş axtarıram'],
    ['category_id' => 9,'name' => 'İtlər'], // Heyvanlar
    ['category_id' => 9,'name' => 'Pişiklər'],
    ['category_id' => 9,'name' => 'Quşlar'],
    ['category_id' => 9,'name' => 'Akvarium və balıqlar'],
    ['category_id' => 9,'name' => 'K/t heyvanları'],
    ['category_id' => 9,'name' => 'Dovşanlar'],
    ['category_id' => 9,'name' => 'Heyvanlar üçün məhsullar'],
    ['category_id' => 9,'name' => 'Atlar'],
    ['category_id' => 9,'name' => 'Gəmiricilər'],
    ['category_id' => 9,'name' => 'Digər heyvanlar'],
    ['category_id' => 10,'name' => 'Avadanlığın icarəsi'], // Xidmətlər və biznes
    ['category_id' => 10,'name' => 'Biznes üçün avadanlıq'],
    ['category_id' => 10,'name' => 'Avadanlıqların quraşdırılması'],
    ['category_id' => 10,'name' => 'Avtoservis və diaqnostika'],
    ['category_id' => 10,'name' => 'Foto və video çəkiliş xidmətləri'],
    ['category_id' => 10,'name' => 'Gözəllik, sağlamlıq'],
    ['category_id' => 10,'name' => 'Hüquq xidmətləri'],
    ['category_id' => 10,'name' => 'IT, internet, telekom'],
    ['category_id' => 10,'name' => 'Mebel yığılması və təmiri'],
    ['category_id' => 10,'name' => 'Musiqi, əyləncə və tədbirlər'],
    ['category_id' => 10,'name' => 'Mühasibat xidmətləri'],
    ['category_id' => 10,'name' => 'Nəqliyyat və logistika'],
    ['category_id' => 10,'name' => 'Qidalanma, keyterinq'],
    ['category_id' => 10,'name' => 'Reklam, dizayn və poliqrafiya'],
    ['category_id' => 10,'name' => 'Sığorta xidmətləri'],
    ['category_id' => 10,'name' => 'Təlim, hazırlıq kursları'],
    ['category_id' => 10,'name' => 'Təmir və tikinti'],
    ['category_id' => 10,'name' => 'Təmizlik'],
    ['category_id' => 10,'name' => 'Tərcümə'],
    ['category_id' => 10,'name' => 'Texnika təmiri'],
    ['category_id' => 10,'name' => 'Tibbi xidmətlər'],
    ['category_id' => 10,'name' => 'Digər'],
];