<?php   $sub_category_type = [     ['sub_category_id' => 8,'name' => 'Oğlan uşaq geyimi'],
    ['sub_category_id' => 8,'name' => 'Qız uşaq geyimi'],
    ['sub_category_id' => 13,'name' => 'Dəftərxana ləvazimatları'],
    ['sub_category_id' => 13,'name' => 'Dərsliklər'],
    ['sub_category_id' => 13,'name' => 'Məktəbli çantaları'],
    ['sub_category_id' => 13,'name' => 'Məktəbli forması'],
    ['sub_category_id' => 13,'name' => 'Yaradıcılıq ləvazimatları'],
    ['sub_category_id' => 16,'name' => 'Qadın geyimləri'],
    ['sub_category_id' => 16,'name' => 'Kişi geyimləri'],
    ['sub_category_id' => 17,'name' => 'Saatlar'],
    ['sub_category_id' => 17,'name' => 'Bijuteriya'],
    ['sub_category_id' => 17,'name' => 'Zərgərlik məmulatları'],
    ['sub_category_id' => 18,'name' => 'Açarlıqlar'],
    ['sub_category_id' => 18,'name' => 'Alışqanlar'],
    ['sub_category_id' => 18,'name' => 'Çamadanlar'],
    ['sub_category_id' => 18,'name' => 'Çantalar'],
    ['sub_category_id' => 18,'name' => 'Eynəklər'],
    ['sub_category_id' => 18,'name' => 'Eynəklər'],
    ['sub_category_id' => 18,'name' => 'Hədiyyə və suvenirlər'],
    ['sub_category_id' => 18,'name' => 'Kəmərlər'],
    ['sub_category_id' => 18,'name' => 'Portmone və pul kisələri'],
    ['sub_category_id' => 18,'name' => 'Təsbehlər'],
    ['sub_category_id' => 19,'name' => 'Arıqlamaq üçün vasitələr'],
    ['sub_category_id' => 19,'name' => 'Fenlər'],
    ['sub_category_id' => 19,'name' => 'Vücuda qulluq'],
    ['sub_category_id' => 19,'name' => 'Kosmetika'],
    ['sub_category_id' => 19,'name' => 'Kosmetoloji avadanlıqlar'],
    ['sub_category_id' => 19,'name' => 'Ətriyyat'],
    ['sub_category_id' => 19,'name' => 'Taraş vasitələri və epilyatorlar'],
    ['sub_category_id' => 21,'name' => 'Elektron siqaretlər'],
    ['sub_category_id' => 21,'name' => 'Tütün qızdırıcıları'],
    ['sub_category_id' => 21,'name' => 'Mayelər, kartriclər və stiklər'],
    ['sub_category_id' => 21,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 22,'name' => 'Buxarılar və qızdırıcılar'],
    ['sub_category_id' => 22,'name' => 'Elektrik malları'],
    ['sub_category_id' => 22,'name' => 'Pəncərələr, qapılar, eyvanlar'],
    ['sub_category_id' => 22,'name' => 'Santexnika və sauna'],
    ['sub_category_id' => 22,'name' => 'Tikinti materialları'],
    ['sub_category_id' => 22,'name' => 'Təmir və tikinti alətləri'],
    ['sub_category_id' => 22,'name' => 'Təmir və tikinti alətləri'],
    ['sub_category_id' => 23,'name' => 'Bufetlər və servantlar'],
    ['sub_category_id' => 23,'name' => 'Çarpayılar'],
    ['sub_category_id' => 23,'name' => 'Dəhliz mebeli'],
    ['sub_category_id' => 23,'name' => 'Divanlar və kreslolar'],
    ['sub_category_id' => 23,'name' => 'Dolablar və komodlar'],
    ['sub_category_id' => 23,'name' => 'Döşəklər'],
    ['sub_category_id' => 23,'name' => 'Jalüz və pərdələr'],
    ['sub_category_id' => 23,'name' => 'Masalar və oturacaqlar'],
    ['sub_category_id' => 23,'name' => 'Mətbəx mebeli'],
    ['sub_category_id' => 23,'name' => 'Ofis mebeli'],
    ['sub_category_id' => 23,'name' => 'Puflar və banketkalar'],
    ['sub_category_id' => 23,'name' => 'Qonaq otağı mebeli'],
    ['sub_category_id' => 23,'name' => 'Rəflər'],
    ['sub_category_id' => 23,'name' => 'Tumbalar'],
    ['sub_category_id' => 23,'name' => 'Yataq otağı mebeli'],
    ['sub_category_id' => 24,'name' => 'Aspiratorlar'],
    ['sub_category_id' => 24,'name' => 'Blenderlər, mikserlər, mətbəx kombaynları'],
    ['sub_category_id' => 24,'name' => 'Blinçik və vafli aparatı'],
    ['sub_category_id' => 24,'name' => 'Elektrik çaydanlar və termopotlar'],
    ['sub_category_id' => 24,'name' => 'Elektrik samovarlar'],
    ['sub_category_id' => 24,'name' => 'Ətçəkən maşınlar'],
    ['sub_category_id' => 24,'name' => 'Fritürlar'],
    ['sub_category_id' => 24,'name' => 'Kondisionerlər'],
    ['sub_category_id' => 24,'name' => 'Mikrodalğalı sobalar'],
    ['sub_category_id' => 24,'name' => 'Mini sobalar'],
    ['sub_category_id' => 24,'name' => 'Multibişiricilər'],
    ['sub_category_id' => 24,'name' => 'Paltaryuyanlar'],
    ['sub_category_id' => 24,'name' => 'Plitələr'],
    ['sub_category_id' => 24,'name' => 'Qabyuyanlar'],
    ['sub_category_id' => 24,'name' => 'Qəhvədəmləyənlər və qəhvə maşınları'],
    ['sub_category_id' => 24,'name' => 'Qızdırıcılar'],
    ['sub_category_id' => 24,'name' => 'Quraşdırılan sobalar'],
    ['sub_category_id' => 24,'name' => 'Samovarlar'],
    ['sub_category_id' => 24,'name' => 'Sərinkeşlər'],
    ['sub_category_id' => 24,'name' => 'Soyuducular'],
    ['sub_category_id' => 24,'name' => 'Su dispenserləri və kulerləri'],
    ['sub_category_id' => 24,'name' => 'Su filterləri və pompaları'],
    ['sub_category_id' => 24,'name' => 'Süd separatorları'],
    ['sub_category_id' => 24,'name' => 'Termometrlər'],
    ['sub_category_id' => 24,'name' => 'Tərəzilər'],
    ['sub_category_id' => 24,'name' => 'Tikiş maşınları'],
    ['sub_category_id' => 24,'name' => 'Tosterlər və çörəkbişirənlər'],
    ['sub_category_id' => 24,'name' => 'Tozsoranlar'],
    ['sub_category_id' => 24,'name' => 'Ütülər'],
    ['sub_category_id' => 24,'name' => 'Vakuum paketləyicilər'],
    ['sub_category_id' => 25,'name' => 'Badələr və qədəhlər'],
    ['sub_category_id' => 25,'name' => 'Boşqablar'],
    ['sub_category_id' => 25,'name' => 'Çay və qəhvə servizləri'],
    ['sub_category_id' => 25,'name' => 'Çaydanlar və qəhvədanlar'],
    ['sub_category_id' => 25,'name' => 'Fincanlar'],
    ['sub_category_id' => 25,'name' => 'Kasalar və salat qabları'],
    ['sub_category_id' => 25,'name' => 'Konfet, qənd və mürəbbə qabları'],
    ['sub_category_id' => 25,'name' => 'Külqabılar'],
    ['sub_category_id' => 25,'name' => 'Meyvə qabları'],
    ['sub_category_id' => 25,'name' => 'Mətbəx məhsulları'],
    ['sub_category_id' => 25,'name' => 'Nahar servizləri'],
    ['sub_category_id' => 25,'name' => 'Nəlbəkilər'],
    ['sub_category_id' => 25,'name' => 'Qazanlar və tavalar'],
    ['sub_category_id' => 25,'name' => 'Qrafinlər və dolçalar'],
    ['sub_category_id' => 25,'name' => 'Sinilər və altlıqlar'],
    ['sub_category_id' => 25,'name' => 'Şirniyyat və çərəz qabları'],
    ['sub_category_id' => 25,'name' => 'Şorba qabları'],
    ['sub_category_id' => 25,'name' => 'Stəkanlar'],
    ['sub_category_id' => 25,'name' => 'Süfrə ləvazimatları'],
    ['sub_category_id' => 28,'name' => 'Xalçalar'],
    ['sub_category_id' => 28,'name' => 'Kilimlər'],
    ['sub_category_id' => 28,'name' => 'Palazlar'],
    ['sub_category_id' => 28,'name' => 'Hamam və tualet üçün xalçalar'],
    ['sub_category_id' => 28,'name' => 'Qapı qabağı xalçalar'],
    ['sub_category_id' => 29,'name' => 'Yataq tekstili'],
    ['sub_category_id' => 29,'name' => 'Dəsmallar'],
    ['sub_category_id' => 29,'name' => 'Mətbəx üçün tekstil'],
    ['sub_category_id' => 29,'name' => 'Pledlər, örtüklər'],
    ['sub_category_id' => 29,'name' => 'Yastıqlar'],
    ['sub_category_id' => 29,'name' => 'Yorğanlar'],
    ['sub_category_id' => 29,'name' => 'Yorğanlar'],
    ['sub_category_id' => 30,'name' => 'Tavan və asma çilçıraqlar'],
    ['sub_category_id' => 30,'name' => 'Divar çıraqları'],
    ['sub_category_id' => 30,'name' => 'Yerüstü və masaüstü çıraqlar'],
    ['sub_category_id' => 30,'name' => 'Küçə çıraqları'],
    ['sub_category_id' => 30,'name' => 'Lampalar'],
    ['sub_category_id' => 30,'name' => 'Projektorlar'],
    ['sub_category_id' => 30,'name' => 'Spotlar və trek çıraqlar'],
    ['sub_category_id' => 30,'name' => 'İşıqlandırılma üçün aksessuarlar'],
    ['sub_category_id' => 31,'name' => 'Bayram dekoru və aksesuarları'],
    ['sub_category_id' => 31,'name' => 'Fotoçərçivələr'],
    ['sub_category_id' => 31,'name' => 'Güldanlar'],
    ['sub_category_id' => 31,'name' => 'Güzgülər'],
    ['sub_category_id' => 31,'name' => 'Heykəlciklər və fiqurlar'],
    ['sub_category_id' => 31,'name' => 'Pul daxılları və mücrülər'],
    ['sub_category_id' => 31,'name' => 'Qapılar üçün stoperlər'],
    ['sub_category_id' => 31,'name' => 'Rəsmlər və pannolar'],
    ['sub_category_id' => 31,'name' => 'Saatlar, zəngli saatlar'],
    ['sub_category_id' => 31,'name' => 'Şamlar və şamdanlar'],
    ['sub_category_id' => 31,'name' => 'Süni güllər və meyvələr'],
    ['sub_category_id' => 32,'name' => 'Bağ ləvazimatları'],
    ['sub_category_id' => 32,'name' => 'Manqallar və aksesuarlar'],
    ['sub_category_id' => 32,'name' => 'Otbiçənlər və trimmerlər'],
    ['sub_category_id' => 32,'name' => 'Qamaklar, yelləncəklər və şezlonqlar'],
    ['sub_category_id' => 32,'name' => 'Su çənləri'],
    ['sub_category_id' => 32,'name' => 'Su nasosları'],
    ['sub_category_id' => 32,'name' => 'Suvarma, suyun çəkilməsi və drenaj avadanlıqları'],
    ['sub_category_id' => 32,'name' => 'Toxumlar və gübrələr'],
    ['sub_category_id' => 33,'name' => 'Dinamik və sabvuferlər'],
    ['sub_category_id' => 33,'name' => 'MP3-pleyerlər'],
    ['sub_category_id' => 33,'name' => 'Musiqi mərkəzləri, maqnitolalar'],
    ['sub_category_id' => 33,'name' => 'Musiqi və kinolar'],
    ['sub_category_id' => 33,'name' => 'Proyektorlar'],
    ['sub_category_id' => 33,'name' => 'Qulaqlıqlar'],
    ['sub_category_id' => 33,'name' => 'Video, DVD və Blu-ray pleyerlər'],
    ['sub_category_id' => 33,'name' => 'Videokameralar'],
    ['sub_category_id' => 34,'name' => 'Kabellər və adapterlar'],
    ['sub_category_id' => 34,'name' => 'Klaviaturalar və kompüter siçanları'],
    ['sub_category_id' => 34,'name' => 'Modemlər və routerlar'],
    ['sub_category_id' => 34,'name' => 'UPS'],
    ['sub_category_id' => 34,'name' => 'USB flaş və yaddaş kartları'],
    ['sub_category_id' => 34,'name' => 'Web kameralar'],
    ['sub_category_id' => 34,'name' => 'Şəbəkə avadanlıqları'],
    ['sub_category_id' => 35,'name' => 'Oyun konsolları'],
    ['sub_category_id' => 35,'name' => 'Konsollar üçün oyunlar'],
    ['sub_category_id' => 35,'name' => 'Kompüter oyunları'],
    ['sub_category_id' => 35,'name' => 'Oyun hesabları'],
    ['sub_category_id' => 35,'name' => 'Proqramlar'],
    ['sub_category_id' => 35,'name' => 'Sosial şəbəkələrdə səhifələr'],
    ['sub_category_id' => 35,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 37,'name' => 'Ana plataları'],
    ['sub_category_id' => 37,'name' => 'Batareyalar'],
    ['sub_category_id' => 37,'name' => 'CD, DVD və Blu-ray'],
    ['sub_category_id' => 37,'name' => 'Keyslər və korpuslar'],
    ['sub_category_id' => 37,'name' => 'Kulerlər və ventilyatorlar'],
    ['sub_category_id' => 37,'name' => 'Monitorlar və ekranlar'],
    ['sub_category_id' => 37,'name' => 'Operativ yaddaş (RAM)'],
    ['sub_category_id' => 37,'name' => 'Prosessorlar (CPU))'],
    ['sub_category_id' => 37,'name' => 'Qida blokları'],
    ['sub_category_id' => 37,'name' => 'Sərt disklər (HDD, SSD)'],
    ['sub_category_id' => 37,'name' => 'Video kartlar'],
    ['sub_category_id' => 38,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 38,'name' => 'Planşetlər'],/*178*/
    ['sub_category_id' => 38,'name' => 'Elektron kitablar'],/*179*/
    ['sub_category_id' => 39,'name' => 'Acer'],
    ['sub_category_id' => 39,'name' => 'Apple Macbook'],
    ['sub_category_id' => 39,'name' => 'Asus'],
    ['sub_category_id' => 39,'name' => 'Casper'],
    ['sub_category_id' => 39,'name' => 'Dell'],
    ['sub_category_id' => 39,'name' => 'Fujitsu-Siemens'],
    ['sub_category_id' => 39,'name' => 'HP'],
    ['sub_category_id' => 39,'name' => 'LG'],
    ['sub_category_id' => 39,'name' => 'Lenovo'],
    ['sub_category_id' => 39,'name' => 'MSI'],
    ['sub_category_id' => 39,'name' => 'Nexus'],
    ['sub_category_id' => 39,'name' => 'Samsung'],
    ['sub_category_id' => 39,'name' => 'Sony'],
    ['sub_category_id' => 39,'name' => 'Toshiba'],
    ['sub_category_id' => 39,'name' => 'Digər'],
    ['sub_category_id' => 39,'name' => 'Noutbuklar üçün aksessuarlar'],
    ['sub_category_id' => 40,'name' => 'Surət çıxardan və skanerlər'],
    ['sub_category_id' => 40,'name' => 'Printerlər'],
    ['sub_category_id' => 40,'name' => 'İstehlak və aksesuarlar'],
    ['sub_category_id' => 40,'name' => 'Digər'],
    ['sub_category_id' => 41,'name' => 'Acer'],/*id 200 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Aiek'],/*id 201 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Alcatel'],/*id 202 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Apple iPhone'],/*id 203 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Asus'],/*id 204 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Blackberry'],/*id 205 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Doogee'],/*id 206 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Dublikat'],/*id 207 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Ericsson'],/*id 208 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Fly'],/*id 209 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Hisense'],/*id 210 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Hoffmann'],/*id 211 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Homtom'],/*id 212 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Honor'],/*id 213 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Hope'],/*id 214 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'HTC'],/*id 215 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Huawei'],/*id 216 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Jinga'],/*id 217 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Keneksi'],/*id 218 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Kgtel'],/*id 219 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Leagoo'],/*id 220 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Lenovo'],/*id 221 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'LG'],/*id 222 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Meizu'],/*id 223 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Micromax'],/*id 224 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Motorola'],/*id 225 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Nokia'],/*id 226 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'OnePlus'],/*id 227 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Oukitel'],/*id 228 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Philips'],/*id 229 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Realme'],/*id 230 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Samsung'],/*id 231 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Siemens'],/*id 232 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Sony'],/*id 233 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Sony Ericsson'],/*id 234 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Umi'],/*id 235 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Vertu'],/*id 236 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Xiaomi'],/*id 237 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'ZTE'],/*id 238 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Stasionar telefonlar'],/*id 239 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Ehtiyat hissələri'],/*id 240 Telefonlar*/
    ['sub_category_id' => 41,'name' => 'Aksesuarlar'],/*id 241 Telefonlar*/
    ['sub_category_id' => 42,'name' => 'Azercell'],/*id 242 NOMRELER VE SIM-KARTLAR*/
    ['sub_category_id' => 42,'name' => 'Bakcell'],/*id 243 NOMRELER VE SIM-KARTLAR*/
    ['sub_category_id' => 42,'name' => 'Nar'],/*id 244 NOMRELER VE SIM-KARTLAR*/
    ['sub_category_id' => 42,'name' => 'Naxtel'],/*id 245 NOMRELER VE SIM-KARTLAR*/
    ['sub_category_id' => 42,'name' => 'Katel CDMA'],/*id 246 NOMRELER VE SIM-KARTLAR*/
    ['sub_category_id' => 43,'name' => 'Binokl və teleskoplar'],/*id 247 Foto texnika*/
    ['sub_category_id' => 43,'name' => 'Fotoaparatlar'],/*id 248 Foto texnika*/
    ['sub_category_id' => 43,'name' => 'Avadanlıq və aksesuarlar'],/*id 249 Foto texnika*/
    ['sub_category_id' => 43,'name' => 'Linzalar'],/*id 250 Foto texnika*/
    ['sub_category_id' => 44,'name' => 'Kəmərlər, aksesuarlar'],/*id 251 Smart saat ve qolbaglqr*/
    ['sub_category_id' => 44,'name' => 'Smart qolbaqlar'],/*id 252 Smart saat ve qolbaglqr*/
    ['sub_category_id' => 44,'name' => 'Smart saatlar'],/*id 253 Smart saat ve qolbaglqr*/
    ['sub_category_id' => 45,'name' => 'Televizorlar'],
    ['sub_category_id' => 45,'name' => 'Antenlər'],
    ['sub_category_id' => 45,'name' => 'Kronşteynlər'],
    ['sub_category_id' => 45,'name' => 'Pultlar'],
    ['sub_category_id' => 45,'name' => 'Televizor altlıqları və stendlər'],
    ['sub_category_id' => 45,'name' => 'Tünerlər'],
    ['sub_category_id' => 46,'name' => 'Konsertlər'],
    ['sub_category_id' => 46,'name' => 'Teatr'],
    ['sub_category_id' => 46,'name' => 'Səyahət'],
    ['sub_category_id' => 46,'name' => 'Səyahət'],
    ['sub_category_id' => 47,'name' => 'BMX'],
    ['sub_category_id' => 47,'name' => 'Dağ'],
    ['sub_category_id' => 47,'name' => 'Yol'],
    ['sub_category_id' => 47,'name' => 'Ehtiyat hissələri və aksesuarlar'],
    ['sub_category_id' => 48,'name' => 'Qramplastinka'],
    ['sub_category_id' => 48,'name' => 'Nişanlar, medallar, döş nişanları'],
    ['sub_category_id' => 48,'name' => 'Kolleksiya silahları'],
    ['sub_category_id' => 48,'name' => 'Markalar'],
    ['sub_category_id' => 48,'name' => 'Rəsm əsərləri'],
    ['sub_category_id' => 48,'name' => 'Modellər'],
    ['sub_category_id' => 48,'name' => 'Pullar'],
    ['sub_category_id' => 48,'name' => 'Əl işləri'],
    ['sub_category_id' => 49,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 49,'name' => 'Gitara və digər simlilər'],
    ['sub_category_id' => 49,'name' => 'Studia və konsertlər üçün'],
    ['sub_category_id' => 49,'name' => 'Pianino və digər klavişnilər'],
    ['sub_category_id' => 49,'name' => 'Skripkalar və digər yaylılar'],
    ['sub_category_id' => 49,'name' => 'Zərb alətləri'],
    ['sub_category_id' => 50,'name' => 'Bilyard və boulinq'],
    ['sub_category_id' => 50,'name' => 'Fitnes və trenajorlar'],
    ['sub_category_id' => 50,'name' => 'İdman qidası və əlavələr'],
    ['sub_category_id' => 50,'name' => 'Masaüstü oyunlar'],
    ['sub_category_id' => 50,'name' => 'Qış idman növləri'],
    ['sub_category_id' => 50,'name' => 'Roliklər, skeytbordlar, segway'],
    ['sub_category_id' => 50,'name' => 'Su idmanı və hovuzlar'],
    ['sub_category_id' => 50,'name' => 'Topla oyunlar'],
    ['sub_category_id' => 50,'name' => 'Təkbətək döyüş'],
    ['sub_category_id' => 51,'name' => 'Jurnallar'],
    ['sub_category_id' => 51,'name' => 'Kitablar'],
    ['sub_category_id' => 55,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 55,'name' => 'Audio və video texnika'],
    ['sub_category_id' => 55,'name' => 'Avto kosmetika və kimya'],
    ['sub_category_id' => 55,'name' => 'Diaqnostika cihazları'],
    ['sub_category_id' => 55,'name' => 'Ehtiyat hissələri'],
    ['sub_category_id' => 55,'name' => 'GPS-naviqatorlar'],
    ['sub_category_id' => 55,'name' => 'Qeydiyyat nişanları'],
    ['sub_category_id' => 55,'name' => 'Şinlər, disklər və təkərlər'],
    ['sub_category_id' => 55,'name' => 'Siqnalizasiyalar'],
    ['sub_category_id' => 55,'name' => 'Videoqeydiyyatçılar'],
    ['sub_category_id' => 56,'name' => 'Hidrosikllar'],
    ['sub_category_id' => 56,'name' => 'Ehtiyat hissələri və aksesuarlar'],
    ['sub_category_id' => 56,'name' => 'Katerlər və yaxtalar'],
    ['sub_category_id' => 56,'name' => 'Mühərrikli qayıqlar'],
    ['sub_category_id' => 56,'name' => 'Hava qayıqları'],
    ['sub_category_id' => 59,'name' => 'Traktorlar'],
    ['sub_category_id' => 59,'name' => 'Kombaynlar'],
    ['sub_category_id' => 59,'name' => 'Köməkçi qoşqular'],
    ['sub_category_id' => 59,'name' => 'Kultivatorlar'],
    ['sub_category_id' => 59,'name' => 'Motobloklar'],
    ['sub_category_id' => 59,'name' => 'Digər texnika'],
    ['sub_category_id' => 64,'name' => 'Satış'],
    ['sub_category_id' => 64,'name' => 'Kirayə'],
    ['sub_category_id' => 64,'name' => 'İcarə'],
    ['sub_category_id' => 68,'name' => 'Akita-inu'],
    ['sub_category_id' => 68,'name' => 'Alabay'],
    ['sub_category_id' => 68,'name' => 'Alman ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Belçika ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Buldoq'],
    ['sub_category_id' => 68,'name' => 'Çau-çau'],
    ['sub_category_id' => 68,'name' => 'Cek Rassel Teryer'],
    ['sub_category_id' => 68,'name' => 'Çixuaxua'],
    ['sub_category_id' => 68,'name' => 'Doberman'],
    ['sub_category_id' => 68,'name' => 'Doq'],
    ['sub_category_id' => 68,'name' => 'Haski'],
    ['sub_category_id' => 68,'name' => 'Kane Korso'],
    ['sub_category_id' => 68,'name' => 'Kanqal'],
    ['sub_category_id' => 68,'name' => 'Koker spaniel'],
    ['sub_category_id' => 68,'name' => 'Labrador Retriver'],
    ['sub_category_id' => 68,'name' => 'Malta bolonkası'],
    ['sub_category_id' => 68,'name' => 'Mastif'],
    ['sub_category_id' => 68,'name' => 'Pekines'],
    ['sub_category_id' => 68,'name' => 'Pitbul'],
    ['sub_category_id' => 68,'name' => 'Pudel'],
    ['sub_category_id' => 68,'name' => 'Qafqaz ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Qurdbasar'],
    ['sub_category_id' => 68,'name' => 'Rotveyler'],
    ['sub_category_id' => 68,'name' => 'Samoyed'],
    ['sub_category_id' => 68,'name' => 'Şpits'],
    ['sub_category_id' => 68,'name' => 'Yorkşir teryer'],
    ['sub_category_id' => 69,'name' => 'Avropa'],
    ['sub_category_id' => 69,'name' => 'Benqal'],
    ['sub_category_id' => 69,'name' => 'Britan'],
    ['sub_category_id' => 69,'name' => 'Pers'],
    ['sub_category_id' => 69,'name' => 'Siam'],
    ['sub_category_id' => 69,'name' => 'Sibir'],['sub_category_id' => 23,'name' => 'Çarpayılar'],
    ['sub_category_id' => 69,'name' => 'Şotland'],
    ['sub_category_id' => 69,'name' => 'Türk anqorı'],
    ['sub_category_id' => 74,'name' => 'Baytarlıq apteki'],
    ['sub_category_id' => 74,'name' => 'Bio-tualetlər və doldurucular'],
    ['sub_category_id' => 74,'name' => 'Daşıma konteynerləri və çantaları'],
    ['sub_category_id' => 74,'name' => 'Oyuncaqlar və dırnaq itiləyənlər'],
    ['sub_category_id' => 74,'name' => 'Qəfəslər və yuvalar'],
    ['sub_category_id' => 74,'name' => 'Qidalar'],
    ['sub_category_id' => 74,'name' => 'Qruminq və qulluq'],
    ['sub_category_id' => 74,'name' => 'Xaltalar və qayışlar'],
    ['sub_category_id' => 74,'name' => 'Yem və su qabları'],
    ['sub_category_id' => 74,'name' => 'Yəhərlər'],
    ['sub_category_id' => 79,'name' => 'Gözəllik salonu üçün'],
    ['sub_category_id' => 79,'name' => 'Mağaza üçün'],
    ['sub_category_id' => 79,'name' => 'Ofis üçün'],
    ['sub_category_id' => 79,'name' => 'Restoran üçün'],
    ['sub_category_id' => 79,'name' => 'Sənaye'],
    ['sub_category_id' => 79,'name' => 'Tibbi avadanlıqlar'],
    ['sub_category_id' => 94,'name' => 'Dam və çardaq'],
    ['sub_category_id' => 94,'name' => 'Darvaza və avtomatik qapıların sifarişi'],
    ['sub_category_id' => 94,'name' => 'Dekor, dizayn, smeta və planlama'],
    ['sub_category_id' => 94,'name' => 'Divar kağızı işləri'],
    ['sub_category_id' => 94,'name' => 'Döşəmə və tavan işləri'],
    ['sub_category_id' => 94,'name' => 'Dülgər işləri'],
    ['sub_category_id' => 94,'name' => 'Elektrik xidmətləri'],
    ['sub_category_id' => 94,'name' => 'Fasad işləri'],
    ['sub_category_id' => 94,'name' => 'Hazır konstruksiyalar'],
    ['sub_category_id' => 94,'name' => 'Kafel-plitə işləri'],
    ['sub_category_id' => 94,'name' => 'Landşaft işləri'],
    ['sub_category_id' => 94,'name' => 'Metal-qaynaq işləri'],
    ['sub_category_id' => 94,'name' => 'Məhəccər və arakəsmələrin sifarişi'],
    ['sub_category_id' => 94,'name' => 'Mərmər sifarişi və mərmər işləri'],
    ['sub_category_id' => 94,'name' => 'Pəncərə, qapı, eyvan'],
    ['sub_category_id' => 94,'name' => 'Təmir xidmətləri'],
    ['sub_category_id' => 94,'name' => 'Tikinti xidmətləri'],
    ['sub_category_id' => 97,'name' => 'Audio və video cihazların təmiri'],
    ['sub_category_id' => 97,'name' => 'Kombi və su qızdırıcılarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Kompüter və noutbukların təmiri'],
    ['sub_category_id' => 97,'name' => 'Məişət texnikalarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Musiqi alətlərinin təmiri'],
    ['sub_category_id' => 97,'name' => 'Oyun konsollarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Printer təmiri və kartric doldurulması'],
    ['sub_category_id' => 97,'name' => 'Telefon və planşetlərin təmiri'],
    ['sub_category_id' => 97,'name' => 'Televizorların təmiri'],
    ['sub_category_id' => 97,'name' => 'Tikinti alət və avadanlıqları təmiri'],
];