<?php   $tab_model = [  ['sub_category_type_one_id' => 75,'name' => 'Chromebook Tab 10'],/*Acer 31 dene*/
    ['sub_category_type_one_id' => 75,'name' => 'Iconia A1-830'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia B1-720'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia B1-721'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia One 7 B1-730'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia One 8 B1-820'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab 10 A3-A30'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab 10 A3-A40'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab 7 A1-713'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab 7 A1-713HD'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab 8 A1-840FHD'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A1-810'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A1-811'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A100'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A101'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A110'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A200'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A210'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A3'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A3-A20'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A3-A20FHD'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A500'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A501'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A510'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A511'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A700'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab A701'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab B1-710'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Tab B1-A71'],
    ['sub_category_type_one_id' => 75,'name' => 'Iconia Talk S'],
    ['sub_category_type_one_id' => 75,'name' => 'Predator 8'],/*1*/
    ['sub_category_type_one_id' => 76,'name' => '1T 10'],/*Alcatel 28 dene*/
    ['sub_category_type_one_id' => 76,'name' => '1T 7'],
    ['sub_category_type_one_id' => 76,'name' => '3T 10'],
    ['sub_category_type_one_id' => 76,'name' => '3T 8'],
    ['sub_category_type_one_id' => 76,'name' => 'Hero 8'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Evo 7'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Evo 7 HD'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Evo 8HD'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch T10'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Tab 7'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Tab 7 HD'],
    ['sub_category_type_one_id' => 76,'name' => 'One Touch Tab 8 HD'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (10)'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (7)'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (7) 3G'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (7) LTE'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (8) 3G'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 3 (8) LTE'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 4 (7)'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 7'],
    ['sub_category_type_one_id' => 76,'name' => 'Pixi 8'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 10'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 7'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 7 LTE'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 7S'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 8'],
    ['sub_category_type_one_id' => 76,'name' => 'Pop 8S'],
    ['sub_category_type_one_id' => 76,'name' => 'Smart Tab 7'],/*2*/
    ['sub_category_type_one_id' => 77,'name' => '2 Speed Quad'],/*Allview 29 dene*/
    ['sub_category_type_one_id' => 77,'name' => '3 Speed Quad HD'],
    ['sub_category_type_one_id' => 77,'name' => 'AX3 Party'],
    ['sub_category_type_one_id' => 77,'name' => 'AX4 Nano'],
    ['sub_category_type_one_id' => 77,'name' => 'AX4 Nano Plus'],
    ['sub_category_type_one_id' => 77,'name' => 'AX501Q'],
    ['sub_category_type_one_id' => 77,'name' => 'City Life'],
    ['sub_category_type_one_id' => 77,'name' => 'City+'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva 1003G'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva 1003G Lite'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva 803G'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva C701'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva C703'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva D8'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H10 HD'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H10 LTE'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H1001 LTE'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H7 LTE'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H7S'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H8'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva H8 LTE'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva Home'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva i10G'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva i8'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva Q7 Life'],
    ['sub_category_type_one_id' => 77,'name' => 'Viva Q8'],
    ['sub_category_type_one_id' => 77,'name' => 'Wi10N PRO'],
    ['sub_category_type_one_id' => 77,'name' => 'Wi7'],
    ['sub_category_type_one_id' => 77,'name' => 'Wi8G'],/*3*/
    ['sub_category_type_one_id' => 78,'name' => 'Fire 7'],/*Amazon 21*/
    ['sub_category_type_one_id' => 78,'name' => 'Fire 7 (2017)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 10'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 10 (2017)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 10 (2019)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 10 (2021)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 10 Plus (2021)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 6'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 7'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 8'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 8 (2017)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 8 (2020)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HD 8 Plus (2020)'],
    ['sub_category_type_one_id' => 78,'name' => 'Fire HDX 8.9 (2014)'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HD'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HD (2013)'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HD 8.9'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HD 8.9 LTE'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HDX'],
    ['sub_category_type_one_id' => 78,'name' => 'Kindle Fire HDX 8.9'],/*4*/
    ['sub_category_type_one_id' => 79,'name' => 'iPad'],/*id=110 Apple 36 dene */
    ['sub_category_type_one_id' => 79,'name' => 'iPad 10.2 (2019)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 10.2 (2020)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 10.2 (2021)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 2'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 2 3G'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 2 CDMA'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 3'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 3 3G'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 3G'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 4'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 4 3G'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 9.7 (2017)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad 9.7 (2018)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Air'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Air (2022)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Air 2'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Air 3 (2019)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Air 4 (2020)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini (2019)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini (2021)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini 2'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini 3'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini 3G'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad mini 4 (2015)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 10.5 (2017)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 11 (2018)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 11 (2020)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 11 (2021)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 12.9 (2015)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 12.9 (2017)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 12.9 (2018)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 12.9 (2020)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 12.9 (2021)'],
    ['sub_category_type_one_id' => 79,'name' => 'iPad Pro 9.7 (2016)'],
    ['sub_category_type_one_id' => 80,'name' => '80 Helium 4G'],/*id 146*/
    ['sub_category_type_one_id' => 80,'name' => 'Diamond Tab'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad'],/*id 148*/
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7 (2014)'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7 FE171CG'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7 FE375CG'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7 FE375CL'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 7 FE375CXG'],
    ['sub_category_type_one_id' => 80,'name' => 'Fonepad 8 FE380CG'],
    ['sub_category_type_one_id' => 80,'name' => 'Google Nexus 7'],
    ['sub_category_type_one_id' => 80,'name' => 'Google Nexus 7 (2013)'],
    ['sub_category_type_one_id' => 80,'name' => 'Google Nexus 7 Cellular'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 10'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 10 ME103K'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 7 ME176C'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 7 ME572C'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 7 ME572CL'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 8 ME180A'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 8 ME181C'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad 8 ME581CL'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad FHD10'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad HD7 16 GB'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad HD7 8 GB'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad ME172V'],
    ['sub_category_type_one_id' => 80,'name' => 'Memo Pad Smart 10'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Book Trio'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad Infinity 700'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad Infinity 700 3G'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad Infinity 700 LTE'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad TF103C'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad TF300T'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad TF300TG'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad TF303CL'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Pad TF701T'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Prime TF201'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer Prime TF700T'],
    ['sub_category_type_one_id' => 80,'name' => 'Transformer TF101'],
    ['sub_category_type_one_id' => 80,'name' => 'VivoTab RT TF600T'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenfone Go ZB690KG'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 10 Z300C'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 10 Z300M'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 3 8.0 Z581KL'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 3S 10 Z500KL'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 3S 10 Z500M'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 3s 8.0 Z582KL'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 7.0 Z370CG'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 8.0 Z380C'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 8.0 Z380KL'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad 8.0 Z380M'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad C 7.0'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad C 7.0 Z170MG'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad S 8.0 Z580C'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad S 8.0 Z580CA'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad Z10 ZT500KL'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad Z8'],
    ['sub_category_type_one_id' => 80,'name' => 'Zenpad Z8s ZT582KL'],
    ['sub_category_type_one_id' => 82,'name' => '4G LTE Playbook'],/*id 204*/
    ['sub_category_type_one_id' => 82,'name' => '4G Playbook HSPA+'],
    ['sub_category_type_one_id' => 82,'name' => 'Playbook'],
    ['sub_category_type_one_id' => 82,'name' => 'Playbook Wimax'],
    ['sub_category_type_one_id' => 83,'name' => 'Life View 8.0'],/*id 208*/
    ['sub_category_type_one_id' => 83,'name' => 'Life View Tab'],
    ['sub_category_type_one_id' => 83,'name' => 'M7L'],
    ['sub_category_type_one_id' => 83,'name' => 'M8L'],
    ['sub_category_type_one_id' => 83,'name' => 'M8L 2022'],
    ['sub_category_type_one_id' => 83,'name' => 'M8L Plus'],
    ['sub_category_type_one_id' => 83,'name' => 'Studio 7.0 II'],
    ['sub_category_type_one_id' => 83,'name' => 'Touch Book 7.0'],
    ['sub_category_type_one_id' => 83,'name' => 'Touch Book 7.0 Lite'],
    ['sub_category_type_one_id' => 83,'name' => 'Touch Book 7.0 Plus'],
    ['sub_category_type_one_id' => 83,'name' => 'Touch Book 9.7'],
    ['sub_category_type_one_id' => 83,'name' => 'Touch Book M7'],
    ['sub_category_type_one_id' => 83,'name' => 'Touchbook G7'],
    ['sub_category_type_one_id' => 83,'name' => 'Touchbook M7'],
    ['sub_category_type_one_id' => 83,'name' => 'Touchbook M7 Pro'],
    ['sub_category_type_one_id' => 84,'name' => 'Aquaris M10'],/*223*/
    ['sub_category_type_one_id' => 85,'name' => 'CT 1'],/*224*/
    ['sub_category_type_one_id' => 85,'name' => 'CT 2'],
    ['sub_category_type_one_id' => 85,'name' => 'CT 7'],
    ['sub_category_type_one_id' => 85,'name' => 'CT 9'],
    ['sub_category_type_one_id' => 85,'name' => 'CT-888'],
    ['sub_category_type_one_id' => 85,'name' => 'CT-910'],
    ['sub_category_type_one_id' => 85,'name' => 'CT-910+'],
    ['sub_category_type_one_id' => 85,'name' => 'C720'],
    ['sub_category_type_one_id' => 85,'name' => 'C820'],
    ['sub_category_type_one_id' => 86,'name' => 'Streak 10 Pro'],/*233*/
    ['sub_category_type_one_id' => 86,'name' => 'Streak 7'],
    ['sub_category_type_one_id' => 86,'name' => 'Streak 7'],
    ['sub_category_type_one_id' => 86,'name' => 'Venue 10 7000'],
    ['sub_category_type_one_id' => 86,'name' => 'Venue 7'],
    ['sub_category_type_one_id' => 86,'name' => 'Venue 7 8 GB'],
    ['sub_category_type_one_id' => 86,'name' => 'Venue 8'],
    ['sub_category_type_one_id' => 86,'name' => 'Venue 8 7000'],
    ['sub_category_type_one_id' => 86,'name' => 'XPS 10'],
    ['sub_category_type_one_id' => 87,'name' => 'Pixel C'],/*242*/
    ['sub_category_type_one_id' => 88,'name' => 'Pad 2'],/*243*/
    ['sub_category_type_one_id' => 88,'name' => 'Pad 5 10.1'],
    ['sub_category_type_one_id' => 88,'name' => 'Pad 5 8'],
    ['sub_category_type_one_id' => 88,'name' => 'Pad 6'],
    ['sub_category_type_one_id' => 88,'name' => 'Pad 8'],
    ['sub_category_type_one_id' => 88,'name' => 'Pad X6'],
    ['sub_category_type_one_id' => 88,'name' => 'Tab 5'],
    ['sub_category_type_one_id' => 88,'name' => 'Tab 7'],
    ['sub_category_type_one_id' => 88,'name' => 'Tablet V7'],
    ['sub_category_type_one_id' => 88,'name' => 'Tablet V7 Pro'],
    ['sub_category_type_one_id' => 88,'name' => 'Tablet X7'],
    ['sub_category_type_one_id' => 88,'name' => 'V6'],
    ['sub_category_type_one_id' => 89,'name' => '10 Plus'],/*255*/
    ['sub_category_type_one_id' => 89,'name' => '7 Plus'],
    ['sub_category_type_one_id' => 89,'name' => '8'],
    ['sub_category_type_one_id' => 89,'name' => 'Pro Slate 10 EE G1'],
    ['sub_category_type_one_id' => 89,'name' => 'Pro Slate 12'],
    ['sub_category_type_one_id' => 89,'name' => 'Pro Slate 8'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate 17'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate 7'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate10 HD'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate7 Extreme'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate7 Plus'],
    ['sub_category_type_one_id' => 89,'name' => 'Slate8 Pro'],
    ['sub_category_type_one_id' => 89,'name' => 'TouchPad'],
    ['sub_category_type_one_id' => 90,'name' => 'EVO View 4G'],/*id 268*/
    ['sub_category_type_one_id' => 90,'name' => 'Flyer'],
    ['sub_category_type_one_id' => 90,'name' => 'Jetstream'],
    ['sub_category_type_one_id' => 90,'name' => 'Nexus 9'],
    ['sub_category_type_one_id' => 90,'name' => 'Shift'],
    ['sub_category_type_one_id' => 91,'name' => 'Enjoy Tablet 2'],/*id 273*/
    ['sub_category_type_one_id' => 91,'name' => 'IDEOS S7'],
    ['sub_category_type_one_id' => 91,'name' => 'IDEOS S7 Slim'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad 10.4'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad 10.4 (2022)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad 10.8'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad 11 (2021)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad 5G'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro 10.8 (2019)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro 10.8 (2021)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro 11 (2022)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro 12.6 (2021)'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad Pro 5G'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad SE'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad T 10'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad T 10s'],
    ['sub_category_type_one_id' => 91,'name' => 'MatePad T8'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 10 FHD'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 10 Link'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 10 Link+'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 7 Lite'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 7 Vogue'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 7 Youth'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad 7 Youth2'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M1'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M2 10.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M2 7.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M2 8.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M3 8.4'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M3 Lite 10'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M3 Lite 8'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M5 10'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M5 10 (Pro)'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M5 8'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M5 lite'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M5 Lite 8'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M6 10.8'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M6 8.4'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad M6 Turbo 8.4'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad S7-301w'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T1 10'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T1 7.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T1 7.0 Plus'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T1 8.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T2 10.0 Pro'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T2 7.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T2 7.0 Pro'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T3 10'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T3 7.0'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad T3 8.0'],
    ['sub_category_type_one_id' => 91,'name' => 'Mediapad T5'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad X1'],
    ['sub_category_type_one_id' => 91,'name' => 'MediaPad X2'],
    ['sub_category_type_one_id' => 92,'name' => 'G10'],/*328*/
    ['sub_category_type_one_id' => 92,'name' => 'G2'],
    ['sub_category_type_one_id' => 92,'name' => 'G3'],
    ['sub_category_type_one_id' => 92,'name' => 'G5'],
    ['sub_category_type_one_id' => 92,'name' => 'G7'],
    ['sub_category_type_one_id' => 92,'name' => 'G7 Pro'],
    ['sub_category_type_one_id' => 92,'name' => 'G8'],
    ['sub_category_type_one_id' => 92,'name' => 'G8 LTE'],
    ['sub_category_type_one_id' => 93,'name' => 'A10-70 A7600'],/*336*/
    ['sub_category_type_one_id' => 93,'name' => 'A7-30 A3300'],
    ['sub_category_type_one_id' => 93,'name' => 'A7-50 A3500'],
    ['sub_category_type_one_id' => 93,'name' => 'A8-50 A5500'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaPad A1'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaPad K1'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaPad S2'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab A1000'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab A2107'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab A3000'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab S6000'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab S6000F'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab S6000H'],
    ['sub_category_type_one_id' => 93,'name' => 'IdeaTab S6000L'],
    ['sub_category_type_one_id' => 93,'name' => 'Legion Y700'],
    ['sub_category_type_one_id' => 93,'name' => 'LePad S2007'],
    ['sub_category_type_one_id' => 93,'name' => 'LePad S2010'],
    ['sub_category_type_one_id' => 93,'name' => 'M10 FHD REL'],
    ['sub_category_type_one_id' => 93,'name' => 'M10 Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'moto tab'],
    ['sub_category_type_one_id' => 93,'name' => 'Pad'],
    ['sub_category_type_one_id' => 93,'name' => 'Pad Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'Pad Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Pad Pro 2022'],
    ['sub_category_type_one_id' => 93,'name' => 'S5000'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 2 A10-70'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 2 A7-10'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 2 A7-20'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 2 A7-30'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 2 A8-50'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 3 10'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 3 7'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 3 8'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 3 8 Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 4 10'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 4 10 Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 4 8'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 4 8 Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 7'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab 7 Essential'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab K10'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M10 HD Gen 2'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M10 Plus (3rd Gen)'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M7'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M8 (3rd Gen)'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M8 (FHD)'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab M8 (HD)'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P10'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P11'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P11 5G'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P11 Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P11 Pro Gen 2'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab P12 Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab S8'],
    ['sub_category_type_one_id' => 93,'name' => 'Tab V7'],
    ['sub_category_type_one_id' => 93,'name' => 'ThinKPad'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Pad Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Smart Tab'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tab 3 10'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tab 3 8.0'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tab 3 Plus'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tab 3 Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 10'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 10 HD+'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 2 10.1'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 2 8.0'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 2 Pro'],
    ['sub_category_type_one_id' => 93,'name' => 'Yoga Tablet 8'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 10.1'],/*id 404*/
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 10.1 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 5 10.1'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 7.0'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 7.0 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 8.0'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 8.0 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 8.3'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad 8.3 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad II 10.1'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad II 8.0 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad II 8.3 LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad III 10.1 FHD'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad III 8.0 FHD'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad IV 8.0 FHD'],
    ['sub_category_type_one_id' => 94,'name' => 'G Pad X 8.0'],
    ['sub_category_type_one_id' => 94,'name' => 'Optimus Pad LTE'],
    ['sub_category_type_one_id' => 94,'name' => 'Optimus Pad V900'],
    ['sub_category_type_one_id' => 94,'name' => 'Ultra Tab'],
    ['sub_category_type_one_id' => 95,'name' => 'Tab Phone 72DC'],/*423*/

    ['sub_category_type_one_id' => 96,'name' => 'Canvas Tab P470'],/*424*/
    ['sub_category_type_one_id' => 96,'name' => 'Canvas Tab P650'],
    ['sub_category_type_one_id' => 96,'name' => 'Canvas Tab P666'],
    ['sub_category_type_one_id' => 96,'name' => 'Canvas Tab P690'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook 3G P560'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook 3G P600'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook Alfa P250'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook Infinity P275'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook P300'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook Pro'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook Talk P360'],
    ['sub_category_type_one_id' => 96,'name' => 'Funbook Talk P362'],
    ['sub_category_type_one_id' => 97,'name' => 'Surface'],/*436*/
    ['sub_category_type_one_id' => 97,'name' => 'Surface 2'],
    ['sub_category_type_one_id' => 97,'name' => 'Surface Duo'],
    ['sub_category_type_one_id' => 97,'name' => 'Surface Duo 2'],
    ['sub_category_type_one_id' => 97,'name' => 'Surface Go 2'],
    ['sub_category_type_one_id' => 98,'name' => 'DROID XYBOARD 10.1 MZ617'],/*441*/
    ['sub_category_type_one_id' => 98,'name' => 'DROID XYBOARD 8.2 MZ609'],
    ['sub_category_type_one_id' => 98,'name' => 'Moto Tab G62'],
    ['sub_category_type_one_id' => 98,'name' => 'Moto Tab G70'],
    ['sub_category_type_one_id' => 98,'name' => 'Tab G20'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM 2 3G MZ616'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM 2 Media Edition 3G MZ608'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM 2 Media Edition MZ607'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM 2 MZ615'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM Media Edition MZ505'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM MZ600'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM MZ601'],
    ['sub_category_type_one_id' => 98,'name' => 'XOOM MZ604'],
    ['sub_category_type_one_id' => 99,'name' => 'Lumia 2520'],/*454*/
    ['sub_category_type_one_id' => 99,'name' => 'N1'],
    ['sub_category_type_one_id' => 99,'name' => 'N800'],
    ['sub_category_type_one_id' => 99,'name' => 'N810'],
    ['sub_category_type_one_id' => 99,'name' => 'T10'],
    ['sub_category_type_one_id' => 99,'name' => 'T20'],
    ['sub_category_type_one_id' => 99,'name' => 'T21'],
    ['sub_category_type_one_id' => 100,'name' => 'Toughpad FZ-A1'],/*461*/
    ['sub_category_type_one_id' => 100,'name' => 'Toughpad JT-B1'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 10.1 Ultimate'],/*463*/
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 10.1 Ultimate 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 2 Prime Duo 8.0'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 2 Pro Duo 8.0 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 2 Ultra Duo 8.0'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 2 Ultra Duo 8.0 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'Multipad 4 Quantum 10.1'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 4 Quantum 10.1 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'Multipad 4 Quantum 7.85'],
    ['sub_category_type_one_id' => 101,'name' => 'Multipad 4 Quantum 9.7'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 4 Quantum 9.7 Colombia'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 4 Ultimate 8.0 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 4 Ultra Quad 8.0 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 HD'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 HD +'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Prime'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Prime +'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Prime 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Prime Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Prime Duo 3G'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Pro'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Pro Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Ultra'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Ultra +'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Ultra + New'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 7.0 Ultra Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 8.0 HD'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 8.0 Pro Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 8.0 Ultra Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad 9.7 Ultra Duo'],
    ['sub_category_type_one_id' => 101,'name' => 'MultiPad Note 8.0 3G'],
    ['sub_category_type_one_id' => 102,'name' => 'QTab V10'],/*494*/
    ['sub_category_type_one_id' => 102,'name' => 'QTab X50'],
    ['sub_category_type_one_id' => 103,'name' => 'Ativ Tab P8510'],/*496*/
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note 10.1 (2014)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note 10.1 N8000'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note 10.1 N8010'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note 8.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note LTE 10.1 N8020'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note Pro 12.2'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note Pro 12.2 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Note Pro 12.2 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 10.1 LTE I905'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 10.1 P7510'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 10.1 CDMA'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 10.1 P5100'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 10.1 P5110'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 7.0 I705'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 7.0 P3100'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 2 7.0 P3110'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 10.1 P5200'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 10.1 P5210'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 10.1 P5220'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 7.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 7.0 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 8.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 Lite 7.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 Lite 7.0 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 Lite 7.0 VE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 3 V'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 10.1'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 10.1 (2015)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 10.1 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 10.1 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 7.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 7.0 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 7.0 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 8.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 8.0 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 4 8.0 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 7.7 LTE I815'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 8.9 4G P7320T'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 8.9 LTE I957'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 8.9 P7300'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab 8.9 P7310'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 10.1 (2016)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 10.1 (2019)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 10.5'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 7.0 (2016)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 (2015)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 (2017)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 (2018)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 (2019)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 S & Pen (2015)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.0 S & Pen (2019)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 8.4 (2020)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 9.7'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A 9.7 S Pen'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A7 10.4 (2020)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A7 Lite'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab A8 10.5 (2021)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active 2'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active 3'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active 4 Pro'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Active Pro'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Advanced 2'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab E 8.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab E 9.6'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab J'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 10.1'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 10.1 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 12.2'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 12.2 3G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 12.2 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 8.4'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab Pro 8.4 3G/LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S 10.5'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S 10.5 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S 8.4'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S 8.4 LTE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S2 8.0'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S2 9.7'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S3 9.7'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S4 10.5'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S5e'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S6'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S6 5G'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S6 Lite'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S6 Lite (2022)'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S7'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S7 FE'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S7+'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S8'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S8 Ultra'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab S8+'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy Tab T-Mobile T849'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy View'],
    ['sub_category_type_one_id' => 103,'name' => 'Galaxy View2'],
    ['sub_category_type_one_id' => 103,'name' => 'Google Nexus 10 P8110'],
    ['sub_category_type_one_id' => 103,'name' => 'P1000 Galaxy Tab'],
    ['sub_category_type_one_id' => 103,'name' => 'P1010 Galaxy Tab'],
    ['sub_category_type_one_id' => 103,'name' => 'P6200 Galaxy Tab 7.0 Plus'],
    ['sub_category_type_one_id' => 103,'name' => 'P6210 Galaxy Tab 7.0 Plus'],
    ['sub_category_type_one_id' => 103,'name' => 'P6800 Galaxy Tab 7.7'],
    ['sub_category_type_one_id' => 103,'name' => 'P6810 Galaxy Tab 7.7'],
    ['sub_category_type_one_id' => 103,'name' => 'P7500 Galaxy Tab 10.1 3G'],

    ['sub_category_type_one_id' => 104,'name' => 'Tablet P'],/*id 601*/
    ['sub_category_type_one_id' => 104,'name' => 'Tablet P 3G'],
    ['sub_category_type_one_id' => 104,'name' => 'Tablet S'],
    ['sub_category_type_one_id' => 104,'name' => 'Tablet S 3G'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Tablet S'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Tablet S 3G'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Tablet Z'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Tablet Z LTE'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Z2 Tablet'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Z2 Tablet LTE'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Z3 Tablet Compact'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Z4 Tablet'],
    ['sub_category_type_one_id' => 104,'name' => 'Xperia Z4 Tablet LTE'],

    ['sub_category_type_one_id' => 105,'name' => '10 TabMax'],/*614*/
    ['sub_category_type_one_id' => 105,'name' => '10 TabMid'],
    ['sub_category_type_one_id' => 105,'name' => 'NxtPaper'],
    ['sub_category_type_one_id' => 105,'name' => 'NxtPaper 10s'],
    ['sub_category_type_one_id' => 105,'name' => 'Tab 10 HD 4G'],
    ['sub_category_type_one_id' => 105,'name' => 'Tab 10L'],
    ['sub_category_type_one_id' => 105,'name' => 'Tab 10s'],
    ['sub_category_type_one_id' => 105,'name' => 'Tab 10s 5G'],
    ['sub_category_type_one_id' => 105,'name' => 'Tab 8 4G'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite 10 AT305'],/*623*/
    ['sub_category_type_one_id' => 106,'name' => 'Excite 10 SE'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite 13 AT335'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite 7.7 AT275'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite 7c AT7-B8'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite AT200'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite Go'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite Pro'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite Pure'],
    ['sub_category_type_one_id' => 106,'name' => 'Excite Write'],
    ['sub_category_type_one_id' => 106,'name' => 'Thrive'],
    ['sub_category_type_one_id' => 106,'name' => 'Thrive 7'],

    ['sub_category_type_one_id' => 107,'name' => 'Mi Pad 2'],/*635*/
    ['sub_category_type_one_id' => 107,'name' => 'Mi Pad 3'],
    ['sub_category_type_one_id' => 107,'name' => 'Mi Pad 4'],
    ['sub_category_type_one_id' => 107,'name' => 'Mi Pad 4 Plus'],
    ['sub_category_type_one_id' => 107,'name' => 'Mi Pad 7.9'],
    ['sub_category_type_one_id' => 107,'name' => 'Pad 5'],
    ['sub_category_type_one_id' => 107,'name' => 'Pad 5 Pro 12.4'],

    ['sub_category_type_one_id' => 108,'name' => 'Grand X View 2'],/*642*/
    ['sub_category_type_one_id' => 108,'name' => 'Light Tab 2 V9A'],
    ['sub_category_type_one_id' => 108,'name' => 'Light Tab 3 V9S'],
    ['sub_category_type_one_id' => 108,'name' => 'Light Tab 300'],
    ['sub_category_type_one_id' => 108,'name' => 'Light Tab V9C'],
    ['sub_category_type_one_id' => 108,'name' => 'Optik'],
    ['sub_category_type_one_id' => 108,'name' => 'T98'],
    ['sub_category_type_one_id' => 108,'name' => 'V81'],
    ['sub_category_type_one_id' => 108,'name' => 'V9'],
    ['sub_category_type_one_id' => 108,'name' => 'V9+'],
    ['sub_category_type_one_id' => 108,'name' => 'V96'],
];