<?php


$cars = [
    ['sub_category_id' => 1,'image' => 'alfaromeo.png',  'name' => 'Alfa Romeo', 'title' => 'alfaromeo'],
    ['sub_category_id' => 1,'image' => 'astonmartin.png',  'name' => 'Aston Martin', 'title' => 'astonmartin'],
    ['sub_category_id' => 1,'image' => 'atv.png',  'name' => 'Atv', 'title' => 'atv'],
    ['sub_category_id' => 1,'image' => 'audi.png',  'name' => 'Audi', 'title' => 'audi'],
    ['sub_category_id' => 1,'image' => 'baic.png',  'name' => 'Baic', 'title' => 'baic'],
    ['sub_category_id' => 1,'image' => 'bajaj.png',  'name' => 'Bajaj', 'title' => 'bajaj'],
    ['sub_category_id' => 1,'image' => 'bentley.png',  'name' => 'Bentley', 'title' => 'bentley'],
    ['sub_category_id' => 1,'image' => 'bmc.png',  'name' => 'BMC', 'title' => 'bmc'],
    ['sub_category_id' => 1,'image' => 'bmw.png',  'name' => 'BMW', 'title' => 'bmw'],
    ['sub_category_id' => 1,'image' => 'bmwalpina.jpg',  'name' => 'Bmw Alpina', 'title' => 'bmwalpina'],
    ['sub_category_id' => 1,'image' => 'brilliance.png',  'name' => 'Brilliance', 'title' => 'brilliance'],
    ['sub_category_id' => 1,'image' => 'buick.png',  'name' => 'Buick', 'title' => 'buick'],
    ['sub_category_id' => 1,'image' => 'byd.png',  'name' => 'Byd', 'title' => 'byd'],
    ['sub_category_id' => 1,'image' => 'cadillac.png',  'name' => 'Cadillac', 'title' => 'cadillac'],
    ['sub_category_id' => 1,'image' => 'changan.png',  'name' => 'Changan', 'title' => 'changan'],
    ['sub_category_id' => 1,'image' => 'chery.png',  'name' => 'Chery', 'title' => 'chery'],
    ['sub_category_id' => 1,'image' => 'chevrolet.png',  'name' => 'Chevrolet', 'title' => 'chevrolet'],
    ['sub_category_id' => 1,'image' => 'chrysler.png',  'name' => 'Chrysler', 'title' => 'chrysler'],
    ['sub_category_id' => 1,'image' => 'citroen.png',  'name' => 'Citroen', 'title' => 'citroen'],
    ['sub_category_id' => 1,'image' => 'dacia.png',  'name' => 'Dacia', 'title' => 'dacia'],
    ['sub_category_id' => 1,'image' => 'daewoo.png',  'name' => 'Daewoo', 'title' => 'daewoo'],
    ['sub_category_id' => 1,'image' => 'daf.png',  'name' => 'Daf', 'title' => 'daf'],
    ['sub_category_id' => 1,'image' => 'daihatsu.png',  'name' => 'Daihatsu', 'title' => 'daihatsu'],
    ['sub_category_id' => 1,'image' => 'dayun.jpg',  'name' => 'Dayun', 'title' => 'dayun'],
    ['sub_category_id' => 1,'image' => 'dnepr.png',  'name' => 'Dnepr', 'title' => 'dnepr'],
    ['sub_category_id' => 1,'image' => 'dodge.png',  'name' => 'Dodge', 'title' => 'dodge'],
    ['sub_category_id' => 1,'image' => 'dongfeng.png',  'name' => 'DongFeng', 'title' => 'dongfeng'],
    ['sub_category_id' => 1,'image' => 'ducati.png',  'name' => 'Ducati', 'title' => 'ducati'],
    ['sub_category_id' => 1,'image' => 'faw.png',  'name' => 'Faw', 'title' => 'faw'],
    ['sub_category_id' => 1,'image' => 'ferrary.png',  'name' => 'Ferrary', 'title' => 'ferrary'],
    ['sub_category_id' => 1,'image' => 'fiat.png',  'name' => 'Fiat', 'title' => 'fiat'],
    ['sub_category_id' => 1,'image' => 'ford.png',  'name' => 'Ford', 'title' => 'ford'],
    ['sub_category_id' => 1,'image' => 'foton.png',  'name' => 'Foton', 'title' => 'foton'],
    ['sub_category_id' => 1,'image' => 'gac.jpg',  'name' => 'Gac', 'title' => 'gac'],
    ['sub_category_id' => 1,'image' => 'gaz.jpeg',  'name' => 'Gaz', 'title' => 'gaz'],
    ['sub_category_id' => 1,'image' => 'geely.png',  'name' => 'Geely', 'title' => 'geely'],
    ['sub_category_id' => 1,'image' => 'gmc.jpg',  'name' => 'Gmc', 'title' => 'gmc'],
    ['sub_category_id' => 1,'image' => 'greatwall.jpg',  'name' => 'Great Wall', 'title' => 'greatwall'],
    ['sub_category_id' => 1,'image' => 'haojue.png',  'name' => 'Haojue', 'title' => 'haojue'],
    ['sub_category_id' => 1,'image' => 'harleydavidson.png',  'name' => 'Harley Davidson', 'title' => 'harleydavidson'],
    ['sub_category_id' => 1,'image' => 'haval.png',  'name' => 'Haval', 'title' => 'haval'],
    ['sub_category_id' => 1,'image' => 'honda.png', 'name' => 'Honda', 'title' => 'honda'],
    ['sub_category_id' => 1,'image' => 'howo.png', 'name' => 'Howo', 'title' => 'howo'],
    ['sub_category_id' => 1,'image' => 'hummer.jpg', 'name' => 'Hummer', 'title' => 'hummer'],
    ['sub_category_id' => 1,'image' => 'hyundai.png', 'name' => 'Hyundai', 'title' => 'hyundai'],
    ['sub_category_id' => 1,'image' => 'ij.jpg', 'name' => 'IJ', 'title' => 'ij'],
    ['sub_category_id' => 1,'image' => 'infiniti.png', 'name' => 'Infiniti', 'title' => 'infiniti'],
    ['sub_category_id' => 1,'image' => 'irankhodro.png', 'name' => 'Iran Khodro', 'title' => 'irankhodro'],
    ['sub_category_id' => 1,'image' => 'isuzu.jpg', 'name' => 'Isuzu', 'title' => 'isuzu'],
    ['sub_category_id' => 1,'image' => 'iveco.png', 'name' => 'Iveco', 'title' => 'iveco'],
    ['sub_category_id' => 1,'image' => 'jac.png', 'name' => 'JAC', 'title' => 'jac'],
    ['sub_category_id' => 1,'image' => 'jaguar.png', 'name' => 'Jaguar', 'title' => 'jaguar'],
    ['sub_category_id' => 1,'image' => 'jep.jpg', 'name' => 'Jep', 'title' => 'jep'],
    ['sub_category_id' => 1,'image' => 'jonway.jpg', 'name' => 'Jonway', 'title' => 'jonway'],
    ['sub_category_id' => 1,'image' => 'kamaz.jpg', 'name' => 'KamAz', 'title' => 'kamaz'],
    ['sub_category_id' => 1,'image' => 'kavz.png', 'name' => 'KAvZ', 'title' => 'kavz'],
    ['sub_category_id' => 1,'image' => 'kawaski.png', 'name' => 'Kawaski', 'title' => 'kawaski'],
    ['sub_category_id' => 1,'image' => 'khazar.png', 'name' => 'Khazar', 'title' => 'khazar'],
    ['sub_category_id' => 1,'image' => 'kia.png', 'name' => 'Kia', 'title' => 'kia'],
    ['sub_category_id' => 1,'image' => 'kinroad.png', 'name' => 'Kinroad', 'title' => 'kinroad'],
    ['sub_category_id' => 1,'image' => 'kraz.png', 'name' => 'KrAz', 'title' => 'kraz'],
    ['sub_category_id' => 1,'image' => 'ktm.png', 'name' => 'KTM', 'title' => 'ktm'],
    ['sub_category_id' => 1,'image' => 'kuba.jpg', 'name' => 'Kuba', 'title' => 'kuba'],
    ['sub_category_id' => 1,'image' => 'vaz.png', 'name' => 'Lada (VAZ)', 'title' => 'vaz'],
    ['sub_category_id' => 1,'image' => 'lamborghini.png', 'name' => 'Lamborghini', 'title' => 'lamborghini'],
    ['sub_category_id' => 1,'image' => 'landrover.png', 'name' => 'Land Rover', 'title' => 'landrover'],
    ['sub_category_id' => 1,'image' => 'lexus.png', 'name' => 'Lexus', 'title' => 'lexus'],
    ['sub_category_id' => 1,'image' => 'lifan.png', 'name' => 'Lifan', 'title' => 'lifan'],
    ['sub_category_id' => 1,'image' => 'lincoln.png', 'name' => 'Lincoln', 'title' => 'lincoln'],
    ['sub_category_id' => 1,'image' => 'luaz.jpg', 'name' => 'LuAz', 'title' => 'luaz'],
    ['sub_category_id' => 1,'image' => 'man.png', 'name' => 'Man', 'title' => 'man'],
    ['sub_category_id' => 1,'image' => 'maserati.png', 'name' => 'Maserati', 'title' => 'maserati'],
    ['sub_category_id' => 1,'image' => 'maz.png', 'name' => 'Maz', 'title' => 'maz'],
    ['sub_category_id' => 1,'image' => 'mazda.png', 'name' => 'Mazda', 'title' => 'mazda'],
    ['sub_category_id' => 1,'image' => 'mclaren.jpg', 'name' => 'McLaren', 'title' => 'mclaren'],
    ['sub_category_id' => 1,'image' => 'megelli.png', 'name' => 'Megelli', 'title' => 'megelli'],
    ['sub_category_id' => 1,'image' => 'mercedes.png', 'name' => 'Mercedes', 'title' => 'mercedes'],
    ['sub_category_id' => 1,'image' => 'maybach.png', 'name' => 'Mercedes-Maybach', 'title' => 'maybach'],
    ['sub_category_id' => 1,'image' => 'mg.png', 'name' => 'MG', 'title' => 'mg'],
    ['sub_category_id' => 1,'image' => 'mini.png', 'name' => 'Mini', 'title' => 'mini'],
    ['sub_category_id' => 1,'image' => 'minsk.png', 'name' => 'Minsk', 'title' => 'minsk'],
    ['sub_category_id' => 1,'image' => 'mitsubishi.png', 'name' => 'Mitsubishi', 'title' => 'mitsubishi'],
    ['sub_category_id' => 1,'image' => 'mondial.png', 'name' => 'Mondial', 'title' => 'mondial'],
    ['sub_category_id' => 1,'image' => 'moskvich.png', 'name' => 'moskvich', 'title' => 'moskvich'],
    ['sub_category_id' => 1,'image' => 'muravey.jpg', 'name' => 'Muravey', 'title' => 'muravey'],
    ['sub_category_id' => 1,'image' => 'nama.jpg', 'name' => 'Nama', 'title' => 'nama'],
    ['sub_category_id' => 1,'image' => 'neoplan.jpg', 'name' => 'Neoplan', 'title' => 'neoplan'],
    ['sub_category_id' => 1,'image' => 'neptun.jpg', 'name' => 'Neptun', 'title' => 'neptun'],
    ['sub_category_id' => 1,'image' => 'nissan.png', 'name' => 'Nissan', 'title' => 'nissan'],
    ['sub_category_id' => 1,'image' => 'opel.png', 'name' => 'Opel', 'title' => 'opel'],
    ['sub_category_id' => 1,'image' => 'otokar.png', 'name' => 'Otokar', 'title' => 'otokar'],
    ['sub_category_id' => 1,'image' => 'paz.png', 'name' => 'Paz', 'title' => 'paz'],
    ['sub_category_id' => 1,'image' => 'peugeot.png', 'name' => 'Peugeot', 'title' => 'peugeot'],
    ['sub_category_id' => 1,'image' => 'piaggio.jpg', 'name' => 'Piaggio', 'title' => 'piaggio'],
    ['sub_category_id' => 1,'image' => 'renault.png', 'name' => 'Pontiac', 'title' => 'renault'],
    ['sub_category_id' => 1,'image' => 'renault.png', 'name' => 'Porsche', 'title' => 'renault'],
    ['sub_category_id' => 1,'image' => 'renault.jpg', 'name' => 'Ravon', 'title' => 'renault'],
    ['sub_category_id' => 1,'image' => 'renault.png', 'name' => 'Renault', 'title' => 'renault'],
    ['sub_category_id' => 1,'image' => 'rollsroyce.png','name' => 'Rolls-Royce', 'title' => 'rollsroyce'],
    ['sub_category_id' => 1,'image' => 'rover.png','name' => 'Rover', 'title' => 'rover'],
    ['sub_category_id' => 1,'image' => 'saab.jpg', 'name' => 'Saab', 'title' => 'saab'],
    ['sub_category_id' => 1,'image' => 'saipa.jpg', 'name' => 'Saipa', 'title' => 'saipa'],
    ['sub_category_id' => 1,'image' => 'scania.jpg', 'name' => 'Scania', 'title' => 'scania'],
    ['sub_category_id' => 1,'image' => 'seat.png', 'name' => 'SEAT', 'title' => 'seat'],
    ['sub_category_id' => 1,'image' => 'shacman.png', 'name' => 'Shacman', 'title' => 'shacman'],
    ['sub_category_id' => 1,'image' => 'shaolin.png', 'name' => 'Shaolin', 'title' => 'shaolin'],
    ['sub_category_id' => 1,'image' => 'skoda.png', 'name' => 'Skoda', 'title' => 'skoda'],
    ['sub_category_id' => 1,'image' => 'smart.jpg', 'name' => 'Smart', 'title' => 'smart'],
    ['sub_category_id' => 1,'image' => 'ssangyong.png', 'name' => 'Ssang Yong', 'title' => 'ssangyong'],
    ['sub_category_id' => 1,'image' => 'subaru.png', 'name' => 'Subaru', 'title' => 'subaru'],
    ['sub_category_id' => 1,'image' => 'suzuki.png', 'name' => 'suzuki', 'title' => 'suzuki'],
    ['sub_category_id' => 1,'image' => 'tata.jpg', 'name' => 'Tata', 'title' => 'tata'],
    ['sub_category_id' => 1,'image' => 'tesla.png', 'name' => 'Tesla', 'title' => 'tesla'],
    ['sub_category_id' => 1,'image' => 'tofas.png', 'name' => 'Tofas', 'title' => 'tofas'],
    ['sub_category_id' => 1,'image' => 'toyota.png','name' => 'Toyota', 'title' => 'toyota'],
    ['sub_category_id' => 1,'image' => 'uaz.jpg', 'name' => 'UAZ', 'title' => 'uaz'],
    ['sub_category_id' => 1,'image' => 'ural.jpg', 'name' => 'Ural', 'title' => 'ural'],
    ['sub_category_id' => 1,'image' => 'vespa.png', 'name' => 'Vespa', 'title' => 'vespa'],
    ['sub_category_id' => 1,'image' => 'volkswagen.png','name' => 'Volkswagen', 'title' => 'volkswagen'],
    ['sub_category_id' => 1,'image' => 'volvo.png', 'name' => 'Volvo', 'title' => 'volvo'],
    ['sub_category_id' => 1,'image' => 'vosxod.png', 'name' => 'Vosxod', 'title' => 'vosxod'],
    ['sub_category_id' => 1,'image' => 'yamaha.jpg', 'name' => 'Yamaha', 'title' => 'yamaha'],
    ['sub_category_id' => 1,'image' => 'zaz.jpg', 'name' => 'ZAZ', 'title' => 'zaz'],
    ['sub_category_id' => 1,'image' => 'zil.png', 'name' => 'ZIL', 'title' => 'zil'],
    ['sub_category_id' => 1,'image' => 'zongshen.png', 'name' => 'Zongshen', 'title' => 'zongshen'],
    ['sub_category_id' => 1, 'image' => 'zontes.jpg','name' => 'Zontes', 'title' => 'zontes'],
];

$car_models = [
    ['title' => '4C', 'marka_id' => 1],
    ['title' => 'Giulia', 'marka_id' => 1],
    ['title' => 'Giulietta', 'marka_id' => 1],
    ['title' => 'Mito', 'marka_id' => 1],
    ['title' => 'Stelvio', 'marka_id' => 1],

    ['title' => 'Rapide', 'marka_id' => 2],
    ['title' => 'Vanquish', 'marka_id' => 2],

    ['title' => '150', 'marka_id' => 3],
    ['title' => 'Hummer 250', 'marka_id' => 3],

    ['title' => '100', 'marka_id' => 4],
    ['title' => '80', 'marka_id' => 4],
    ['title' => 'A3', 'marka_id' => 4],
    ['title' => 'A4', 'marka_id' => 4],
    ['title' => 'A5', 'marka_id' => 4],
    ['title' => 'A6', 'marka_id' => 4],
    ['title' => 'A7', 'marka_id' => 4],
    ['title' => 'A8', 'marka_id' => 4],
    ['title' => 'Allroad', 'marka_id' => 4],
    ['title' => 'Q3', 'marka_id' => 4],
    ['title' => 'Q5', 'marka_id' => 4],
    ['title' => 'Q7', 'marka_id' => 4],
    ['title' => 'Q8', 'marka_id' => 4],
    ['title' => 'R8', 'marka_id' => 4],
    ['title' => 'RS7', 'marka_id' => 4],
    ['title' => 'S5', 'marka_id' => 4],
    ['title' => 'S6', 'marka_id' => 4],
    ['title' => 'S7', 'marka_id' => 4],
    ['title' => 'S8', 'marka_id' => 4],
    ['title' => 'TT', 'marka_id' => 4],
    ['title' => 'V8', 'marka_id' => 4],

    ['title' => 'A113/A115', 'marka_id' => 5],
    ['title' => 'M 20', 'marka_id' => 5],
    ['title' => 'M 60', 'marka_id' => 5],

    ['title' => 'Pulsar NS200', 'marka_id' => 6],
    ['title' => 'V', 'marka_id' => 6],

    ['title' => 'Bentayga', 'marka_id' => 7],
    ['title' => 'Continental', 'marka_id' => 7],
    ['title' => 'Flying Spur', 'marka_id' => 7],
    ['title' => 'Mulsanne', 'marka_id' => 7],

    ['title' => 'Pro 827', 'marka_id' => 8],
    ['title' => 'Pro 832', 'marka_id' => 8],

    ['title' => '120', 'marka_id' => 9],
    ['title' => '316', 'marka_id' => 9],
    ['title' => '318', 'marka_id' => 9],
    ['title' => '320', 'marka_id' => 9],
    ['title' => '320 GT', 'marka_id' => 9],
    ['title' => '323', 'marka_id' => 9],
    ['title' => '325', 'marka_id' => 9],
    ['title' => '328', 'marka_id' => 9],
    ['title' => '330', 'marka_id' => 9],
    ['title' => '335', 'marka_id' => 9],
    ['title' => '520', 'marka_id' => 9],
    ['title' => '523', 'marka_id' => 9],
    ['title' => '525', 'marka_id' => 9],
    ['title' => '528', 'marka_id' => 9],
    ['title' => '530', 'marka_id' => 9],
    ['title' => '535', 'marka_id' => 9],
    ['title' => '535 GT', 'marka_id' => 9],
    ['title' => '540', 'marka_id' => 9],
    ['title' => '545', 'marka_id' => 9],
    ['title' => '728', 'marka_id' => 9],
    ['title' => '730', 'marka_id' => 9],
    ['title' => '735', 'marka_id' => 9],
    ['title' => '740', 'marka_id' => 9],
    ['title' => '745', 'marka_id' => 9],
    ['title' => '750', 'marka_id' => 9],
    ['title' => '760', 'marka_id' => 9],
    ['title' => '630', 'marka_id' => 9],
    ['title' => '640', 'marka_id' => 9],
    ['title' => '645', 'marka_id' => 9],
    ['title' => '650', 'marka_id' => 9],
    ['title' => 'M4', 'marka_id' => 9],
    ['title' => 'M5', 'marka_id' => 9],
    ['title' => 'M6', 'marka_id' => 9],
    ['title' => 'M760', 'marka_id' => 9],
    ['title' => 'X5 M', 'marka_id' => 9],
    ['title' => 'X6 M', 'marka_id' => 9],
    ['title' => 'X1', 'marka_id' => 9],
    ['title' => 'X2', 'marka_id' => 9],
    ['title' => 'X3', 'marka_id' => 9],
    ['title' => 'X5', 'marka_id' => 9],
    ['title' => 'X6', 'marka_id' => 9],
    ['title' => 'X7', 'marka_id' => 9],
    ['title' => 'R 1200 GS', 'marka_id' => 9],
    ['title' => '420', 'marka_id' => 9],
    ['title' => '428', 'marka_id' => 9],
    ['title' => '430', 'marka_id' => 9],
    ['title' => 'i3', 'marka_id' => 9],
    ['title' => 'i8', 'marka_id' => 9],
    ['title' => '220', 'marka_id' => 9],
    ['title' => '228', 'marka_id' => 9],

    ['title' => 'B7', 'marka_id' => 10],

    ['title' => 'V7', 'marka_id' => 11],

    ['title' => 'Enclave', 'marka_id' => 12],
    ['title' => 'Encore', 'marka_id' => 12],
    ['title' => 'LaCrosse', 'marka_id' => 12],

    ['title' => 'F3', 'marka_id' => 13],
    ['title' => 'F6', 'marka_id' => 13],
    ['title' => 'S6', 'marka_id' => 13],

    ['title' => 'ATS', 'marka_id' => 14],
    ['title' => 'CT6', 'marka_id' => 14],
    ['title' => 'CTS', 'marka_id' => 14],
    ['title' => 'DTS', 'marka_id' => 14],
    ['title' => 'Escalade', 'marka_id' => 14],
    ['title' => 'Fleetwood', 'marka_id' => 14],
    ['title' => 'SRX', 'marka_id' => 14],
    ['title' => 'XTS', 'marka_id' => 14],

    ['title' => 'Alsvin', 'marka_id' => 15],
    ['title' => 'Alsvin V3', 'marka_id' => 15],
    ['title' => 'Alsvin V7', 'marka_id' => 15],
    ['title' => 'Benni', 'marka_id' => 15],
    ['title' => 'CS 15', 'marka_id' => 15],
    ['title' => 'CS 35', 'marka_id' => 15],
    ['title' => 'CS 75', 'marka_id' => 15],
    ['title' => 'CS 85', 'marka_id' => 15],
    ['title' => 'CS 95', 'marka_id' => 15],
    ['title' => 'CX 20', 'marka_id' => 15],
    ['title' => 'Eado', 'marka_id' => 15],
    ['title' => 'Eado DT', 'marka_id' => 15],
    ['title' => 'EU-Love', 'marka_id' => 15],
    ['title' => 'F70', 'marka_id' => 15],
    ['title' => 'Honor', 'marka_id' => 15],
    ['title' => 'Raeton', 'marka_id' => 15],
    ['title' => 'Star', 'marka_id' => 15],

    ['title' => 'A-15 Cowin/Amulet', 'marka_id' => 16],
    ['title' => 'A1-13/Kimo', 'marka_id' => 16],
    ['title' => 'Arrizo 5', 'marka_id' => 16],
    ['title' => 'Arrizo 7', 'marka_id' => 16],
    ['title' => 'B11/Eastar', 'marka_id' => 16],
    ['title' => 'E5', 'marka_id' => 16],
    ['title' => 'Fora', 'marka_id' => 16],
    ['title' => 'Fulwin 2', 'marka_id' => 16],
    ['title' => 'QQ', 'marka_id' => 16],
    ['title' => 'Tiggo', 'marka_id' => 16],
    ['title' => 'Tiggo 2', 'marka_id' => 16],

    ['title' => 'Aveo', 'marka_id' => 17],
    ['title' => 'Camaro', 'marka_id' => 17],
    ['title' => 'Caprice', 'marka_id' => 17],
    ['title' => 'Captiva', 'marka_id' => 17],
    ['title' => 'Cavalier', 'marka_id' => 17],
    ['title' => 'Cobalt', 'marka_id' => 17],
    ['title' => 'Cruze', 'marka_id' => 17],
    ['title' => 'Epica', 'marka_id' => 17],
    ['title' => 'Equinox', 'marka_id' => 17],
    ['title' => 'Express', 'marka_id' => 17],
    ['title' => 'Kalos', 'marka_id' => 17],
    ['title' => 'Lacetti', 'marka_id' => 17],
    ['title' => 'Lumina', 'marka_id' => 17],
    ['title' => 'Malibu', 'marka_id' => 17],
    ['title' => 'Niva', 'marka_id' => 17],
    ['title' => 'Orlando', 'marka_id' => 17],
    ['title' => 'Silverado', 'marka_id' => 17],
    ['title' => 'Spark', 'marka_id' => 17],
    ['title' => 'Suburban', 'marka_id' => 17],
    ['title' => 'Traverse', 'marka_id' => 17],
    ['title' => 'Trax', 'marka_id' => 17],
    ['title' => 'Volt', 'marka_id' => 17],

    ['title' => '200', 'marka_id' => 18],
    ['title' => '300C', 'marka_id' => 18],
    ['title' => 'Crossfire', 'marka_id' => 18],
    ['title' => 'Neon', 'marka_id' => 18],
    ['title' => 'PT Cruiser', 'marka_id' => 18],
    ['title' => 'Sebring', 'marka_id' => 18],
    ['title' => 'Town & Country', 'marka_id' => 18],
    ['title' => 'Voyager', 'marka_id' => 18],

    ['title' => 'C-Elysee', 'marka_id' => 19],
    ['title' => 'C3', 'marka_id' => 19],
    ['title' => 'C4', 'marka_id' => 19],
    ['title' => 'C5', 'marka_id' => 19],
    ['title' => 'DS5', 'marka_id' => 19],

    ['title' => 'Lodgy', 'marka_id' => 20],
    ['title' => 'Logan', 'marka_id' => 20],

    ['title' => 'BS090', 'marka_id' => 21],
    ['title' => 'Damas', 'marka_id' => 21],
    ['title' => 'Espero', 'marka_id' => 21],
    ['title' => 'Gentra', 'marka_id' => 21],
    ['title' => 'Labo', 'marka_id' => 21],
    ['title' => 'Lanos', 'marka_id' => 21],
    ['title' => 'Leganza', 'marka_id' => 21],
    ['title' => 'Matiz', 'marka_id' => 21],
    ['title' => 'Musso', 'marka_id' => 21],
    ['title' => 'Nexia', 'marka_id' => 21],
    ['title' => 'Nubira', 'marka_id' => 21],
    ['title' => 'Racer', 'marka_id' => 21],
    ['title' => 'Super Salon', 'marka_id' => 21],
    ['title' => 'Tico', 'marka_id' => 21],

    ['title' => '105XF', 'marka_id' => 22],
    ['title' => '85CF', 'marka_id' => 22],
    ['title' => '95XF', 'marka_id' => 22],
    ['title' => 'CF 290', 'marka_id' => 22],

    ['title' => 'Materia', 'marka_id' => 23],
    ['title' => 'Mira', 'marka_id' => 23],
    ['title' => 'Sirion', 'marka_id' => 23],
    ['title' => 'Terios', 'marka_id' => 23],

    ['title' => 'DY125-B', 'marka_id' => 24],
    ['title' => 'DY150-12', 'marka_id' => 24],

    ['title' => '11', 'marka_id' => 25],
    ['title' => 'K-750', 'marka_id' => 25],

    ['title' => 'Caliber', 'marka_id' => 26],
    ['title' => 'Challenger', 'marka_id' => 26],
    ['title' => 'Charger', 'marka_id' => 26],
    ['title' => 'Dart', 'marka_id' => 26],
    ['title' => 'Durango', 'marka_id' => 26],
    ['title' => 'Durango', 'marka_id' => 26],
    ['title' => 'Neon', 'marka_id' => 26],

    ['title' => 'DFL3310A13', 'marka_id' => 27],
    ['title' => 'EQ5081JSQG', 'marka_id' => 27],
    ['title' => 'Fengshen A30', 'marka_id' => 27],
    ['title' => 'Fengshen A30', 'marka_id' => 27],

    ['title' => '1100 EVO', 'marka_id' => 28],
    ['title' => '848 EVO Corse', 'marka_id' => 28],

    ['title' => 'CA6350', 'marka_id' => 29],
    ['title' => 'Bestune T33', 'marka_id' => 29],
    ['title' => 'Bestune T77', 'marka_id' => 29],
    ['title' => 'Bestune T99', 'marka_id' => 29],
    ['title' => 'Besturn B 50', 'marka_id' => 29],
    ['title' => 'Hongqi HS5', 'marka_id' => 29],
    ['title' => 'Hongqi HS7', 'marka_id' => 29],
    ['title' => 'Oley', 'marka_id' => 29],

    ['title' => '458 Italia', 'marka_id' => 30],
    ['title' => '458 Speciale', 'marka_id' => 30],
    ['title' => 'California', 'marka_id' => 30],

    ['title' => '500L', 'marka_id' => 31],
    ['title' => 'Albea', 'marka_id' => 31],
    ['title' => 'Bravo', 'marka_id' => 31],
    ['title' => 'Doblo', 'marka_id' => 31],
    ['title' => 'Egea', 'marka_id' => 31],
    ['title' => 'Fiorino', 'marka_id' => 31],
    ['title' => 'Linea', 'marka_id' => 31],
    ['title' => 'Punto', 'marka_id' => 31],
    ['title' => 'Qubo', 'marka_id' => 31],
    ['title' => 'Tempra', 'marka_id' => 31],
    ['title' => 'Ulysse', 'marka_id' => 31],

    ['title' => 'C-Max', 'marka_id' => 32],
    ['title' => 'Cargo', 'marka_id' => 32],
    ['title' => 'Courier', 'marka_id' => 32],
    ['title' => 'Edge', 'marka_id' => 32],
    ['title' => 'Escape', 'marka_id' => 32],
    ['title' => 'Escort', 'marka_id' => 32],
    ['title' => 'Expedition', 'marka_id' => 32],
    ['title' => 'Explorer', 'marka_id' => 32],
    ['title' => 'F-150', 'marka_id' => 32],
    ['title' => 'Fiesta', 'marka_id' => 32],
    ['title' => 'Focus', 'marka_id' => 32],
    ['title' => 'Fusion', 'marka_id' => 32],
    ['title' => 'Galaxy', 'marka_id' => 32],
    ['title' => 'Kuga', 'marka_id' => 32],
    ['title' => 'Maverick', 'marka_id' => 32],
    ['title' => 'Mercury', 'marka_id' => 32],
    ['title' => 'Mondeo', 'marka_id' => 32],
    ['title' => 'Mustang', 'marka_id' => 32],
    ['title' => 'Ranger', 'marka_id' => 32],
    ['title' => 'Scorpio', 'marka_id' => 32],
    ['title' => 'Tourneo Connect', 'marka_id' => 32],
    ['title' => 'Tourneo Custom', 'marka_id' => 32],
    ['title' => 'Transit', 'marka_id' => 32],

    ['title' => 'Aumark TX', 'marka_id' => 33],
    ['title' => 'Forland', 'marka_id' => 33],
    ['title' => 'Ollin', 'marka_id' => 33],
    ['title' => 'SUP', 'marka_id' => 33],

    ['title' => 'GA 5', 'marka_id' => 34],
    ['title' => 'GS 4', 'marka_id' => 34],
    ['title' => 'GS 5', 'marka_id' => 34],
    ['title' => 'GS 8', 'marka_id' => 34],

    ['title' => '24', 'marka_id' => 35],
    ['title' => '24-10', 'marka_id' => 35],
    ['title' => '2705', 'marka_id' => 35],
    ['title' => '2705-757', 'marka_id' => 35],
    ['title' => '2705-764', 'marka_id' => 35],
    ['title' => '27527-745', 'marka_id' => 35],
    ['title' => '2757', 'marka_id' => 35],
    ['title' => '3102', 'marka_id' => 35],
    ['title' => '31029', 'marka_id' => 35],
    ['title' => '3110', 'marka_id' => 35],
    ['title' => '31105', 'marka_id' => 35],
    ['title' => '3111', 'marka_id' => 35],
    ['title' => '32212', 'marka_id' => 35],
    ['title' => '3302-744', 'marka_id' => 35],
    ['title' => '330200', 'marka_id' => 35],
    ['title' => '330202-740', 'marka_id' => 35],
    ['title' => '33021', 'marka_id' => 35],
    ['title' => '33023-744', 'marka_id' => 35],
    ['title' => '330232-744', 'marka_id' => 35],
    ['title' => '33027-745', 'marka_id' => 35],
    ['title' => '33027-745', 'marka_id' => 35],
    ['title' => '3309-352', 'marka_id' => 35],
    ['title' => '52', 'marka_id' => 35],
    ['title' => '53', 'marka_id' => 35],
    ['title' => '66', 'marka_id' => 35],
    ['title' => '69', 'marka_id' => 35],
    ['title' => 'A21R22-03', 'marka_id' => 35],
    ['title' => 'C41R13', 'marka_id' => 35],
    ['title' => 'Gazon C41R33', 'marka_id' => 35],
    ['title' => 'M-20 Pobeda', 'marka_id' => 35],
    ['title' => 'M-21', 'marka_id' => 35],
    ['title' => 'Next А31R32', 'marka_id' => 35],
    ['title' => 'Next A21R22-30', 'marka_id' => 35],
    ['title' => 'Next A21R32-30', 'marka_id' => 35],
    ['title' => 'Next A22R22-30', 'marka_id' => 35],
    ['title' => 'Next A22R32', 'marka_id' => 35],
    ['title' => 'Next A31R22', 'marka_id' => 35],
    ['title' => 'Next A32R32-40', 'marka_id' => 35],
    ['title' => 'Next A64R42-10', 'marka_id' => 35],
    ['title' => 'Next A65R32-40', 'marka_id' => 35],
    ['title' => 'Sadko Next C41A23', 'marka_id' => 35],
    ['title' => 'Siber', 'marka_id' => 35],
    ['title' => 'Sobol', 'marka_id' => 35],
    ['title' => 'Vector Next', 'marka_id' => 35],

    ['title' => 'CK', 'marka_id' => 36],
    ['title' => 'Emgrand EC7', 'marka_id' => 36],
    ['title' => 'Emgrand EC8', 'marka_id' => 36],
    ['title' => 'MK', 'marka_id' => 36],
    ['title' => 'TX4', 'marka_id' => 36],

    ['title' => 'Acadia', 'marka_id' => 37],
    ['title' => 'Envoy', 'marka_id' => 37],
    ['title' => 'Safari', 'marka_id' => 37],
    ['title' => 'Sierra', 'marka_id' => 37],
    ['title' => 'Terrain', 'marka_id' => 37],
    ['title' => 'Yukon', 'marka_id' => 37],

    ['title' => 'Florid', 'marka_id' => 38],
    ['title' => 'Hover H3', 'marka_id' => 38],
    ['title' => 'Hover H5', 'marka_id' => 38],
    ['title' => 'Hover H6', 'marka_id' => 38],
    ['title' => 'Hover M2', 'marka_id' => 38],
    ['title' => 'Hover M4', 'marka_id' => 38],
    ['title' => 'Voleex C30', 'marka_id' => 38],
    ['title' => 'Voleex C50', 'marka_id' => 38],
    ['title' => 'Wingle', 'marka_id' => 38],

    ['title' => 'HJ100T-7C', 'marka_id' => 39],
    ['title' => 'HJ150-11A', 'marka_id' => 39],
    ['title' => 'HJ150-3C', 'marka_id' => 39],
    ['title' => 'HJ150-9', 'marka_id' => 39],
    ['title' => 'HJ150-9A', 'marka_id' => 39],
    ['title' => 'TR150S', 'marka_id' => 39],
    ['title' => 'TZ125', 'marka_id' => 39],

    ['title' => 'CVO Convertible', 'marka_id' => 40],
    ['title' => 'FXDR', 'marka_id' => 40],
    ['title' => 'Sportster Custom 1200', 'marka_id' => 40],
    ['title' => 'Touring Road King', 'marka_id' => 40],
    ['title' => 'Touring Street Glide', 'marka_id' => 40],
    ['title' => 'Harley-Davidson XL883N Sportster Iron 883', 'marka_id' => 40],

    ['title' => 'H2', 'marka_id' => 41],
    ['title' => 'H6', 'marka_id' => 41],
    ['title' => 'H7', 'marka_id' => 41],
    ['title' => 'H8', 'marka_id' => 41],
    ['title' => 'H9', 'marka_id' => 41],

    ['title' => 'Dio AF', 'marka_id' => 42],
    ['title' => 'GLX 1800', 'marka_id' => 42],
    ['title' => 'Accord', 'marka_id' => 42],
    ['title' => 'City', 'marka_id' => 42],
    ['title' => 'Civic', 'marka_id' => 42],
    ['title' => 'CR-V', 'marka_id' => 42],
    ['title' => 'Dio AF 35', 'marka_id' => 42],
    ['title' => 'Element', 'marka_id' => 42],
    ['title' => 'Insight', 'marka_id' => 42],
    ['title' => 'Passport', 'marka_id' => 42],
    ['title' => 'Pilot', 'marka_id' => 42],

    ['title' => '371', 'marka_id' => 43],
    ['title' => 'A7', 'marka_id' => 43],
    ['title' => 'Sinotruk', 'marka_id' => 43],

    ['title' => 'H2', 'marka_id' => 44],
    ['title' => 'H3', 'marka_id' => 44],

    ['title' => 'Accent', 'marka_id' => 45],
    ['title' => 'Azera', 'marka_id' => 45],
    ['title' => 'Chorus', 'marka_id' => 45],
    ['title' => 'County', 'marka_id' => 45],
    ['title' => 'Coupe', 'marka_id' => 45],
    ['title' => 'Creta', 'marka_id' => 45],
    ['title' => 'Elantra', 'marka_id' => 45],
    ['title' => 'Equus', 'marka_id' => 45],
    ['title' => 'Excel', 'marka_id' => 45],
    ['title' => 'Galloper', 'marka_id' => 45],
    ['title' => 'Genesis', 'marka_id' => 45],
    ['title' => 'Genesis Coupe', 'marka_id' => 45],
    ['title' => 'Getz', 'marka_id' => 45],
    ['title' => 'Grand Santa Fe', 'marka_id' => 45],
    ['title' => 'Grandeur', 'marka_id' => 45],
    ['title' => 'H 100', 'marka_id' => 45],
    ['title' => 'H 350', 'marka_id' => 45],
    ['title' => 'H-1', 'marka_id' => 45],
    ['title' => 'HD-120', 'marka_id' => 45],
    ['title' => 'HD-45', 'marka_id' => 45],
    ['title' => 'HD-65', 'marka_id' => 45],
    ['title' => 'HD-72', 'marka_id' => 45],
    ['title' => 'HD-78', 'marka_id' => 45],
    ['title' => 'i10', 'marka_id' => 45],
    ['title' => 'i20', 'marka_id' => 45],
    ['title' => 'i30', 'marka_id' => 45],
    ['title' => 'i40', 'marka_id' => 45],
    ['title' => 'ix35', 'marka_id' => 45],
    ['title' => 'ix55', 'marka_id' => 45],
    ['title' => 'Matrix', 'marka_id' => 45],
    ['title' => 'Palisade', 'marka_id' => 45],
    ['title' => 'Santa Fe', 'marka_id' => 45],
    ['title' => 'Solaris', 'marka_id' => 45],
    ['title' => 'Sonata', 'marka_id' => 45],
    ['title' => 'Terracan', 'marka_id' => 45],
    ['title' => 'Tucson', 'marka_id' => 45],
    ['title' => 'Veloster', 'marka_id' => 45],
    ['title' => 'Veracruz', 'marka_id' => 45],
    ['title' => 'XG', 'marka_id' => 45],

    ['title' => '57', 'marka_id' => 46],
    ['title' => '6.113-05 (Unker)', 'marka_id' => 46],
    ['title' => 'Planeta 2', 'marka_id' => 46],
    ['title' => 'Planeta 5', 'marka_id' => 46],
    ['title' => 'Planeta 7', 'marka_id' => 46],
    ['title' => 'Upiter 5', 'marka_id' => 46],
    ['title' => '2126 Oda', 'marka_id' => 46],
    ['title' => '2717', 'marka_id' => 46],
    ['title' => '27175', 'marka_id' => 46],

    ['title' => 'G25', 'marka_id' => 47],
    ['title' => 'G35', 'marka_id' => 47],
    ['title' => 'G35x', 'marka_id' => 47],
    ['title' => 'G37S', 'marka_id' => 47],
    ['title' => 'M35', 'marka_id' => 47],
    ['title' => 'M37S', 'marka_id' => 47],
    ['title' => 'EX25', 'marka_id' => 47],
    ['title' => 'EX35', 'marka_id' => 47],
    ['title' => 'FX35', 'marka_id' => 47],
    ['title' => 'FX37', 'marka_id' => 47],
    ['title' => 'FX45', 'marka_id' => 47],
    ['title' => 'JX35', 'marka_id' => 47],
    ['title' => 'Q45', 'marka_id' => 47],
    ['title' => 'Q50', 'marka_id' => 47],
    ['title' => 'Q50S', 'marka_id' => 47],
    ['title' => 'Q70', 'marka_id' => 47],
    ['title' => 'Q70S', 'marka_id' => 47],
    ['title' => 'QX4', 'marka_id' => 47],
    ['title' => 'QX56', 'marka_id' => 47],
    ['title' => 'QX60', 'marka_id' => 47],
    ['title' => 'QX70', 'marka_id' => 47],
    ['title' => 'QX80', 'marka_id' => 47],

    ['title' => 'Azsamand', 'marka_id' => 48],
    ['title' => 'Runna', 'marka_id' => 48],
    ['title' => 'Soren', 'marka_id' => 48],

    ['title' => 'Ecobus', 'marka_id' => 49],
    ['title' => 'MD 22 B', 'marka_id' => 49],
    ['title' => 'NHR 55 E', 'marka_id' => 49],
    ['title' => 'NKR 55 E', 'marka_id' => 49],
    ['title' => 'NKR 55 L', 'marka_id' => 49],
    ['title' => 'NP 37', 'marka_id' => 49],
    ['title' => 'NPR 66 L', 'marka_id' => 49],
    ['title' => 'NPR 71', 'marka_id' => 49],
    ['title' => 'NPR 75', 'marka_id' => 49],
    ['title' => 'Rodeo', 'marka_id' => 49],
    ['title' => 'Trooper', 'marka_id' => 49],
    ['title' => 'Turkuaz', 'marka_id' => 49],

    ['title' => '35C15', 'marka_id' => 50],
    ['title' => 'Daily 30-8', 'marka_id' => 50],
    ['title' => 'Daily 35C15VH', 'marka_id' => 50],
    ['title' => 'EuroStar', 'marka_id' => 50],
    ['title' => 'Otoyol', 'marka_id' => 50],
    ['title' => 'Stralis', 'marka_id' => 50],
    ['title' => 'Trakker', 'marka_id' => 50],

    ['title' => 'HFC1045KRD', 'marka_id' => 51],
    ['title' => 'HFC1061K5P', 'marka_id' => 51],
    ['title' => 'T8', 'marka_id' => 51],

    ['title' => 'E-Pace', 'marka_id' => 52],
    ['title' => 'F-Pace', 'marka_id' => 52],
    ['title' => 'F-Pace R', 'marka_id' => 52],
    ['title' => 'F-Type', 'marka_id' => 52],
    ['title' => 'F-Type R', 'marka_id' => 52],
    ['title' => 'XE', 'marka_id' => 52],
    ['title' => 'XF', 'marka_id' => 52],
    ['title' => 'XJ', 'marka_id' => 52],
    ['title' => 'XJ L', 'marka_id' => 52],

    ['title' => 'Cherokee', 'marka_id' => 53],
    ['title' => 'Commander', 'marka_id' => 53],
    ['title' => 'Compass', 'marka_id' => 53],
    ['title' => 'Grand Cherokee', 'marka_id' => 53],
    ['title' => 'Liberty', 'marka_id' => 53],
    ['title' => 'Patriot', 'marka_id' => 53],
    ['title' => 'Renegade', 'marka_id' => 53],
    ['title' => 'Wrangler', 'marka_id' => 53],

    ['title' => 'YY50QT-21B', 'marka_id' => 54],
    ['title' => 'YY50QT-6', 'marka_id' => 54],

    ['title' => '4308', 'marka_id' => 55],
    ['title' => '43101', 'marka_id' => 55],
    ['title' => '5320', 'marka_id' => 55],
    ['title' => '53202', 'marka_id' => 55],
    ['title' => '53212', 'marka_id' => 55],
    ['title' => '53213', 'marka_id' => 55],
    ['title' => '53215', 'marka_id' => 55],
    ['title' => '53229', 'marka_id' => 55],
    ['title' => '5410', 'marka_id' => 55],
    ['title' => '54112', 'marka_id' => 55],
    ['title' => '5511', 'marka_id' => 55],
    ['title' => '55111', 'marka_id' => 55],
    ['title' => '55115', 'marka_id' => 55],
    ['title' => '65115', 'marka_id' => 55],
    ['title' => '65117', 'marka_id' => 55],
    ['title' => '6520', 'marka_id' => 55],
    ['title' => '65201', 'marka_id' => 55],

    ['title' => '3270', 'marka_id' => 56],

    ['title' => 'Z1000', 'marka_id' => 57],
    ['title' => 'ZX-6R', 'marka_id' => 57],

    ['title' => 'LX', 'marka_id' => 58],
    ['title' => 'SD', 'marka_id' => 58],

    ['title' => 'Avella', 'marka_id' => 59],
    ['title' => 'Bongo', 'marka_id' => 59],
    ['title' => 'Cadenza', 'marka_id' => 59],
    ['title' => 'Carens', 'marka_id' => 59],
    ['title' => 'Carnival', 'marka_id' => 59],
    ['title' => 'Ceed', 'marka_id' => 59],
    ['title' => 'Cerato', 'marka_id' => 59],
    ['title' => 'Clarus', 'marka_id' => 59],
    ['title' => 'Credos', 'marka_id' => 59],
    ['title' => 'Joice', 'marka_id' => 59],
    ['title' => 'K2700', 'marka_id' => 59],
    ['title' => 'Koup', 'marka_id' => 59],
    ['title' => 'Magentis', 'marka_id' => 59],
    ['title' => 'Mohave', 'marka_id' => 59],
    ['title' => 'Opirus', 'marka_id' => 59],
    ['title' => 'Optima', 'marka_id' => 59],
    ['title' => 'Picanto', 'marka_id' => 59],
    ['title' => 'Pregio', 'marka_id' => 59],
    ['title' => 'Pride', 'marka_id' => 59],
    ['title' => 'Quoris', 'marka_id' => 59],
    ['title' => 'Rio', 'marka_id' => 59],
    ['title' => 'Rio X-Line', 'marka_id' => 59],
    ['title' => 'Sephia', 'marka_id' => 59],
    ['title' => 'Shuma', 'marka_id' => 59],
    ['title' => 'Sorento', 'marka_id' => 59],
    ['title' => 'Soul', 'marka_id' => 59],
    ['title' => 'Sportage', 'marka_id' => 59],
    ['title' => 'Stinger', 'marka_id' => 59],

    ['title' => 'XT150QT-8', 'marka_id' => 60],

    ['title' => '65053', 'marka_id' => 61],
    ['title' => '6511C4-082', 'marka_id' => 61],

    ['title' => '390 Duke', 'marka_id' => 62],

    ['title' => 'Dragon 50', 'marka_id' => 63],
    ['title' => 'Ege 50', 'marka_id' => 63],
    ['title' => 'Reiz 50', 'marka_id' => 63],

    ['title' => 'Vesta', 'marka_id' => 64],
    ['title' => 'Vesta Cross', 'marka_id' => 64],
    ['title' => 'Vesta SW', 'marka_id' => 64],
    ['title' => 'Vesta SW Cross', 'marka_id' => 64],
    ['title' => 'XRAY', 'marka_id' => 64],
    ['title' => 'XRAY Cross', 'marka_id' => 64],
    ['title' => '2101', 'marka_id' => 64],
    ['title' => '21011', 'marka_id' => 64],
    ['title' => '21013', 'marka_id' => 64],
    ['title' => '2102', 'marka_id' => 64],
    ['title' => '2103', 'marka_id' => 64],
    ['title' => '2104', 'marka_id' => 64],
    ['title' => '2105', 'marka_id' => 64],
    ['title' => '2106', 'marka_id' => 64],
    ['title' => '2107', 'marka_id' => 64],
    ['title' => '2108', 'marka_id' => 64],
    ['title' => '2109', 'marka_id' => 64],
    ['title' => '21099', 'marka_id' => 64],
    ['title' => '2110', 'marka_id' => 64],
    ['title' => '21103', 'marka_id' => 64],
    ['title' => '2111', 'marka_id' => 64],
    ['title' => '2112', 'marka_id' => 64],
    ['title' => '2113', 'marka_id' => 64],
    ['title' => '2114', 'marka_id' => 64],
    ['title' => '2115', 'marka_id' => 64],
    ['title' => 'Granta', 'marka_id' => 64],
    ['title' => 'Kalina', 'marka_id' => 64],
    ['title' => 'Largus', 'marka_id' => 64],
    ['title' => 'Niva', 'marka_id' => 64],
    ['title' => 'Oka', 'marka_id' => 64],
    ['title' => 'Priora', 'marka_id' => 64],

    ['title' => 'Aventador', 'marka_id' => 65],
    ['title' => 'Gallardo', 'marka_id' => 65],

    ['title' => 'Defender', 'marka_id' => 66],
    ['title' => 'Discovery', 'marka_id' => 66],
    ['title' => 'Discovery Sport', 'marka_id' => 66],
    ['title' => 'Freelander', 'marka_id' => 66],
    ['title' => 'Range Rover', 'marka_id' => 66],
    ['title' => 'RR Evoque', 'marka_id' => 66],
    ['title' => 'RR Sport', 'marka_id' => 66],
    ['title' => 'Velar', 'marka_id' => 66],

    ['title' => 'IS 200', 'marka_id' => 67],
    ['title' => 'IS 250', 'marka_id' => 67],
    ['title' => 'IS 300', 'marka_id' => 67],
    ['title' => 'GS 250', 'marka_id' => 67],
    ['title' => 'GS 300', 'marka_id' => 67],
    ['title' => 'GS 350', 'marka_id' => 67],
    ['title' => 'GS200T ', 'marka_id' => 67],
    ['title' => 'ES 250', 'marka_id' => 67],
    ['title' => 'ES 300', 'marka_id' => 67],
    ['title' => 'ES 350', 'marka_id' => 67],
    ['title' => 'LS 400', 'marka_id' => 67],
    ['title' => 'LS 460', 'marka_id' => 67],
    ['title' => 'LS 600 H', 'marka_id' => 67],
    ['title' => 'RX 200t', 'marka_id' => 67],
    ['title' => 'RX 300', 'marka_id' => 67],
    ['title' => 'RX 330', 'marka_id' => 67],
    ['title' => 'RX 350', 'marka_id' => 67],
    ['title' => 'RX 400 H', 'marka_id' => 67],
    ['title' => 'GX 460', 'marka_id' => 67],
    ['title' => 'GX 470', 'marka_id' => 67],
    ['title' => 'LX 450', 'marka_id' => 67],
    ['title' => 'LX 470', 'marka_id' => 67],
    ['title' => 'LX 570', 'marka_id' => 67],
    ['title' => 'CT 200 H', 'marka_id' => 67],
    ['title' => 'NX 200', 'marka_id' => 67],
    ['title' => 'NX 200T', 'marka_id' => 67],
    ['title' => 'NX 300H', 'marka_id' => 67],
    ['title' => 'NX300', 'marka_id' => 67],
    ['title' => 'LS 500', 'marka_id' => 67],

    ['title' => '320', 'marka_id' => 68],
    ['title' => '330', 'marka_id' => 68],
    ['title' => '520', 'marka_id' => 68],
    ['title' => '620', 'marka_id' => 68],
    ['title' => '720', 'marka_id' => 68],
    ['title' => '820', 'marka_id' => 68],
    ['title' => 'X60', 'marka_id' => 68],

    ['title' => 'MKX', 'marka_id' => 69],
    ['title' => 'Navigator', 'marka_id' => 69],
    ['title' => 'Towncar', 'marka_id' => 69],

    ['title' => '969M', 'marka_id' => 70],

    ['title' => '19372', 'marka_id' => 71],
    ['title' => '19463', 'marka_id' => 71],
    ['title' => '22.321', 'marka_id' => 71],
    ['title' => '26.403', 'marka_id' => 71],
    ['title' => 'F2000', 'marka_id' => 71],
    ['title' => 'TGA 18.440', 'marka_id' => 71],
    ['title' => 'TGA 33.480', 'marka_id' => 71],
    ['title' => 'TGA 410', 'marka_id' => 71],

    ['title' => 'Ghibli', 'marka_id' => 72],
    ['title' => 'GranTurismo', 'marka_id' => 72],
    ['title' => 'GranTurismo S', 'marka_id' => 72],
    ['title' => 'Quattroporte', 'marka_id' => 72],

    ['title' => '3577', 'marka_id' => 73],
    ['title' => '5337', 'marka_id' => 73],
    ['title' => '54323', 'marka_id' => 73],
    ['title' => '5549', 'marka_id' => 73],
    ['title' => '642208', 'marka_id' => 73],

    ['title' => '2', 'marka_id' => 74],
    ['title' => '3', 'marka_id' => 74],
    ['title' => '323', 'marka_id' => 74],
    ['title' => '6', 'marka_id' => 74],
    ['title' => '626', 'marka_id' => 74],
    ['title' => 'CX-5', 'marka_id' => 74],
    ['title' => 'CX-7', 'marka_id' => 74],
    ['title' => 'CX-9', 'marka_id' => 74],
    ['title' => 'MPV', 'marka_id' => 74],
    ['title' => 'MX-5 Miata', 'marka_id' => 74],
    ['title' => 'Premacy', 'marka_id' => 74],
    ['title' => 'RX 8', 'marka_id' => 74],
    ['title' => 'Tribute', 'marka_id' => 74],

    ['title' => 'MP4-12C', 'marka_id' => 75],

    ['title' => null, 'marka_id' => 76],

    ['title' => 'A 140', 'marka_id' => 77],
    ['title' => 'A 160', 'marka_id' => 77],
    ['title' => 'A 170', 'marka_id' => 77],
    ['title' => 'A 180', 'marka_id' => 77],
    ['title' => 'A 190', 'marka_id' => 77],
    ['title' => 'A 200', 'marka_id' => 77],
    ['title' => 'A 220', 'marka_id' => 77],
    ['title' => 'A 45 AMG', 'marka_id' => 77],
    ['title' => 'C 180', 'marka_id' => 77],
    ['title' => 'C 200', 'marka_id' => 77],
    ['title' => 'C 220', 'marka_id' => 77],
    ['title' => 'C 230', 'marka_id' => 77],
    ['title' => 'C 240', 'marka_id' => 77],
    ['title' => 'C 250', 'marka_id' => 77],
    ['title' => 'C 270', 'marka_id' => 77],
    ['title' => 'C 280', 'marka_id' => 77],
    ['title' => 'C 300', 'marka_id' => 77],
    ['title' => 'C 32 AMG', 'marka_id' => 77],
    ['title' => 'C 320', 'marka_id' => 77],
    ['title' => 'C 350', 'marka_id' => 77],
    ['title' => 'C 43 AMG', 'marka_id' => 77],
    ['title' => 'C 55 AMG', 'marka_id' => 77],
    ['title' => '200 D', 'marka_id' => 77],
    ['title' => '230 CE', 'marka_id' => 77],
    ['title' => 'E 180', 'marka_id' => 77],
    ['title' => 'E 200', 'marka_id' => 77],
    ['title' => 'E 220', 'marka_id' => 77],
    ['title' => 'E 230', 'marka_id' => 77],
    ['title' => 'E 240', 'marka_id' => 77],
    ['title' => 'E 250', 'marka_id' => 77],
    ['title' => 'E 260', 'marka_id' => 77],
    ['title' => 'E 270', 'marka_id' => 77],
    ['title' => 'E 280', 'marka_id' => 77],
    ['title' => 'E 290', 'marka_id' => 77],
    ['title' => 'E 300', 'marka_id' => 77],
    ['title' => 'E 320', 'marka_id' => 77],
    ['title' => 'E 350', 'marka_id' => 77],
    ['title' => 'E 400', 'marka_id' => 77],
    ['title' => 'E 43 AMG', 'marka_id' => 77],
    ['title' => 'E 430', 'marka_id' => 77],
    ['title' => 'E 63 AMG', 'marka_id' => 77],
    ['title' => 'G 230', 'marka_id' => 77],
    ['title' => 'G 270', 'marka_id' => 77],
    ['title' => 'G 300', 'marka_id' => 77],
    ['title' => 'G 320', 'marka_id' => 77],
    ['title' => 'G 350', 'marka_id' => 77],
    ['title' => 'G 400', 'marka_id' => 77],
    ['title' => 'G 500', 'marka_id' => 77],
    ['title' => 'G 55 AMG', 'marka_id' => 77],
    ['title' => 'G 63 AMG', 'marka_id' => 77],
    ['title' => 'G 65 AMG', 'marka_id' => 77],
    ['title' => 'B 170', 'marka_id' => 77],
    ['title' => 'B 180', 'marka_id' => 77],
    ['title' => 'B 200', 'marka_id' => 77],
    ['title' => 'CL 55 AMG', 'marka_id' => 77],
    ['title' => 'CL 550', 'marka_id' => 77],
    ['title' => 'CLS 250 CDI', 'marka_id' => 77],
    ['title' => 'CLS 350', 'marka_id' => 77],
    ['title' => 'CLS 450 Coupe', 'marka_id' => 77],
    ['title' => 'CLS 500', 'marka_id' => 77],
    ['title' => 'CLS 63 AMG', 'marka_id' => 77],
    ['title' => 'GL 320', 'marka_id' => 77],
    ['title' => 'GL 350', 'marka_id' => 77],
    ['title' => 'GL 400', 'marka_id' => 77],
    ['title' => 'GL 450', 'marka_id' => 77],
    ['title' => 'GL 500', 'marka_id' => 77],
    ['title' => 'GL 550', 'marka_id' => 77],
    ['title' => 'GL 63 AMG', 'marka_id' => 77],
    ['title' => 'GL Brabus Widestar', 'marka_id' => 77],
    ['title' => 'GLK 220', 'marka_id' => 77],
    ['title' => 'GLK 250', 'marka_id' => 77],
    ['title' => 'ML 250', 'marka_id' => 77],
    ['title' => 'ML 270', 'marka_id' => 77],
    ['title' => 'ML 280', 'marka_id' => 77],
    ['title' => 'ML 300', 'marka_id' => 77],
    ['title' => 'ML 320', 'marka_id' => 77],
    ['title' => 'ML 350', 'marka_id' => 77],
    ['title' => 'ML 400', 'marka_id' => 77],
    ['title' => 'ML 63 AMG', 'marka_id' => 77],
    ['title' => 'R 350', 'marka_id' => 77],
    ['title' => '280 SE', 'marka_id' => 77],
    ['title' => '280 SEL', 'marka_id' => 77],
    ['title' => '300 SEL', 'marka_id' => 77],
    ['title' => '400 SEL', 'marka_id' => 77],
    ['title' => '500 SEL', 'marka_id' => 77],
    ['title' => 'S 280', 'marka_id' => 77],
    ['title' => 'S 300', 'marka_id' => 77],
    ['title' => 'S 320', 'marka_id' => 77],
    ['title' => 'S 350', 'marka_id' => 77],
    ['title' => 'S 400', 'marka_id' => 77],
    ['title' => 'S 420', 'marka_id' => 77],
    ['title' => 'S 430', 'marka_id' => 77],
    ['title' => 'S 450', 'marka_id' => 77],
    ['title' => 'S 500', 'marka_id' => 77],
    ['title' => 'S 500 Coupe', 'marka_id' => 77],
    ['title' => 'S 55 AMG', 'marka_id' => 77],
    ['title' => 'S 550', 'marka_id' => 77],
    ['title' => 'S 560', 'marka_id' => 77],
    ['title' => 'S 600', 'marka_id' => 77],
    ['title' => 'S 63 AMG', 'marka_id' => 77],
    ['title' => 'S 63 AMG Coupe', 'marka_id' => 77],
    ['title' => 'S 65 AMG', 'marka_id' => 77],
    ['title' => 'S 65 AMG Coupe', 'marka_id' => 77],
    ['title' => 'SLK 200', 'marka_id' => 77],
    ['title' => 'SLK 230', 'marka_id' => 77],
    ['title' => 'SLK 250', 'marka_id' => 77],
    ['title' => 'SLS AMG', 'marka_id' => 77],
    ['title' => 'V 220', 'marka_id' => 77],
    ['title' => 'V 250', 'marka_id' => 77],
    ['title' => 'Viano', 'marka_id' => 77],
    ['title' => 'CLK 200', 'marka_id' => 77],
    ['title' => 'CLK 230', 'marka_id' => 77],
    ['title' => 'CLK 320', 'marka_id' => 77],
    ['title' => 'CLA 180', 'marka_id' => 77],
    ['title' => 'CLA 200', 'marka_id' => 77],
    ['title' => 'CLA 220', 'marka_id' => 77],
    ['title' => 'CLA 250', 'marka_id' => 77],
    ['title' => 'CLA 45 AMG', 'marka_id' => 77],
    ['title' => '1217', 'marka_id' => 77],
    ['title' => '207 D', 'marka_id' => 77],
    ['title' => '208 D', 'marka_id' => 77],
    ['title' => '210 D', 'marka_id' => 77],
    ['title' => '308 D', 'marka_id' => 77],
    ['title' => '403', 'marka_id' => 77],
    ['title' => '409 D', 'marka_id' => 77],
    ['title' => '410 D', 'marka_id' => 77],
    ['title' => '412 D', 'marka_id' => 77],
    ['title' => '508', 'marka_id' => 77],
    ['title' => '609 D', 'marka_id' => 77],
    ['title' => '612 D', 'marka_id' => 77],
    ['title' => '709 D', 'marka_id' => 77],
    ['title' => '809 D', 'marka_id' => 77],
    ['title' => '814 D', 'marka_id' => 77],
    ['title' => 'Actros 1840', 'marka_id' => 77],
    ['title' => 'Actros 1843', 'marka_id' => 77],
    ['title' => 'Actros 1844', 'marka_id' => 77],
    ['title' => 'Actros 2536', 'marka_id' => 77],
    ['title' => 'Actros 2544', 'marka_id' => 77],
    ['title' => 'Actros 2640', 'marka_id' => 77],
    ['title' => 'Actros 4140', 'marka_id' => 77],
    ['title' => 'Atego 1018', 'marka_id' => 77],
    ['title' => 'Atego 1217', 'marka_id' => 77],
    ['title' => 'Atego 1218', 'marka_id' => 77],
    ['title' => 'Atego 1222', 'marka_id' => 77],
    ['title' => 'Atego 1223', 'marka_id' => 77],
    ['title' => 'Atego 1228', 'marka_id' => 77],
    ['title' => 'Atego 1229', 'marka_id' => 77],
    ['title' => 'Atego 1517', 'marka_id' => 77],
    ['title' => 'Atego 1524', 'marka_id' => 77],
    ['title' => 'Atego 1528', 'marka_id' => 77],
    ['title' => 'Atego 1828', 'marka_id' => 77],
    ['title' => 'Atego 2528', 'marka_id' => 77],
    ['title' => 'Atego 813', 'marka_id' => 77],
    ['title' => 'Atego 814', 'marka_id' => 77],
    ['title' => 'Atego 815', 'marka_id' => 77],
    ['title' => 'Atego 816', 'marka_id' => 77],
    ['title' => 'Atego 817', 'marka_id' => 77],
    ['title' => 'Atego 818', 'marka_id' => 77],
    ['title' => 'Axor 1829', 'marka_id' => 77],
    ['title' => 'Axor 1840', 'marka_id' => 77],
    ['title' => 'Axor 1843', 'marka_id' => 77],
    ['title' => 'Axor 2533', 'marka_id' => 77],
    ['title' => 'Axor 2533', 'marka_id' => 77],
    ['title' => 'Axor 3028', 'marka_id' => 77],
    ['title' => 'MB140D', 'marka_id' => 77],
    ['title' => 'Travego', 'marka_id' => 77],
    ['title' => 'Vario', 'marka_id' => 77],
    ['title' => 'Sprinter 208', 'marka_id' => 77],
    ['title' => 'Sprinter 209', 'marka_id' => 77],
    ['title' => 'Sprinter 211', 'marka_id' => 77],
    ['title' => 'Sprinter 212', 'marka_id' => 77],
    ['title' => 'Sprinter 213', 'marka_id' => 77],
    ['title' => 'Sprinter 308', 'marka_id' => 77],
    ['title' => 'Sprinter 309', 'marka_id' => 77],
    ['title' => 'Sprinter 310', 'marka_id' => 77],
    ['title' => 'Sprinter 311', 'marka_id' => 77],
    ['title' => 'Sprinter 312', 'marka_id' => 77],
    ['title' => 'Sprinter 313', 'marka_id' => 77],
    ['title' => 'Sprinter 315', 'marka_id' => 77],
    ['title' => 'Sprinter 316', 'marka_id' => 77],
    ['title' => 'Sprinter 318', 'marka_id' => 77],
    ['title' => 'Sprinter 319', 'marka_id' => 77],
    ['title' => 'Sprinter 411', 'marka_id' => 77],
    ['title' => 'Sprinter 412', 'marka_id' => 77],
    ['title' => 'Sprinter 413', 'marka_id' => 77],
    ['title' => 'Sprinter 416', 'marka_id' => 77],
    ['title' => 'Sprinter 513', 'marka_id' => 77],
    ['title' => 'Sprinter 515', 'marka_id' => 77],
    ['title' => 'Sprinter 516', 'marka_id' => 77],
    ['title' => 'Sprinter 519', 'marka_id' => 77],
    ['title' => 'GLA 200', 'marka_id' => 77],
    ['title' => 'GLA 220', 'marka_id' => 77],
    ['title' => 'GLA 250', 'marka_id' => 77],
    ['title' => 'GLE 300', 'marka_id' => 77],
    ['title' => 'GLE 350', 'marka_id' => 77],
    ['title' => 'GLE 43 AMG', 'marka_id' => 77],
    ['title' => 'GLE 43 AMG Coupe ', 'marka_id' => 77],
    ['title' => 'GLE 450', 'marka_id' => 77],
    ['title' => 'GLE 450 AMG Coupe', 'marka_id' => 77],
    ['title' => 'GLE 53 AMG Coupe', 'marka_id' => 77],
    ['title' => 'GLE 63 AMG S', 'marka_id' => 77],
    ['title' => 'GLC 200 4Matic', 'marka_id' => 77],
    ['title' => 'GLC 200 4Matic Coupe', 'marka_id' => 77],
    ['title' => 'GLC 250', 'marka_id' => 77],
    ['title' => 'GLC 300', 'marka_id' => 77],
    ['title' => 'GLS 350', 'marka_id' => 77],
    ['title' => 'GLS 400', 'marka_id' => 77],
    ['title' => 'GLS 450', 'marka_id' => 77],
    ['title' => 'GLS 500', 'marka_id' => 77],
    ['title' => 'GLS 580', 'marka_id' => 77],
    ['title' => 'GLS 63 AMG', 'marka_id' => 77],
    ['title' => 'Vito', 'marka_id' => 77],
    ['title' => 'Vito 108', 'marka_id' => 77],
    ['title' => 'Vito 109', 'marka_id' => 77],
    ['title' => 'Vito 110', 'marka_id' => 77],
    ['title' => 'Vito 111', 'marka_id' => 77],
    ['title' => 'Vito 112', 'marka_id' => 77],
    ['title' => 'Vito 113', 'marka_id' => 77],
    ['title' => 'Vito 114', 'marka_id' => 77],
    ['title' => 'Vito 115', 'marka_id' => 77],
    ['title' => 'Vito 116', 'marka_id' => 77],
    ['title' => 'Vito 119', 'marka_id' => 77],
    ['title' => 'Vito 122', 'marka_id' => 77],
    ['title' => 'X 250D', 'marka_id' => 77],
    ['title' => 'AMG GT', 'marka_id' => 77],
    ['title' => 'AMG GT 43', 'marka_id' => 77],
    ['title' => 'AMG GT S', 'marka_id' => 77],
    ['title' => '100', 'marka_id' => 77],
    ['title' => '190', 'marka_id' => 77],
    ['title' => '200', 'marka_id' => 77],
    ['title' => '300', 'marka_id' => 77],
    ['title' => 'Citan', 'marka_id' => 77],
    ['title' => 'Gazelle', 'marka_id' => 77],
    ['title' => 'Vaneo', 'marka_id' => 77],

    ['title' => 'S 400', 'marka_id' => 78],
    ['title' => 'S 500', 'marka_id' => 78],
    ['title' => 'S 560', 'marka_id' => 78],
    ['title' => 'S 600', 'marka_id' => 78],

    ['title' => '3', 'marka_id' => 79],
    ['title' => '350', 'marka_id' => 79],
    ['title' => '5', 'marka_id' => 79],
    ['title' => '550', 'marka_id' => 79],
    ['title' => '6', 'marka_id' => 79],

    ['title' => 'Clubman', 'marka_id' => 80],
    ['title' => 'Cooper', 'marka_id' => 80],
    ['title' => 'Countryman', 'marka_id' => 80],

    ['title' => '3.112.12', 'marka_id' => 81],

    ['title' => 'Airtrek', 'marka_id' => 82],
    ['title' => 'ASX', 'marka_id' => 82],
    ['title' => 'Attrage', 'marka_id' => 82],
    ['title' => 'Chariot', 'marka_id' => 82],
    ['title' => 'Colt', 'marka_id' => 82],
    ['title' => 'Eclipse Cross', 'marka_id' => 82],
    ['title' => 'Galant', 'marka_id' => 82],
    ['title' => 'Grandis', 'marka_id' => 82],
    ['title' => 'L 200', 'marka_id' => 82],
    ['title' => 'L 300', 'marka_id' => 82],
    ['title' => 'Lancer', 'marka_id' => 82],
    ['title' => 'Mirage', 'marka_id' => 82],
    ['title' => 'Outlander', 'marka_id' => 82],
    ['title' => 'Outlander Sport', 'marka_id' => 82],
    ['title' => 'Pajero', 'marka_id' => 82],
    ['title' => 'Pajero io', 'marka_id' => 82],
    ['title' => 'Pajero Pinin', 'marka_id' => 82],
    ['title' => 'Pajero Sport', 'marka_id' => 82],
    ['title' => 'Rosa', 'marka_id' => 82],
    ['title' => 'Space Runner', 'marka_id' => 82],
    ['title' => 'Space Wagon', 'marka_id' => 82],

    ['title' => '100 SFC Snappy X', 'marka_id' => 83],
    ['title' => '125 NT TURKUAZ', 'marka_id' => 83],
    ['title' => '125 ZNU', 'marka_id' => 83],
    ['title' => '150 MASH', 'marka_id' => 83],
    ['title' => '50 Revival', 'marka_id' => 83],
    ['title' => 'Ritmica 110', 'marka_id' => 83],
    ['title' => 'X-Treme MAXX - 200', 'marka_id' => 83],

    ['title' => '2140', 'marka_id' => 84],
    ['title' => '2141', 'marka_id' => 84],
    ['title' => '2715', 'marka_id' => 84],
    ['title' => '400', 'marka_id' => 84],
    ['title' => '403', 'marka_id' => 84],
    ['title' => '408', 'marka_id' => 84],
    ['title' => '412', 'marka_id' => 84],

    ['title' => 'Muravey- 2 01', 'marka_id' => 85],
    ['title' => 'TG200', 'marka_id' => 85],
    ['title' => 'TGA200-01P', 'marka_id' => 85],

    ['title' => '48-2', 'marka_id' => 86],

    ['title' => 'Cityliner', 'marka_id' => 87],

    ['title' => 'NP150ZH-E', 'marka_id' => 88],

    ['title' => '350Z', 'marka_id' => 89],
    ['title' => 'Almera', 'marka_id' => 89],
    ['title' => 'Altima', 'marka_id' => 89],
    ['title' => 'Armada', 'marka_id' => 89],
    ['title' => 'Bluebird', 'marka_id' => 89],
    ['title' => 'Juke', 'marka_id' => 89],
    ['title' => 'Kicks', 'marka_id' => 89],
    ['title' => 'Leaf', 'marka_id' => 89],
    ['title' => 'March', 'marka_id' => 89],
    ['title' => 'Maxima', 'marka_id' => 89],
    ['title' => 'Micra', 'marka_id' => 89],
    ['title' => 'Murano', 'marka_id' => 89],
    ['title' => 'Navara', 'marka_id' => 89],
    ['title' => 'Note', 'marka_id' => 89],
    ['title' => 'Pathfinder', 'marka_id' => 89],
    ['title' => 'Patrol', 'marka_id' => 89],
    ['title' => 'Presage', 'marka_id' => 89],
    ['title' => 'Primera', 'marka_id' => 89],
    ['title' => 'Qashqai', 'marka_id' => 89],
    ['title' => 'Rogue', 'marka_id' => 89],
    ['title' => 'Sentra', 'marka_id' => 89],
    ['title' => 'Serena', 'marka_id' => 89],
    ['title' => 'Sunny', 'marka_id' => 89],
    ['title' => 'Teana', 'marka_id' => 89],
    ['title' => 'Terrano', 'marka_id' => 89],
    ['title' => 'Tiida', 'marka_id' => 89],
    ['title' => 'Urvan', 'marka_id' => 89],
    ['title' => 'Vanette', 'marka_id' => 89],
    ['title' => 'Versa', 'marka_id' => 89],
    ['title' => 'X-Trail', 'marka_id' => 89],
    ['title' => 'Xterra', 'marka_id' => 89],

    ['title' => 'Agila', 'marka_id' => 90],
    ['title' => 'Antara', 'marka_id' => 90],
    ['title' => 'Astra', 'marka_id' => 90],
    ['title' => 'Combo', 'marka_id' => 90],
    ['title' => 'Corsa', 'marka_id' => 90],
    ['title' => 'Frontera', 'marka_id' => 90],
    ['title' => 'Insignia', 'marka_id' => 90],
    ['title' => 'Kadett', 'marka_id' => 90],
    ['title' => 'Meriva', 'marka_id' => 90],
    ['title' => 'Omega', 'marka_id' => 90],
    ['title' => 'Signum', 'marka_id' => 90],
    ['title' => 'Sintra', 'marka_id' => 90],
    ['title' => 'Tigra', 'marka_id' => 90],
    ['title' => 'Vectra', 'marka_id' => 90],
    ['title' => 'Vita', 'marka_id' => 90],
    ['title' => 'Vivaro', 'marka_id' => 90],
    ['title' => 'Zafira', 'marka_id' => 90],

    ['title' => 'Doruk 220 T', 'marka_id' => 91],

    ['title' => '32054', 'marka_id' => 92],

    ['title' => '206', 'marka_id' => 93],
    ['title' => '207', 'marka_id' => 93],
    ['title' => '301', 'marka_id' => 93],
    ['title' => '306', 'marka_id' => 93],
    ['title' => '307', 'marka_id' => 93],
    ['title' => '307 CC', 'marka_id' => 93],
    ['title' => '308', 'marka_id' => 93],
    ['title' => '308 CC', 'marka_id' => 93],
    ['title' => '405', 'marka_id' => 93],
    ['title' => '406', 'marka_id' => 93],
    ['title' => '407', 'marka_id' => 93],
    ['title' => '607', 'marka_id' => 93],
    ['title' => 'J9', 'marka_id' => 93],
    ['title' => 'Khazar 406', 'marka_id' => 93],
    ['title' => 'Pars', 'marka_id' => 93],
    ['title' => 'Partner', 'marka_id' => 93],
    ['title' => 'RCZ', 'marka_id' => 93],

    ['title' => 'X10', 'marka_id' => 94],

    ['title' => 'Solstice', 'marka_id' => 95],

    ['title' => '718 Boxter', 'marka_id' => 96],
    ['title' => '718 Boxter S', 'marka_id' => 96],
    ['title' => '911 Carrera', 'marka_id' => 96],
    ['title' => '911 Carrera 4S', 'marka_id' => 96],
    ['title' => '911 Turbo', 'marka_id' => 96],
    ['title' => 'Panamera', 'marka_id' => 96],
    ['title' => 'Panamera 4', 'marka_id' => 96],
    ['title' => 'Panamera 4S', 'marka_id' => 96],
    ['title' => 'Panamera GTS', 'marka_id' => 96],
    ['title' => 'Panamera S', 'marka_id' => 96],
    ['title' => 'Panamera Turbo', 'marka_id' => 96],
    ['title' => 'Panamera Turbo Executive', 'marka_id' => 96],
    ['title' => 'Panamera Turbo S', 'marka_id' => 96],
    ['title' => 'Macan', 'marka_id' => 96],
    ['title' => 'Macan S', 'marka_id' => 96],
    ['title' => 'Macan Turbo', 'marka_id' => 96],
    ['title' => 'Cayenne', 'marka_id' => 96],
    ['title' => 'Cayenne Coupe', 'marka_id' => 96],
    ['title' => 'Cayenne E-Hybrid', 'marka_id' => 96],
    ['title' => 'Cayenne GTS', 'marka_id' => 96],
    ['title' => 'Cayenne S', 'marka_id' => 96],
    ['title' => 'Cayenne Turbo', 'marka_id' => 96],
    ['title' => 'Cayenne Turbo Coupe', 'marka_id' => 96],
    ['title' => 'Cayenne Turbo S', 'marka_id' => 96],
    ['title' => 'Cayenne Turbo S E-Hybrid', 'marka_id' => 96],
    ['title' => 'Boxster', 'marka_id' => 96],

    ['title' => 'Gentra', 'marka_id' => 97],
    ['title' => 'Nexia R3', 'marka_id' => 97],
    ['title' => 'R2', 'marka_id' => 97],
    ['title' => 'R4', 'marka_id' => 97],

    ['title' => '11', 'marka_id' => 98],
    ['title' => '12 Toros', 'marka_id' => 98],
    ['title' => '19', 'marka_id' => 98],
    ['title' => '21', 'marka_id' => 98],
    ['title' => 'Arkana', 'marka_id' => 98],
    ['title' => 'Clio', 'marka_id' => 98],
    ['title' => 'Dokker', 'marka_id' => 98],
    ['title' => 'Duster', 'marka_id' => 98],
    ['title' => 'Espace', 'marka_id' => 98],
    ['title' => 'Fluence', 'marka_id' => 98],
    ['title' => 'Grand Scenic', 'marka_id' => 98],
    ['title' => 'Kangoo', 'marka_id' => 98],
    ['title' => 'Koleos', 'marka_id' => 98],
    ['title' => 'Laguna', 'marka_id' => 98],
    ['title' => 'Logan', 'marka_id' => 98],
    ['title' => 'Magnum', 'marka_id' => 98],
    ['title' => 'Master', 'marka_id' => 98],
    ['title' => 'Megane', 'marka_id' => 98],
    ['title' => 'Megane Scenic', 'marka_id' => 98],
    ['title' => 'Modus', 'marka_id' => 98],
    ['title' => 'Premium 420', 'marka_id' => 98],
    ['title' => 'Sandero', 'marka_id' => 98],
    ['title' => 'Scenic', 'marka_id' => 98],
    ['title' => 'Symbol', 'marka_id' => 98],
    ['title' => 'Tondar', 'marka_id' => 98],
    ['title' => 'Trafic', 'marka_id' => 98],

    ['title' => 'Cullinan', 'marka_id' => 99],
    ['title' => 'Phantom', 'marka_id' => 99],
    ['title' => 'Wraith', 'marka_id' => 99],

    ['title' => '200', 'marka_id' => 100],
    ['title' => '75', 'marka_id' => 100],

    ['title' => '9-3', 'marka_id' => 101],
    ['title' => '9-5', 'marka_id' => 101],

    ['title' => '132', 'marka_id' => 102],
    ['title' => '141', 'marka_id' => 102],
    ['title' => 'Saina', 'marka_id' => 102],
    ['title' => 'Tiba', 'marka_id' => 102],

    ['title' => 'G 420', 'marka_id' => 103],

    ['title' => 'Cordoba', 'marka_id' => 104],
    ['title' => 'Exeo', 'marka_id' => 104],
    ['title' => 'Ibiza', 'marka_id' => 104],
    ['title' => 'Leon', 'marka_id' => 104],
    ['title' => 'Toledo', 'marka_id' => 104],

    ['title' => 'F2000', 'marka_id' => 105],
    ['title' => 'F3000', 'marka_id' => 105],

    ['title' => 'SLG 6602', 'marka_id' => 106],

    ['title' => 'Fabia', 'marka_id' => 107],
    ['title' => 'Felicia', 'marka_id' => 107],
    ['title' => 'Kamiq', 'marka_id' => 107],
    ['title' => 'Karoq', 'marka_id' => 107],
    ['title' => 'Kodiaq', 'marka_id' => 107],
    ['title' => 'Octavia', 'marka_id' => 107],
    ['title' => 'Rapid', 'marka_id' => 107],
    ['title' => 'Scala', 'marka_id' => 107],
    ['title' => 'Superb', 'marka_id' => 107],
    ['title' => 'Yeti', 'marka_id' => 107],

    ['title' => 'Forfour', 'marka_id' => 108],
    ['title' => 'Fortwo', 'marka_id' => 108],

    ['title' => 'Actyon', 'marka_id' => 109],
    ['title' => 'Actyon Sports', 'marka_id' => 109],
    ['title' => 'Korando', 'marka_id' => 109],
    ['title' => 'Kyron', 'marka_id' => 109],
    ['title' => 'Rexton', 'marka_id' => 109],

    ['title' => 'B9 Tribeca', 'marka_id' => 110],
    ['title' => 'Forester', 'marka_id' => 110],
    ['title' => 'Impreza', 'marka_id' => 110],
    ['title' => 'Legacy', 'marka_id' => 110],
    ['title' => 'Outback', 'marka_id' => 110],
    ['title' => 'Tribeca', 'marka_id' => 110],
    ['title' => '5XV', 'marka_id' => 110],

    ['title' => 'AN 200', 'marka_id' => 111],
    ['title' => 'Boulevard', 'marka_id' => 111],
    ['title' => 'GSR 750', 'marka_id' => 111],
    ['title' => 'Intruder M1800R', 'marka_id' => 111],
    ['title' => 'Kingquad 500', 'marka_id' => 111],
    ['title' => 'V-Strom 650', 'marka_id' => 111],
    ['title' => 'Aerio', 'marka_id' => 111],
    ['title' => 'Grand Vitara', 'marka_id' => 111],
    ['title' => 'GW 250', 'marka_id' => 111],
    ['title' => 'Jimny', 'marka_id' => 111],
    ['title' => 'Kizashi', 'marka_id' => 111],
    ['title' => 'Splash', 'marka_id' => 111],
    ['title' => 'Swift', 'marka_id' => 111],
    ['title' => 'SX4', 'marka_id' => 111],

    ['title' => 'Indica', 'marka_id' => 112],

    ['title' => 'Model S', 'marka_id' => 113],

    ['title' => 'Dogan', 'marka_id' => 114],
    ['title' => 'Kartal', 'marka_id' => 114],
    ['title' => 'Sahin', 'marka_id' => 114],

    ['title' => 'Auris', 'marka_id' => 115],
    ['title' => 'Avalon', 'marka_id' => 115],
    ['title' => 'Avensis', 'marka_id' => 115],
    ['title' => 'C-HR', 'marka_id' => 115],
    ['title' => 'Camry', 'marka_id' => 115],
    ['title' => 'Carina', 'marka_id' => 115],
    ['title' => 'Corolla', 'marka_id' => 115],
    ['title' => 'Corolla Verso', 'marka_id' => 115],
    ['title' => 'FJ Cruiser', 'marka_id' => 115],
    ['title' => 'Fortuner', 'marka_id' => 115],
    ['title' => 'GT 86', 'marka_id' => 115],
    ['title' => 'Harrier', 'marka_id' => 115],
    ['title' => 'HiAce', 'marka_id' => 115],
    ['title' => 'Highlander', 'marka_id' => 115],
    ['title' => 'Hilux', 'marka_id' => 115],
    ['title' => 'IQ', 'marka_id' => 115],
    ['title' => 'Land Cruiser', 'marka_id' => 115],
    ['title' => 'Prado', 'marka_id' => 115],
    ['title' => 'Previa', 'marka_id' => 115],
    ['title' => 'Prius', 'marka_id' => 115],
    ['title' => 'Prius C', 'marka_id' => 115],
    ['title' => 'Prius V', 'marka_id' => 115],
    ['title' => 'RAV 4', 'marka_id' => 115],
    ['title' => 'Sequoia', 'marka_id' => 115],
    ['title' => 'Sienna', 'marka_id' => 115],
    ['title' => 'Solara', 'marka_id' => 115],
    ['title' => 'Supra', 'marka_id' => 115],
    ['title' => 'Surf', 'marka_id' => 115],
    ['title' => 'Tacoma', 'marka_id' => 115],
    ['title' => 'Venza', 'marka_id' => 115],
    ['title' => 'Vitz', 'marka_id' => 115],
    ['title' => 'Yaris', 'marka_id' => 115],

    ['title' => '31512', 'marka_id' => 116],
    ['title' => '31514', 'marka_id' => 116],
    ['title' => '31519', 'marka_id' => 116],
    ['title' => '3162', 'marka_id' => 116],
    ['title' => '3303', 'marka_id' => 116],
    ['title' => '39625', 'marka_id' => 116],
    ['title' => '452', 'marka_id' => 116],
    ['title' => '462', 'marka_id' => 116],
    ['title' => '469', 'marka_id' => 116],
    ['title' => 'Hunter', 'marka_id' => 116],
    ['title' => 'Patriot', 'marka_id' => 116],
    ['title' => 'Pickup', 'marka_id' => 116],
    ['title' => 'Profi', 'marka_id' => 116],

    ['title' => '4320', 'marka_id' => 117],
    ['title' => 'DNEPR MT', 'marka_id' => 117],

    ['title' => 'Primavera 50', 'marka_id' => 118],

    ['title' => 'Amarok', 'marka_id' => 119],
    ['title' => 'Arteon', 'marka_id' => 119],
    ['title' => 'Beetle', 'marka_id' => 119],
    ['title' => 'Bora', 'marka_id' => 119],
    ['title' => 'Caddy', 'marka_id' => 119],
    ['title' => 'Caravelle', 'marka_id' => 119],
    ['title' => 'Crafter', 'marka_id' => 119],
    ['title' => 'Fox', 'marka_id' => 119],
    ['title' => 'Golf', 'marka_id' => 119],
    ['title' => 'Golf GTI', 'marka_id' => 119],
    ['title' => 'Golf Plus', 'marka_id' => 119],
    ['title' => 'Jetta', 'marka_id' => 119],
    ['title' => 'Multivan', 'marka_id' => 119],
    ['title' => 'Passat', 'marka_id' => 119],
    ['title' => 'Passat CC', 'marka_id' => 119],
    ['title' => 'Phaeton', 'marka_id' => 119],
    ['title' => 'Polo', 'marka_id' => 119],
    ['title' => 'Scirocco', 'marka_id' => 119],
    ['title' => 'Sharan', 'marka_id' => 119],
    ['title' => 'Tiguan', 'marka_id' => 119],
    ['title' => 'Touareg', 'marka_id' => 119],
    ['title' => 'Touran', 'marka_id' => 119],
    ['title' => 'Transporter', 'marka_id' => 119],
    ['title' => 'Vento', 'marka_id' => 119],

    ['title' => '240', 'marka_id' => 120],
    ['title' => '850', 'marka_id' => 120],
    ['title' => '940', 'marka_id' => 120],
    ['title' => 'C 70', 'marka_id' => 120],
    ['title' => 'FH 13', 'marka_id' => 120],
    ['title' => 'S 40', 'marka_id' => 120],
    ['title' => 'S 60', 'marka_id' => 120],
    ['title' => 'S 70', 'marka_id' => 120],
    ['title' => 'S 80', 'marka_id' => 120],
    ['title' => 'S 90', 'marka_id' => 120],
    ['title' => 'V 90', 'marka_id' => 120],
    ['title' => 'XC 40', 'marka_id' => 120],
    ['title' => 'XC 60', 'marka_id' => 120],
    ['title' => 'XC 70', 'marka_id' => 120],
    ['title' => 'XC 90', 'marka_id' => 120],

    ['title' => '2', 'marka_id' => 121],

    ['title' => 'Grizzly 660', 'marka_id' => 122],
    ['title' => 'R15', 'marka_id' => 122],
    ['title' => 'Ray Z 115', 'marka_id' => 122],
    ['title' => 'RAY-ZR', 'marka_id' => 122],
    ['title' => 'Vino', 'marka_id' => 122],

    ['title' => '965', 'marka_id' => 123],
    ['title' => '968M', 'marka_id' => 123],
    ['title' => 'Slavuta', 'marka_id' => 123],
    ['title' => 'Tavriya', 'marka_id' => 123],
    ['title' => 'Vida', 'marka_id' => 123],

    ['title' => '130', 'marka_id' => 124],
    ['title' => '131', 'marka_id' => 124],
    ['title' => '133', 'marka_id' => 124],
    ['title' => '157', 'marka_id' => 124],
    ['title' => '4334', 'marka_id' => 124],
    ['title' => '5301', 'marka_id' => 124],
    ['title' => 'MMZ 45023', 'marka_id' => 124],

    ['title' => 'Spex', 'marka_id' => 125],

    ['title' => 'Panther ZT150-8A', 'marka_id' => 126],
    ['title' => 'R310', 'marka_id' => 126],
    ['title' => 'Tiger ZT150-3A', 'marka_id' => 126],

];


