<?php











//HTC den basla





$electron_books_model = [
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Black Pearl'],/*id 1 AirOn*/
    ['sub_category_type_one_id' => 109,'name' => 'AirBook City'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook City Base'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook City LED'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook City Light HD'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Liber Plus'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Pro 6'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Pro 6S'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Pro 8'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Pro 8s'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook Liber'],
    ['sub_category_type_one_id' => 109,'name' => 'AirBook City Light Touch'],

    ['sub_category_type_one_id' => 110,'name' => 'Kindle 8 2018'],/*id 13 Amazon*/
    ['sub_category_type_one_id' => 110,'name' => 'Kindle DX'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Keyboard'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Voyage 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 2021'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 7 2015 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Kindle Paperwhite New'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 2014'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 5 2012'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 7 2014'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Keyboard 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis (9th gen)'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 2016'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 10 2018'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 5'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 7 2015'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 2015'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 10 2019'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 2 2009'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 2007'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle 4 2011'],
    ['sub_category_type_one_id' => 110,'name' => 'Kids Edition'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Kids Edition'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis 10 2019'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis 8 2016'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis 8 2016 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Oasis 9 2017'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 10 2018 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 10 2018 LTE'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Touch'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Touch 3G'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Voyage'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 2021 Signature'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 5 2012'],
    ['sub_category_type_one_id' => 110,'name' => 'Kindle Paperwhite 6 2013'],

    ['sub_category_type_one_id' => 111,'name' => 'Nook'],/*50*/
    ['sub_category_type_one_id' => 111,'name' => 'Nook 3G'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook color'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook GlowLight'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook GlowLight 3'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook GlowLight Plus'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook Simple Touch'],
    ['sub_category_type_one_id' => 111,'name' => 'Nook Simple Touch With GlowLight'],

    ['sub_category_type_one_id' => 112,'name' => 'A700'],/*58*/
    ['sub_category_type_one_id' => 112,'name' => 'C700'],
    ['sub_category_type_one_id' => 112,'name' => 'C701'],
    ['sub_category_type_one_id' => 112,'name' => 'CS700'],
    ['sub_category_type_one_id' => 112,'name' => 'D700'],
    ['sub_category_type_one_id' => 112,'name' => 'D701'],
    ['sub_category_type_one_id' => 112,'name' => 'E5'],
    ['sub_category_type_one_id' => 112,'name' => 'E500'],
    ['sub_category_type_one_id' => 112,'name' => 'E6'],
    ['sub_category_type_one_id' => 112,'name' => 'E600'],
    ['sub_category_type_one_id' => 112,'name' => 'E601'],
    ['sub_category_type_one_id' => 112,'name' => 'E601HD'],
    ['sub_category_type_one_id' => 112,'name' => 'E605'],
    ['sub_category_type_one_id' => 112,'name' => 'E60C'],
    ['sub_category_type_one_id' => 112,'name' => 'E61M'],
    ['sub_category_type_one_id' => 112,'name' => 'E624'],
    ['sub_category_type_one_id' => 112,'name' => 'E625'],
    ['sub_category_type_one_id' => 112,'name' => 'E626'],
    ['sub_category_type_one_id' => 112,'name' => 'E627'],
    ['sub_category_type_one_id' => 112,'name' => 'E628'],
    ['sub_category_type_one_id' => 112,'name' => 'E629'],
    ['sub_category_type_one_id' => 112,'name' => 'E62B'],
    ['sub_category_type_one_id' => 112,'name' => 'E630'],
    ['sub_category_type_one_id' => 112,'name' => 'E631'],
    ['sub_category_type_one_id' => 112,'name' => 'E632'],
    ['sub_category_type_one_id' => 112,'name' => 'E633'],
    ['sub_category_type_one_id' => 112,'name' => 'E634'],
    ['sub_category_type_one_id' => 112,'name' => 'E635'],
    ['sub_category_type_one_id' => 112,'name' => 'E63S'],
    ['sub_category_type_one_id' => 112,'name' => 'E63W'],
    ['sub_category_type_one_id' => 112,'name' => 'E64M'],
    ['sub_category_type_one_id' => 112,'name' => 'E652'],
    ['sub_category_type_one_id' => 112,'name' => 'E654'],
    ['sub_category_type_one_id' => 112,'name' => 'E656'],
    ['sub_category_type_one_id' => 112,'name' => 'E65G'],
    ['sub_category_type_one_id' => 112,'name' => 'E68B'],
    ['sub_category_type_one_id' => 112,'name' => 'E6DG'],
    ['sub_category_type_one_id' => 112,'name' => 'K1'],
    ['sub_category_type_one_id' => 112,'name' => 'K2'],
    ['sub_category_type_one_id' => 112,'name' => 'M1'],
    ['sub_category_type_one_id' => 112,'name' => 'M2'],
    ['sub_category_type_one_id' => 112,'name' => 'MagicBook W6LHD'],
    ['sub_category_type_one_id' => 112,'name' => 'Q1000'],
    ['sub_category_type_one_id' => 112,'name' => 'Q600'],
    ['sub_category_type_one_id' => 112,'name' => 'R61M'],
    ['sub_category_type_one_id' => 112,'name' => 'R62B'],
    ['sub_category_type_one_id' => 112,'name' => 'R634'],
    ['sub_category_type_one_id' => 112,'name' => 'R63S'],
    ['sub_category_type_one_id' => 112,'name' => 'R63W'],
    ['sub_category_type_one_id' => 112,'name' => 'R63W'],
    ['sub_category_type_one_id' => 112,'name' => 'R651'],
    ['sub_category_type_one_id' => 112,'name' => 'R652'],
    ['sub_category_type_one_id' => 112,'name' => 'R654'],
    ['sub_category_type_one_id' => 112,'name' => 'R655'],
    ['sub_category_type_one_id' => 112,'name' => 'R656'],
    ['sub_category_type_one_id' => 112,'name' => 'R657'],
    ['sub_category_type_one_id' => 112,'name' => 'R658'],
    ['sub_category_type_one_id' => 112,'name' => 'R659'],
    ['sub_category_type_one_id' => 112,'name' => 'R660'],
    ['sub_category_type_one_id' => 112,'name' => 'R663'],
    ['sub_category_type_one_id' => 112,'name' => 'R67M'],
    ['sub_category_type_one_id' => 112,'name' => 'R68B'],
    ['sub_category_type_one_id' => 112,'name' => 'S605'],
    ['sub_category_type_one_id' => 112,'name' => 'S605f'],
    ['sub_category_type_one_id' => 112,'name' => 'S605t'],
    ['sub_category_type_one_id' => 112,'name' => 'S60G'],
    ['sub_category_type_one_id' => 112,'name' => 'S665'],
    ['sub_category_type_one_id' => 112,'name' => 'S675'],
    ['sub_category_type_one_id' => 112,'name' => 'S676'],
    ['sub_category_type_one_id' => 112,'name' => 'S677'],
    ['sub_category_type_one_id' => 112,'name' => 'S683G'],
    ['sub_category_type_one_id' => 112,'name' => 'T635'],
    ['sub_category_type_one_id' => 112,'name' => 'T645'],
    ['sub_category_type_one_id' => 112,'name' => 'T646'],
    ['sub_category_type_one_id' => 112,'name' => 'T700'],
    ['sub_category_type_one_id' => 112,'name' => 'X600'],

    ['sub_category_type_one_id' => 113,'name' => 'MagicBook A62LHD'],/*134*/
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook A6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook C6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook C6HD TE'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook C6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook H6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook M5'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook M6'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook M61'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook M61P'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook P60'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook Q6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook R6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook R6L'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S62HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S62LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S65T'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S701'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook S702'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook T6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook T70'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook T7A'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook V6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook W6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook W6LHD'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook Z6'],
    ['sub_category_type_one_id' => 113,'name' => 'MagicBook Z6HD'],
    ['sub_category_type_one_id' => 113,'name' => 'T6LHD Lite'],

    ['sub_category_type_one_id' => 114,'name' => 'LE-106'],
    ['sub_category_type_one_id' => 114,'name' => 'LE-116'],
    ['sub_category_type_one_id' => 114,'name' => 'LT-105'],
    ['sub_category_type_one_id' => 114,'name' => 'LT-114'],
    ['sub_category_type_one_id' => 114,'name' => 'LT-115'],
    ['sub_category_type_one_id' => 114,'name' => 'LT-117'],
    ['sub_category_type_one_id' => 114,'name' => 'LT-127'],

    ['sub_category_type_one_id' => 115,'name' => 'BOOX Faust 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Faust 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Faust 4'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX Lumi 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Mira'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note 5'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova Air'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Volta 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Volta 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX A60S'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX A61S'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX A62S'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Amundsen'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Barcelona'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Bering 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C63M Marco Polo'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C63SM Bering'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C67ML Darwin'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C67ML Magellan 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C67ML Magellan 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C67SM Bering 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX C67SML Columbus'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Caesar'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Caesar 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Caesar 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Caesar 4'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Cleopatra 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Cleopatra 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Columbus 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 4'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 5'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 6'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 7'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Darwin 8'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Edison'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Euclid'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Faust'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Gulliver'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX i62M'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX i63ML Maxwell'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX i63ML Newton'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX i63SL'],
    ['sub_category_type_one_id' => 115,'name' => 'Boox i63SML Kopernik'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX i86ML Moby Dick'],
    ['sub_category_type_one_id' => 115,'name' => 'Boox James Cook'],
    ['sub_category_type_one_id' => 115,'name' => 'Boox James Cook 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Kon-Tiki'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Kon-Tiki 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Livingstone'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Lomonosov'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX M92'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX M96M Zeus'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Max'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX 2 Pro'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX Carta'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX MAX Lumi'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Miklukho-Maclay'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Monte Cristo'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Monte Cristo 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Monte Cristo 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Monte Cristo 4'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Monte Cristo 5'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note Air'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note Air 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note Pro'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Note S'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova 3 Color'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova Air C'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Nova Pro'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Poke 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Poke 2 Color'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Poke 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Poke 4 Lite'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Prometheus'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Prometheus 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Robinson Crusoe'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Robinson Crusoe 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX T76ML Cleopatra'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX T76SML Nefertiti'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Vasco da Gama'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Vasco da Gama 2'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Vasco da Gama 3'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Vasco da Gama 4'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Viking'],
    ['sub_category_type_one_id' => 115,'name' => 'BOOX Volta'],
    ['sub_category_type_one_id' => 115,'name' => 'C63L Akunin Book'],
    ['sub_category_type_one_id' => 115,'name' => 'Chronos'],
    ['sub_category_type_one_id' => 115,'name' => 'Dontsova Book'],
    ['sub_category_type_one_id' => 115,'name' => 'Leaf'],
    ['sub_category_type_one_id' => 115,'name' => 'Lukyanenko Book'],
    ['sub_category_type_one_id' => 115,'name' => 'ONYX My first book'],

    ['sub_category_type_one_id' => 116,'name' => '617'],
    ['sub_category_type_one_id' => 116,'name' => '740 Pro'],
    ['sub_category_type_one_id' => 116,'name' => '970'],
    ['sub_category_type_one_id' => 116,'name' => 'X'],
    ['sub_category_type_one_id' => 116,'name' => '301'],
    ['sub_category_type_one_id' => 116,'name' => '302'],
    ['sub_category_type_one_id' => 116,'name' => '360'],
    ['sub_category_type_one_id' => 116,'name' => '360 Plus'],
    ['sub_category_type_one_id' => 116,'name' => '606'],
    ['sub_category_type_one_id' => 116,'name' => '611 Basic'],
    ['sub_category_type_one_id' => 116,'name' => '613 Basic'],
    ['sub_category_type_one_id' => 116,'name' => '614 Basic'],
    ['sub_category_type_one_id' => 116,'name' => '614 Basic 3'],
    ['sub_category_type_one_id' => 116,'name' => '615'],
    ['sub_category_type_one_id' => 116,'name' => '616'],
    ['sub_category_type_one_id' => 116,'name' => '624 Basic Touch'],
    ['sub_category_type_one_id' => 116,'name' => '625 Basic Touch 2'],
    ['sub_category_type_one_id' => 116,'name' => '627 Touch Lux 4'],
    ['sub_category_type_one_id' => 116,'name' => '628 Touch Lux 5'],
    ['sub_category_type_one_id' => 116,'name' => '630 Fashion'],
    ['sub_category_type_one_id' => 116,'name' => '631 Touch HD'],
    ['sub_category_type_one_id' => 116,'name' => '631 Touch HD 2'],
    ['sub_category_type_one_id' => 116,'name' => '632 Aqua'],
    ['sub_category_type_one_id' => 116,'name' => '632 Touch HD 3'],
    ['sub_category_type_one_id' => 116,'name' => '633 Color'],
    ['sub_category_type_one_id' => 116,'name' => '640 Aqua'],
    ['sub_category_type_one_id' => 116,'name' => '641'],
    ['sub_category_type_one_id' => 116,'name' => '740'],
    ['sub_category_type_one_id' => 116,'name' => '740 Color'],
    ['sub_category_type_one_id' => 116,'name' => 'A10'],
    ['sub_category_type_one_id' => 116,'name' => 'A10 3G'],
    ['sub_category_type_one_id' => 116,'name' => 'A7'],
    ['sub_category_type_one_id' => 116,'name' => 'A7 3G'],
    ['sub_category_type_one_id' => 116,'name' => 'AZ101'],
    ['sub_category_type_one_id' => 116,'name' => 'Color Lux 801'],
    ['sub_category_type_one_id' => 116,'name' => 'Era'],
    ['sub_category_type_one_id' => 116,'name' => 'InkPad 2'],
    ['sub_category_type_one_id' => 116,'name' => 'InkPad 3'],
    ['sub_category_type_one_id' => 116,'name' => 'InkPad 3 Pro'],
    ['sub_category_type_one_id' => 116,'name' => 'InkPad 840'],
    ['sub_category_type_one_id' => 116,'name' => 'InkPad Color'],
    ['sub_category_type_one_id' => 116,'name' => 'IQ 701'],
    ['sub_category_type_one_id' => 116,'name' => 'Mini 515'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 602'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 603'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 612'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 902'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 903'],
    ['sub_category_type_one_id' => 116,'name' => 'Pro 912'],
    ['sub_category_type_one_id' => 116,'name' => 'Reader Book 1'],
    ['sub_category_type_one_id' => 116,'name' => 'Reader Book 2'],
    ['sub_category_type_one_id' => 116,'name' => 'Touch 622'],
    ['sub_category_type_one_id' => 116,'name' => 'Touch HD 3'],
    ['sub_category_type_one_id' => 116,'name' => 'Touch Lux 623'],
    ['sub_category_type_one_id' => 116,'name' => 'Touch Lux 626'],
    ['sub_category_type_one_id' => 116,'name' => 'Touch Lux 626 Plus'],
    ['sub_category_type_one_id' => 116,'name' => 'Ultra 650'],

    ['sub_category_type_one_id' => 117,'name' => 'RBK-200'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-330'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-400'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-420'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-421'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-422'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-423'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-425'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-429'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-430'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-431'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-433'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-435'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-436'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-450'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-460'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-470'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-475'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-490'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-493'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-495'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-496'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-497'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-499'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-520'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-600'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-610'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-615'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-616'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-617'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-620'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-650'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-670FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-675FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-676FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-677FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-678FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-680'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-690'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-695FL'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-750'],
    ['sub_category_type_one_id' => 117,'name' => 'RBK-900'],

    ['sub_category_type_one_id' => 118,'name' => 'E5001'],
    ['sub_category_type_one_id' => 118,'name' => 'E6001'],
    ['sub_category_type_one_id' => 118,'name' => 'E6002'],
    ['sub_category_type_one_id' => 118,'name' => 'E6003'],
    ['sub_category_type_one_id' => 118,'name' => 'E6005'],
    ['sub_category_type_one_id' => 118,'name' => 'E6007'],
    ['sub_category_type_one_id' => 118,'name' => 'E7001'],
    ['sub_category_type_one_id' => 118,'name' => 'Flex ONE'],
    ['sub_category_type_one_id' => 118,'name' => 'T5002'],
    ['sub_category_type_one_id' => 118,'name' => 'T7001'],
    ['sub_category_type_one_id' => 118,'name' => 'T7002'],
    ['sub_category_type_one_id' => 118,'name' => 'T7004'],
    ['sub_category_type_one_id' => 118,'name' => 'T7005'],
    ['sub_category_type_one_id' => 118,'name' => 'T7006'],
    ['sub_category_type_one_id' => 118,'name' => 'T7007'],
    ['sub_category_type_one_id' => 118,'name' => 'T7008'],
    ['sub_category_type_one_id' => 118,'name' => 'T7011'],
    ['sub_category_type_one_id' => 118,'name' => 'T7022'],
    ['sub_category_type_one_id' => 118,'name' => 'T7044'],
    ['sub_category_type_one_id' => 118,'name' => 'T7055'],
    ['sub_category_type_one_id' => 118,'name' => 'T7205'],
    ['sub_category_type_one_id' => 118,'name' => 'T7205'],
    ['sub_category_type_one_id' => 118,'name' => 'T7206'],
];


// ZTE den bashla


$woman_clothing_type = [
    ['sub_category_type_one_id' => 13,'name' => 'Dublyonkalar'],
    ['sub_category_type_one_id' => 13,'name' => 'Gödəkcələr'],
    ['sub_category_type_one_id' => 13,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 13,'name' => 'Kürklər'],
    ['sub_category_type_one_id' => 13,'name' => 'Paltolar'],
    ['sub_category_type_one_id' => 13,'name' => 'Pelerin və ponço'],
    ['sub_category_type_one_id' => 13,'name' => 'Plaşlar'],

    ['sub_category_type_one_id' => 16,'name' => 'Futbolkalar'],
    ['sub_category_type_one_id' => 16,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 16,'name' => 'Polo'],
    ['sub_category_type_one_id' => 16,'name' => 'Top-koftalar'],

    ['sub_category_type_one_id' => 20,'name' => 'Əlcəklər'],
    ['sub_category_type_one_id' => 20,'name' => 'Kepkalar'],
    ['sub_category_type_one_id' => 20,'name' => 'Papaqlar'],
    ['sub_category_type_one_id' => 20,'name' => 'Şərflər'],
    ['sub_category_type_one_id' => 20,'name' => 'Şlyapalar'],
    ['sub_category_type_one_id' => 20,'name' => 'Yaylıqlar'],

    ['sub_category_type_one_id' => 21,'name' => 'Penüarlar'],
    ['sub_category_type_one_id' => 21,'name' => 'Pijamalar'],
    ['sub_category_type_one_id' => 21,'name' => 'Xələtlər'],

    ['sub_category_type_one_id' => 22,'name' => 'Alt paltarı'],
    ['sub_category_type_one_id' => 22,'name' => 'Bodi'],
    ['sub_category_type_one_id' => 22,'name' => 'Büstqalterlər'],
    ['sub_category_type_one_id' => 22,'name' => 'Corablar'],
    ['sub_category_type_one_id' => 22,'name' => 'Korsetlər'],

    ['sub_category_type_one_id' => 23,'name' => 'Yastıdaban ayaqqabılar'],
    ['sub_category_type_one_id' => 23,'name' => 'Çəkələklər'],
    ['sub_category_type_one_id' => 23,'name' => 'Çəkmələr'],
    ['sub_category_type_one_id' => 23,'name' => 'Ev ayaqqabıları'],
    ['sub_category_type_one_id' => 23,'name' => 'Hündürdaban ayaqqabılar'],
    ['sub_category_type_one_id' => 23,'name' => 'İdman ayaqqabıları'],
    ['sub_category_type_one_id' => 23,'name' => 'Kedlər'],
    ['sub_category_type_one_id' => 23,'name' => 'Uzunboğaz çəkmələr'],

    ['sub_category_type_one_id' => 24,'name' => 'Ətəklər'],
    ['sub_category_type_one_id' => 24,'name' => 'Gəlinliklər'],
    ['sub_category_type_one_id' => 24,'name' => 'Gündəlik donlar'],
    ['sub_category_type_one_id' => 24,'name' => 'Sarafanlar'],
    ['sub_category_type_one_id' => 24,'name' => 'Ziyafət donları'],

    ['sub_category_type_one_id' => 25,'name' => 'Cemperlər və sviterlər'],
    ['sub_category_type_one_id' => 25,'name' => 'Hudi və svitşotlar'],
    ['sub_category_type_one_id' => 25,'name' => 'Jaketlər'],
    ['sub_category_type_one_id' => 25,'name' => 'Koftalar və bluzlar'],
    ['sub_category_type_one_id' => 25,'name' => 'Uzunboğaz kofta'],

    ['sub_category_type_one_id' => 27,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 27,'name' => 'Kostyumlar'],
    ['sub_category_type_one_id' => 27,'name' => 'Pencəklər'],

    ['sub_category_type_one_id' => 28,'name' => 'Bricilər və kaprilər'],
    ['sub_category_type_one_id' => 28,'name' => 'Cinslər'],
    ['sub_category_type_one_id' => 28,'name' => 'Losinlər'],
    ['sub_category_type_one_id' => 28,'name' => 'Şalvarlar'],
    ['sub_category_type_one_id' => 28,'name' => 'Şortlar'],
];
$woman_clothing_type_size = [
    ['sub_category_type_one_id' => 13,'size' => '34 (XS) və daha az'],
    ['sub_category_type_one_id' => 13,'size' => '36 (S)'],
    ['sub_category_type_one_id' => 13,'size' => '38 (M)'],
    ['sub_category_type_one_id' => 13,'size' => '40 (L)'],
    ['sub_category_type_one_id' => 13,'size' => '42 (XL)'],
    ['sub_category_type_one_id' => 13,'size' => '44 (XXL)'],
    ['sub_category_type_one_id' => 13,'size' => '46 (XXXL) və daha çox'],
];
$woman_clothing_type_pants_size = [
    ['sub_category_type_one_id' => 28,'name' => '24 və daha az'],
    ['sub_category_type_one_id' => 28,'name' => '25'],
    ['sub_category_type_one_id' => 28,'name' => '26'],
    ['sub_category_type_one_id' => 28,'name' => '27'],
    ['sub_category_type_one_id' => 28,'name' => '28'],
    ['sub_category_type_one_id' => 28,'name' => '29'],
    ['sub_category_type_one_id' => 28,'name' => '30'],
    ['sub_category_type_one_id' => 28,'name' => '31'],
    ['sub_category_type_one_id' => 28,'name' => '32'],
    ['sub_category_type_one_id' => 28,'name' => '33'],
    ['sub_category_type_one_id' => 28,'name' => '34'],
    ['sub_category_type_one_id' => 28,'name' => '35'],
    ['sub_category_type_one_id' => 28,'name' => '36'],
    ['sub_category_type_one_id' => 28,'name' => '37'],
    ['sub_category_type_one_id' => 28,'name' => '38'],
    ['sub_category_type_one_id' => 28,'name' => '39'],
    ['sub_category_type_one_id' => 28,'name' => '40'],
    ['sub_category_type_one_id' => 28,'name' => '41'],
    ['sub_category_type_one_id' => 28,'name' => '42'],
    ['sub_category_type_one_id' => 28,'name' => '43'],
    ['sub_category_type_one_id' => 28,'name' => '44 və daha çox'],
];
$woman_clothing_type_shoe_size = [
    ['sub_category_type_one_id' => 23,'name' => '34 və daha az'],
    ['sub_category_type_one_id' => 23,'name' => '35'],
    ['sub_category_type_one_id' => 23,'name' => '36'],
    ['sub_category_type_one_id' => 23,'name' => '37'],
    ['sub_category_type_one_id' => 23,'name' => '38'],
    ['sub_category_type_one_id' => 23,'name' => '39'],
    ['sub_category_type_one_id' => 23,'name' => '40'],
    ['sub_category_type_one_id' => 23,'name' => '41'],
    ['sub_category_type_one_id' => 23,'name' => '42'],
    ['sub_category_type_one_id' => 23,'name' => '43'],
    ['sub_category_type_one_id' => 23,'name' => '43 və daha çox'],
];
$woman_clothing_brand = [
    ['sub_category_type_id' => 8,'name' => 'Adidas'],
    ['sub_category_type_id' => 8,'name' => 'AdL'],
    ['sub_category_type_id' => 8,'name' => 'Adolfo Dominguez'],
    ['sub_category_type_id' => 8,'name' => 'Armani Collezioni'],
    ['sub_category_type_id' => 8,'name' => 'Armani Exchange'],
    ['sub_category_type_id' => 8,'name' => 'Armani Jeans'],
    ['sub_category_type_id' => 8,'name' => 'Armonika'],
    ['sub_category_type_id' => 8,'name' => 'Asos'],
    ['sub_category_type_id' => 8,'name' => 'Banana Republic'],
    ['sub_category_type_id' => 8,'name' => 'Bebe'],
    ['sub_category_type_id' => 8,'name' => 'Bebe Plus'],
    ['sub_category_type_id' => 8,'name' => 'Benetton'],
    ['sub_category_type_id' => 8,'name' => 'Bershka'],
    ['sub_category_type_id' => 8,'name' => 'Burberry'],
    ['sub_category_type_id' => 8,'name' => 'Calvin Klein'],
    ['sub_category_type_id' => 8,'name' => 'Carolina Herrera'],
    ['sub_category_type_id' => 8,'name' => 'Chanel'],
    ['sub_category_type_id' => 8,'name' => 'Citizen'],
    ['sub_category_type_id' => 8,'name' => 'Colin'],
    ['sub_category_type_id' => 8,'name' => 'Collezione'],
    ['sub_category_type_id' => 8,'name' => 'Columbia'],
    ['sub_category_type_id' => 8,'name' => 'Cool Sexy'],
    ['sub_category_type_id' => 8,'name' => 'Dericlub'],
    ['sub_category_type_id' => 8,'name' => 'Dilvin'],
    ['sub_category_type_id' => 8,'name' => 'Dkny'],
    ['sub_category_type_id' => 8,'name' => 'Donna Karan'],
    ['sub_category_type_id' => 8,'name' => 'EA7'],
    ['sub_category_type_id' => 8,'name' => 'Elie Saab'],
    ['sub_category_type_id' => 8,'name' => 'Emporio Armani'],
    ['sub_category_type_id' => 8,'name' => 'Escada'],
    ['sub_category_type_id' => 8,'name' => 'Faik Sönmez'],
    ['sub_category_type_id' => 8,'name' => 'Faik Sönmez'],
    ['sub_category_type_id' => 8,'name' => 'Fila'],
    ['sub_category_type_id' => 8,'name' => 'Fullamoda'],
    ['sub_category_type_id' => 8,'name' => 'GAP'],
    ['sub_category_type_id' => 8,'name' => 'Guess'],
    ['sub_category_type_id' => 8,'name' => 'H&M'],
    ['sub_category_type_id' => 8,'name' => 'H&Helly Hansen'],
    ['sub_category_type_id' => 8,'name' => 'Hugo Boss'],
    ['sub_category_type_id' => 8,'name' => 'Hummel'],
    ['sub_category_type_id' => 8,'name' => 'İnci'],
    ['sub_category_type_id' => 8,'name' => 'İpekyol'],
    ['sub_category_type_id' => 8,'name' => 'Just Cavalli'],
    ['sub_category_type_id' => 8,'name' => 'Kappa'],
    ['sub_category_type_id' => 8,'name' => 'Karen Millen'],
    ['sub_category_type_id' => 8,'name' => 'Karl Lagerfeld'],
    ['sub_category_type_id' => 8,'name' => 'Kenzo'],
    ['sub_category_type_id' => 8,'name' => 'Kinetix'],
    ['sub_category_type_id' => 8,'name' => 'Koton'],
    ['sub_category_type_id' => 8,'name' => 'Lanvin'],
    ['sub_category_type_id' => 8,'name' => 'LC Waikiki'],
    ['sub_category_type_id' => 8,'name' => "Levi's"],
    ['sub_category_type_id' => 8,'name' => 'Loft'],
    ['sub_category_type_id' => 8,'name' => 'Ltb'],
    ['sub_category_type_id' => 8,'name' => 'Lumberjack'],
    ['sub_category_type_id' => 8,'name' => 'Mango'],
    ['sub_category_type_id' => 8,'name' => 'Marks & Spencer'],
    ['sub_category_type_id' => 8,'name' => 'Massimo Dutti'],
    ['sub_category_type_id' => 8,'name' => 'Mavi'],
    ['sub_category_type_id' => 8,'name' => 'Michael Kors'],
    ['sub_category_type_id' => 8,'name' => 'Miss Ipekyol'],
    ['sub_category_type_id' => 8,'name' => 'Moncler'],
    ['sub_category_type_id' => 8,'name' => 'Nike'],
    ['sub_category_type_id' => 8,'name' => 'Olalook'],
    ['sub_category_type_id' => 8,'name' => 'Oysho'],
    ['sub_category_type_id' => 8,'name' => 'Penti'],
    ['sub_category_type_id' => 8,'name' => 'Pierre Cardin'],
    ['sub_category_type_id' => 8,'name' => 'Pimkie'],
    ['sub_category_type_id' => 8,'name' => 'Pull & Bear'],
    ['sub_category_type_id' => 8,'name' => 'Puma'],
    ['sub_category_type_id' => 8,'name' => 'Reebok'],
    ['sub_category_type_id' => 8,'name' => 'Robin'],
    ['sub_category_type_id' => 8,'name' => 'Sisley'],
    ['sub_category_type_id' => 8,'name' => 'Stradivarius'],
    ['sub_category_type_id' => 8,'name' => 'The North Face'],
    ['sub_category_type_id' => 8,'name' => 'Tiffany'],
    ['sub_category_type_id' => 8,'name' => 'Tom Ford'],
    ['sub_category_type_id' => 8,'name' => 'Tommy Hilfiger'],
    ['sub_category_type_id' => 8,'name' => 'Tonny Black'],
    ['sub_category_type_id' => 8,'name' => 'Trendyol Modest'],
    ['sub_category_type_id' => 8,'name' => 'Trendyolmilla'],
    ['sub_category_type_id' => 8,'name' => 'Twist'],
    ['sub_category_type_id' => 8,'name' => 'US Polo Assn'],
    ['sub_category_type_id' => 8,'name' => 'Vans'],
    ['sub_category_type_id' => 8,'name' => 'Vero Moda'],
    ['sub_category_type_id' => 8,'name' => 'Versace'],
    ['sub_category_type_id' => 8,'name' => 'Waggon'],
    ['sub_category_type_id' => 8,'name' => 'Wilson'],
    ['sub_category_type_id' => 8,'name' => 'XHAN'],
    ['sub_category_type_id' => 8,'name' => 'Zara']
];


$man_clothing_type = [
    ['sub_category_type_one_id' => 29,'name' => 'Dublyonkalar'],
    ['sub_category_type_one_id' => 29,'name' => 'Gödəkcələr'],
    ['sub_category_type_one_id' => 29,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 29,'name' => 'Paltolar'],
    ['sub_category_type_one_id' => 29,'name' => 'Plaşlar'],

    ['sub_category_type_one_id' => 30,'name' => 'Əlcəklər'],
    ['sub_category_type_one_id' => 30,'name' => 'Kepkalar və beysbolkalar'],
    ['sub_category_type_one_id' => 30,'name' => 'Papaqlar'],
    ['sub_category_type_one_id' => 30,'name' => 'Şərflər'],
    ['sub_category_type_one_id' => 30,'name' => 'Şlyapalar'],

    ['sub_category_type_one_id' => 31,'name' => 'Pijamalar'],
    ['sub_category_type_one_id' => 31,'name' => 'Xələtlər'],

    ['sub_category_type_one_id' => 32,'name' => 'Alt paltarı'],
    ['sub_category_type_one_id' => 32,'name' => 'Corablar'],
    ['sub_category_type_one_id' => 32,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 32,'name' => 'Termal alt paltarları'],

    ['sub_category_type_one_id' => 33,'name' => 'Çəkələklər'],
    ['sub_category_type_one_id' => 33,'name' => 'Çəkmələr'],
    ['sub_category_type_one_id' => 33,'name' => 'Ev ayaqqabıları'],
    ['sub_category_type_one_id' => 33,'name' => 'İdman ayaqqabıları'],
    ['sub_category_type_one_id' => 33,'name' => 'Kedlər'],
    ['sub_category_type_one_id' => 33,'name' => 'Klassik ayaqqabılar'],
    ['sub_category_type_one_id' => 33,'name' => 'Mokasinlər'],
    ['sub_category_type_one_id' => 33,'name' => 'Səndəllər'],
    ['sub_category_type_one_id' => 33,'name' => 'Uzunboğaz çəkmələr'],

    ['sub_category_type_one_id' => 34,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 34,'name' => 'Kostyumlar'],
    ['sub_category_type_one_id' => 34,'name' => 'Pencəklər'],

    ['sub_category_type_one_id' => 35,'name' => 'Cemperlər və sviterlər'],
    ['sub_category_type_one_id' => 35,'name' => 'Hudi və svitşotlar'],
    ['sub_category_type_one_id' => 35,'name' => 'Jaketlər'],
    ['sub_category_type_one_id' => 35,'name' => 'Koftalar'],
    ['sub_category_type_one_id' => 35,'name' => 'Uzunboğaz koftalar'],

    ['sub_category_type_one_id' => 36,'name' => 'Futbolkalar'],
    ['sub_category_type_one_id' => 36,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 36,'name' => 'Polo'],

    ['sub_category_type_one_id' => 37,'name' => 'Cinslər'],
    ['sub_category_type_one_id' => 37,'name' => 'Şalvarlar'],
    ['sub_category_type_one_id' => 37,'name' => 'Şortlar'],
    ['sub_category_type_one_id' => 37,'name' => 'Şortlar'],
];
$man_clothing_type_size = [
    ['sub_category_type_one_id' => 34,'size' => '34 (XS) və daha az'],
    ['sub_category_type_one_id' => 34,'size' => '36 (S)'],
    ['sub_category_type_one_id' => 34,'size' => '38 (M)'],
    ['sub_category_type_one_id' => 34,'size' => '40 (L)'],
    ['sub_category_type_one_id' => 34,'size' => '42 (XL)'],
    ['sub_category_type_one_id' => 34,'size' => '44 (XXL)'],
    ['sub_category_type_one_id' => 34,'size' => '48 (4XL) və daha çox'],
];
$man_clothing_type_pants_size = [
    ['sub_category_type_one_id' => 37,'name' => '28 və daha az'],
    ['sub_category_type_one_id' => 37,'name' => '29'],
    ['sub_category_type_one_id' => 37,'name' => '30'],
    ['sub_category_type_one_id' => 37,'name' => '31'],
    ['sub_category_type_one_id' => 37,'name' => '32'],
    ['sub_category_type_one_id' => 37,'name' => '33'],
    ['sub_category_type_one_id' => 37,'name' => '34'],
    ['sub_category_type_one_id' => 37,'name' => '35'],
    ['sub_category_type_one_id' => 37,'name' => '36'],
    ['sub_category_type_one_id' => 37,'name' => '37'],
    ['sub_category_type_one_id' => 37,'name' => '38'],
    ['sub_category_type_one_id' => 37,'name' => '39'],
    ['sub_category_type_one_id' => 37,'name' => '40'],
    ['sub_category_type_one_id' => 37,'name' => '41'],
    ['sub_category_type_one_id' => 37,'name' => '42'],
    ['sub_category_type_one_id' => 37,'name' => '43'],
    ['sub_category_type_one_id' => 37,'name' => '44'],
    ['sub_category_type_one_id' => 37,'name' => '45'],
    ['sub_category_type_one_id' => 37,'name' => '46'],
    ['sub_category_type_one_id' => 37,'name' => '47'],
    ['sub_category_type_one_id' => 37,'name' => '48'],
    ['sub_category_type_one_id' => 37,'name' => '49'],
    ['sub_category_type_one_id' => 37,'name' => '50 və daha çox'],
];
$man_clothing_type_shoe_size = [
    ['sub_category_type_one_id' => 33,'name' => '36 və daha az'],
    ['sub_category_type_one_id' => 33,'name' => '37'],
    ['sub_category_type_one_id' => 33,'name' => '38'],
    ['sub_category_type_one_id' => 33,'name' => '39'],
    ['sub_category_type_one_id' => 33,'name' => '40'],
    ['sub_category_type_one_id' => 33,'name' => '41'],
    ['sub_category_type_one_id' => 33,'name' => '42'],
    ['sub_category_type_one_id' => 33,'name' => '43'],
    ['sub_category_type_one_id' => 33,'name' => '44'],
    ['sub_category_type_one_id' => 33,'name' => '45'],
    ['sub_category_type_one_id' => 33,'name' => '46 və daha çox'],
];
$man_clothing_brand = [
    ['sub_category_type_id' => 9,'name' => 'Baldinini'],
    ['sub_category_type_id' => 9,'name' => 'Adidas'],
    ['sub_category_type_id' => 9,'name' => 'Armani'],
    ['sub_category_type_id' => 9,'name' => 'Asos'],
    ['sub_category_type_id' => 9,'name' => 'Avva'],
    ['sub_category_type_id' => 9,'name' => 'Bershka'],
    ['sub_category_type_id' => 9,'name' => 'Calvin Klein'],
    ['sub_category_type_id' => 9,'name' => 'Colin’s'],
    ['sub_category_type_id' => 9,'name' => 'Collezione'],
    ['sub_category_type_id' => 9,'name' => 'Defacto'],
    ['sub_category_type_id' => 9,'name' => 'Derimod'],
    ['sub_category_type_id' => 9,'name' => 'Dior'],
    ['sub_category_type_id' => 9,'name' => 'Dsquared'],
    ['sub_category_type_id' => 9,'name' => 'DSquared2'],
    ['sub_category_type_id' => 9,'name' => 'Emporio Armani'],
    ['sub_category_type_id' => 9,'name' => 'ETRO'],
    ['sub_category_type_id' => 9,'name' => 'Fendi'],
    ['sub_category_type_id' => 9,'name' => 'Fullamoda'],
    ['sub_category_type_id' => 9,'name' => 'Galvanni'],
    ['sub_category_type_id' => 9,'name' => 'Gucci'],
    ['sub_category_type_id' => 9,'name' => 'H&M'],
    ['sub_category_type_id' => 9,'name' => 'Hatemoğlu'],
    ['sub_category_type_id' => 9,'name' => 'Hugo Boss'],
    ['sub_category_type_id' => 9,'name' => 'Hummel'],
    ['sub_category_type_id' => 9,'name' => 'Hunter'],
    ['sub_category_type_id' => 9,'name' => 'Jack Jones'],
    ['sub_category_type_id' => 9,'name' => 'Kappa'],
    ['sub_category_type_id' => 9,'name' => 'Kenzo'],
    ['sub_category_type_id' => 9,'name' => 'Kiğılı'],
    ['sub_category_type_id' => 9,'name' => 'Kinetix'],
    ['sub_category_type_id' => 9,'name' => 'Koton'],
    ['sub_category_type_id' => 9,'name' => 'Lacoste'],
    ['sub_category_type_id' => 9,'name' => 'LC Waikiki'],
    ['sub_category_type_id' => 9,'name' => "Levi's"],
    ['sub_category_type_id' => 9,'name' => "Ltb"],
    ['sub_category_type_id' => 9,'name' => "Lumberjack"],
    ['sub_category_type_id' => 9,'name' => "Mango"],
    ['sub_category_type_id' => 9,'name' => "Massimo Dutti"],
    ['sub_category_type_id' => 9,'name' => "Mavi"],
    ['sub_category_type_id' => 9,'name' => "Milan"],
    ['sub_category_type_id' => 9,'name' => "Moncler"],
    ['sub_category_type_id' => 9,'name' => "New Balance"],
    ['sub_category_type_id' => 9,'name' => "Nike"],
    ['sub_category_type_id' => 9,'name' => "Philipp Plein"],
    ['sub_category_type_id' => 9,'name' => "Pierre Cardin"],
    ['sub_category_type_id' => 9,'name' => "Prada"],
    ['sub_category_type_id' => 9,'name' => "Puma"],
    ['sub_category_type_id' => 9,'name' => "Ramsey"],
    ['sub_category_type_id' => 9,'name' => "Reebok"],
    ['sub_category_type_id' => 9,'name' => "Rodi Jeans"],
    ['sub_category_type_id' => 9,'name' => "Süvari"],
    ['sub_category_type_id' => 9,'name' => "Ted Baker"],
    ['sub_category_type_id' => 9,'name' => "The North Face"],
    ['sub_category_type_id' => 9,'name' => "Timberland"],
    ['sub_category_type_id' => 9,'name' => "Tommy Hilfiger"],
    ['sub_category_type_id' => 9,'name' => "Trendyol Man"],
    ['sub_category_type_id' => 9,'name' => "US Polo Assn"],
    ['sub_category_type_id' => 9,'name' => "Versace"],
    ['sub_category_type_id' => 9,'name' => "XHAN"],
    ['sub_category_type_id' => 9,'name' => "Zara"],
    ['sub_category_type_id' => 9,'name' => "Zara"],
];


$season = [
    ['sub_category_id' => 16, 'name' => 'Yarım mövsüm'],
    ['sub_category_id' => 16, 'name' => 'Yay'],
    ['sub_category_id' => 16, 'name' => 'Qış']
];

$child_suits_and_jacket_size = [
    ['sub_category_type_one_id' => 2,'size' => '0-3 ay'],
    ['sub_category_type_one_id' => 2,'size' => '3-6 ay'],
    ['sub_category_type_one_id' => 2,'size' => '6-9 ay'],
    ['sub_category_type_one_id' => 2,'size' => '9-12 ay'],
    ['sub_category_type_one_id' => 2,'size' => '12-18 ay'],
    ['sub_category_type_one_id' => 2,'size' => '18-24 ay'],
    ['sub_category_type_one_id' => 2,'size' => '2-3 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '3-4 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '4-5 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '5-6 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '7-8 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '8-9 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '9-10 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '10-11 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '11-12 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '12-13 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '13-14 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '14-15 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '15-16 yaş'],
];
$child_shoe_size = [
    ['size' => 16],
    ['size' => 17],
    ['size' => 18],
    ['size' => 19],
    ['size' => 20],
    ['size' => 21],
    ['size' => 22],
    ['size' => 23],
    ['size' => 24],
    ['size' => 25],
    ['size' => 26],
    ['size' => 27],
    ['size' => 28],
    ['size' => 29],
    ['size' => 30],
    ['size' => 31],
    ['size' => 32],
    ['size' => 33],
    ['size' => 34],
    ['size' => 35],
    ['size' => 36],
];


$color = [
    ['name' => 'Ağ'],
    ['name' => 'Bej'],
    ['name' => 'Bənövşəyi'],
    ['name' => 'Boz'],
    ['name' => 'Çəhrayı'],
    ['name' => 'Göy'],
    ['name' => 'Gümüşü'],
    ['name' => 'Mavi'],
    ['name' => 'Narıncı'],
    ['name' => 'Qara'],
    ['name' => 'Qəhvəyi'],
    ['name' => 'Qırmızı'],
    ['name' => 'Qızılı'],
    ['name' => 'Sarı'],
    ['name' => 'Tünd qırmızı'],
    ['name' => 'Yaş Asfalt'],
    ['name' => 'Yaşıl'],
];

$fuel_type = [
    ['name' => 'Benzin'],
    ['name' => 'Dizel'],
    ['name' => 'Qaz'],
    ['name' => 'Elektro'],
    ['name' => 'Hibrid'],
];
$transmission = [
    ['name' => 'Mexaniki'],
    ['name' => 'Avtomat'],
    ['name' => 'Robotlaşdırılmış'],
    ['name' => 'Variator'],
];
$body_type = [
    ['name' => 'Sedan'],
    ['name' => 'Universal'],
    ['name' => 'Hetçbek'],
    ['name' => 'Kupe'],
    ['name' => 'Rodster'],
    ['name' => 'Mikroavtobus'],
    ['name' => 'Pikap'],
    ['name' => 'Limuzin'],
    ['name' => 'Krosover'],
    ['name' => 'Miniven'],
    ['name' => 'Kabriolet'],
    ['name' => 'Offroader'],
];
$motorbikeType = [
    ['subcategory_id' => 57,'name' => 'Baqqi'],
    ['subcategory_id' => 57,'name' => 'Kvadrosikllar'],
    ['subcategory_id' => 57,'name' => 'Mopedlər'],
    ['subcategory_id' => 57,'name' => 'Motosikletlər'],
    ['subcategory_id' => 57,'name' => 'Motosikletlər'],
    ['subcategory_id' => 57,'name' => 'Skuterlər'],
];
$motorbikeMarka = [
    ['subcategory_id' => 57,'name' => 'ABM'],
    ['subcategory_id' => 57,'name' => 'AMC'],
    ['subcategory_id' => 57,'name' => 'Aprilia'],
    ['subcategory_id' => 57,'name' => 'Arctic Cat'],
    ['subcategory_id' => 57,'name' => 'ATV'],
    ['subcategory_id' => 57,'name' => 'Baotian'],
    ['subcategory_id' => 57,'name' => 'BMW'],
    ['subcategory_id' => 57,'name' => 'Buell'],
    ['subcategory_id' => 57,'name' => 'Can-Am'],
    ['subcategory_id' => 57,'name' => 'CFMOTO'],
    ['subcategory_id' => 57,'name' => 'Changan'],
    ['subcategory_id' => 57,'name' => 'Chery'],
    ['subcategory_id' => 57,'name' => 'Chevrolet'],
    ['subcategory_id' => 57,'name' => 'Chituma'],
    ['subcategory_id' => 57,'name' => 'CZ'],
    ['subcategory_id' => 57,'name' => 'Dayun'],
    ['subcategory_id' => 57,'name' => 'Dnepr'],
    ['subcategory_id' => 57,'name' => 'Ducati'],
    ['subcategory_id' => 57,'name' => 'Foton'],
    ['subcategory_id' => 57,'name' => 'Gabro'],
    ['subcategory_id' => 57,'name' => 'Geely'],
    ['subcategory_id' => 57,'name' => 'Gilera'],
    ['subcategory_id' => 57,'name' => 'Great Wall'],
    ['subcategory_id' => 57,'name' => 'GUSİDE'],
    ['subcategory_id' => 57,'name' => 'Hamtaz'],
    ['subcategory_id' => 57,'name' => 'Haojue'],
    ['subcategory_id' => 57,'name' => 'Harley-Davidson'],
    ['subcategory_id' => 57,'name' => 'Haval'],
    ['subcategory_id' => 57,'name' => 'Hisun - motocars'],
    ['subcategory_id' => 57,'name' => 'Honda'],
    ['subcategory_id' => 57,'name' => 'Huzhou'],
    ['subcategory_id' => 57,'name' => 'Hyosung'],
    ['subcategory_id' => 57,'name' => 'Hyundai'],
    ['subcategory_id' => 57,'name' => 'IJ'],
    ['subcategory_id' => 57,'name' => 'Infiniti'],
    ['subcategory_id' => 57,'name' => 'Jawa'],
    ['subcategory_id' => 57,'name' => 'Jiajue'],
    ['subcategory_id' => 57,'name' => 'Jinan'],
    ['subcategory_id' => 57,'name' => 'Jinbei'],
    ['subcategory_id' => 57,'name' => 'Jonway'],
    ['subcategory_id' => 57,'name' => 'Kawasaki'],
    ['subcategory_id' => 57,'name' => 'Kayo'],
    ['subcategory_id' => 57,'name' => 'Kia'],
    ['subcategory_id' => 57,'name' => 'Kinroad'],
    ['subcategory_id' => 57,'name' => 'KTM'],
    ['subcategory_id' => 57,'name' => 'LADA (VAZ)'],
    ['subcategory_id' => 57,'name' => 'Land Rover'],
    ['subcategory_id' => 57,'name' => 'Lexus'],
    ['subcategory_id' => 57,'name' => 'Marseille'],
    ['subcategory_id' => 57,'name' => 'Mazda'],
    ['subcategory_id' => 57,'name' => 'Megelli'],
    ['subcategory_id' => 57,'name' => 'Mercedes'],
    ['subcategory_id' => 57,'name' => 'Minsk'],
    ['subcategory_id' => 57,'name' => 'Mitsubishi'],
    ['subcategory_id' => 57,'name' => 'Mondial'],
    ['subcategory_id' => 57,'name' => 'Muravey'],
    ['subcategory_id' => 57,'name' => 'MV Agusta'],
    ['subcategory_id' => 57,'name' => 'Neoplan'],
    ['subcategory_id' => 57,'name' => 'Neptun'],
    ['subcategory_id' => 57,'name' => 'Nissan'],
    ['subcategory_id' => 57,'name' => 'NIU'],
    ['subcategory_id' => 57,'name' => 'Opel'],
    ['subcategory_id' => 57,'name' => 'Parvaz'],
    ['subcategory_id' => 57,'name' => 'Piaggio'],
    ['subcategory_id' => 57,'name' => 'Polaris'],
    ['subcategory_id' => 57,'name' => 'QAZ'],
    ['subcategory_id' => 57,'name' => 'Rialli'],
    ['subcategory_id' => 57,'name' => 'Riga'],
    ['subcategory_id' => 57,'name' => 'Shineray'],
    ['subcategory_id' => 57,'name' => 'Skyline'],
    ['subcategory_id' => 57,'name' => 'Sport'],
    ['subcategory_id' => 57,'name' => 'Suzuki'],
    ['subcategory_id' => 57,'name' => 'SYM'],
    ['subcategory_id' => 57,'name' => 'Toyota'],
    ['subcategory_id' => 57,'name' => 'Triumph'],
    ['subcategory_id' => 57,'name' => 'UAZ'],
    ['subcategory_id' => 57,'name' => 'Ural'],
    ['subcategory_id' => 57,'name' => 'Vespa'],
    ['subcategory_id' => 57,'name' => 'Volkswagen'],
    ['subcategory_id' => 57,'name' => 'Vosxod'],
    ['subcategory_id' => 57,'name' => 'Vyatka'],
    ['subcategory_id' => 57,'name' => 'Yadea'],
    ['subcategory_id' => 57,'name' => 'Yamaha'],
    ['subcategory_id' => 57,'name' => 'Zongshen'],
    ['subcategory_id' => 57,'name' => 'Zontes'],
];
$busType = [
    ['sub_category_id' => 58, 'name' => 'Avtobuslar'],
    ['sub_category_id' => 58, 'name' => 'Avtokranlar'],
    ['sub_category_id' => 58, 'name' => 'Yük maşınları'],
    ['sub_category_id' => 58, 'name' => 'Qoşqular'],
    ['sub_category_id' => 58, 'name' => 'Tikinti texnikası'],
];
$bus_marka = [
    ['sub_category_id' => 58, 'name' => 'AMMANN'],
    ['sub_category_id' => 58, 'name' => 'Belarus'],
    ['sub_category_id' => 58, 'name' => 'Bobcat'],
    ['sub_category_id' => 58, 'name' => 'Bomag'],
    ['sub_category_id' => 58, 'name' => 'Cat'],
    ['sub_category_id' => 58, 'name' => 'Daf'],
    ['sub_category_id' => 58, 'name' => 'DongFeng'],
    ['sub_category_id' => 58, 'name' => 'FAW'],
    ['sub_category_id' => 58, 'name' => 'Fiat'],
    ['sub_category_id' => 58, 'name' => 'Ford'],
    ['sub_category_id' => 58, 'name' => 'Foton'],
    ['sub_category_id' => 58, 'name' => 'Hidromek'],
    ['sub_category_id' => 58, 'name' => 'Hitachi'],
    ['sub_category_id' => 58, 'name' => 'Howo'],
    ['sub_category_id' => 58, 'name' => 'Hyundai'],
    ['sub_category_id' => 58, 'name' => 'Isuzu'],
    ['sub_category_id' => 58, 'name' => 'Iveco'],
    ['sub_category_id' => 58, 'name' => 'JAC'],
    ['sub_category_id' => 58, 'name' => 'JCB'],
    ['sub_category_id' => 58, 'name' => 'Jungheinrich'],
    ['sub_category_id' => 58, 'name' => 'Kamaz'],
    ['sub_category_id' => 58, 'name' => 'Komatsu'],
    ['sub_category_id' => 58, 'name' => 'Kraz'],
    ['sub_category_id' => 58, 'name' => 'Liebherr'],
    ['sub_category_id' => 58, 'name' => 'Linde'],
    ['sub_category_id' => 58, 'name' => 'MAN'],
    ['sub_category_id' => 58, 'name' => 'Mack'],
    ['sub_category_id' => 58, 'name' => 'Maz'],
    ['sub_category_id' => 58, 'name' => 'Mercedes Benz'],
    ['sub_category_id' => 58, 'name' => 'Mitsubishi'],
    ['sub_category_id' => 58, 'name' => 'Otocar'],
    ['sub_category_id' => 58, 'name' => 'Qazel'],
    ['sub_category_id' => 58, 'name' => 'RAF'],
    ['sub_category_id' => 58, 'name' => 'Renault'],
    ['sub_category_id' => 58, 'name' => 'Scania'],
    ['sub_category_id' => 58, 'name' => 'Shacman'],
    ['sub_category_id' => 58, 'name' => 'Sumitomo'],
    ['sub_category_id' => 58, 'name' => 'T-seriya'],
    ['sub_category_id' => 58, 'name' => 'Tatra'],
    ['sub_category_id' => 58, 'name' => 'Volvo'],
    ['sub_category_id' => 58, 'name' => 'Wirtgen'],
    ['sub_category_id' => 58, 'name' => 'Zil'],
    ['sub_category_id' => 58, 'name' => 'Zoomlion'],
];

$sale_type = [
    ['name' => 'Satılır'],
    ['name' => 'Kirayə verilir'],
];
$apartmentType = [
    ['sub_category_id' => 60, 'name' => 'Yeni tikili'],
    ['sub_category_id' => 60, 'name' => 'Köhnə tikili'],
];
$villa_property_type = [
    ['sub_category_id' => 61, 'name' => 'Bağ evi'],
    ['sub_category_id' => 61, 'name' => 'Həyət evi'],
    ['sub_category_id' => 61, 'name' => 'Villa'],
];
$objects_and_offices = [
    ['sub_category_id' => 65, 'name' => 'Ofis'],
    ['sub_category_id' => 65, 'name' => 'Obyekt'],
    ['sub_category_id' => 65, 'name' => 'Mağaza'],
];












