<?php

$category = [
    ['name' => 'Uşaq aləmi'],
    ['name' => 'Şəxsi əşyalar'],
    ['name' => 'Ev və bağ üçün'],
    ['name' => 'Elektronika'],
    ['name' => 'Hobbi və asudə'],
    ['name' => 'Nəqliyyat'],
    ['name' => 'Daşınmaz əmlak'],
    ['name' => 'İş elanları'],
    ['name' => 'Heyvanlar'],
    ['name' => 'Xidmətlər və biznes'],
];

$sub_category = [
    ['category_id' => 1, 'name' => 'Avtomobil oturacaqları'],
    ['category_id' => 1, 'name' => 'Oyuncaqlar'],
    ['category_id' => 1, 'name' => 'Qidalanma üçün uşaq oturacaqları'],
    ['category_id' => 1, 'name' => 'Uşaq arabaları'],
    ['category_id' => 1, 'name' => 'Uşaq avtomobilləri'],
    ['category_id' => 1, 'name' => 'Uşaq çarpayıları və beşiklər'],
    ['category_id' => 1, 'name' => 'Uşaq daşıyıcıları'],
    ['category_id' => 1, 'name' => 'Uşaq geyimi'],
    ['category_id' => 1, 'name' => 'Uşaq mebeli'],
    ['category_id' => 1, 'name' => 'Uşaq qidası'],
    ['category_id' => 1, 'name' => 'Uşaq sürüşkənləri və oyun meydançaları'],
    ['category_id' => 1, 'name' => 'Manejlər'],
    ['category_id' => 1, 'name' => 'Məktəblilər üçün'],
    ['category_id' => 1, 'name' => 'Yürütəclər'],
    ['category_id' => 1, 'name' => 'Digər'],
    ['category_id' => 2,'name' => 'Geyim və ayaqqabılar'],
    ['category_id' => 2,'name' => 'Saat və zinət əşyaları'],
    ['category_id' => 2,'name' => 'Aksesuarlar'],
    ['category_id' => 2,'name' => 'Sağlamlıq və gözəllik'],
    ['category_id' => 2,'name' => 'İtmiş əşyalar'],
    ['category_id' => 2,'name' => 'Elektron siqaretlər və tütün qızdırıcıları'],
    ['category_id' => 3,'name' => 'Təmir və tikinti'],
    ['category_id' => 3,'name' => 'Mebellər'],
    ['category_id' => 3,'name' => 'Məişət texnikası'],
    ['category_id' => 3,'name' => 'Qab-qacaq və mətbəx ləvazimatları'],
    ['category_id' => 3,'name' => 'Ərzaq'],
    ['category_id' => 3,'name' => 'Bitkilər'],
    ['category_id' => 3,'name' => 'Xalçalar və aksesuarlar'],
    ['category_id' => 3,'name' => 'Ev tekstili'],
    ['category_id' => 3,'name' => 'Ev və bağ üçün işiqlandırma'],
    ['category_id' => 3,'name' => 'Dekor və interyer'],
    ['category_id' => 3,'name' => 'Bağ və bostan'],
    ['category_id' => 4,'name' => 'Audio və video'],
    ['category_id' => 4,'name' => 'Kompüter aksesuarları'],
    ['category_id' => 4,'name' => 'Oyunlar, pultlar və proqramlar'],
    ['category_id' => 4,'name' => 'Masaüstü kompüterlər'],
    ['category_id' => 4,'name' => 'Komponentlər və monitorlar'],
    ['category_id' => 4,'name' => 'Planşet və elektron kitablar'],
    ['category_id' => 4,'name' => 'Noutbuklar və Netbuklar'],
    ['category_id' => 4,'name' => 'Ofis avadanlığı və istehlak'],
    ['category_id' => 4,'name' => 'Telefonlar'],
    ['category_id' => 4,'name' => 'Nömrələr və SİM-kartlar'],
    ['category_id' => 4,'name' => 'Foto texnika'],
    ['category_id' => 4,'name' => 'Smart saat və qolbaqlar'],
    ['category_id' => 4,'name' => 'Televizorlar və aksesuarlar'],
    ['category_id' => 5,'name' => 'Biletlər və səyahət'],
    ['category_id' => 5,'name' => 'Velosipedlər'],
    ['category_id' => 5,'name' => 'Kolleksiya'],
    ['category_id' => 5,'name' => 'Musiqi alətləri'],
    ['category_id' => 5,'name' => 'İdman və asudə'],
    ['category_id' => 5,'name' => 'Kitab və jurnallar'],
    ['category_id' => 5,'name' => 'Ovçuluq və balıqçılıq'],
    ['category_id' => 5,'name' => 'Tanışlıq'],
    ['category_id' => 6,'name' => 'Avtomobillər'],
    ['category_id' => 6,'name' => 'Ehtiyat hissələri və aksesuarlar'],
    ['category_id' => 6,'name' => 'Motosikletlər və mopedlər'],
    ['category_id' => 6,'name' => 'Su nəqliyyatı'],
    ['category_id' => 6,'name' => 'Avtobuslar və xüsusi texnika'],
    ['category_id' => 6,'name' => 'Aqrotexnika'],
    ['category_id' => 7,'name' => 'Mənzillər'],
    ['category_id' => 7,'name' => 'Villalar, bağ evləri'],
    ['category_id' => 7,'name' => 'Torpaq'],
    ['category_id' => 7,'name' => 'Qarajlar'],
    ['category_id' => 7,'name' => 'Xaricdə əmlak'],
    ['category_id' => 7,'name' => 'byektlər və ofislər'],
    ['category_id' => 8,'name' => 'Vakansiyalar'],
    ['category_id' => 8,'name' => 'İş axtarıram'],
    ['category_id' => 9,'name' => 'İtlər'],
    ['category_id' => 9,'name' => 'Pişiklər'],
    ['category_id' => 9,'name' => 'Quşlar'],
    ['category_id' => 9,'name' => 'Akvarium və balıqlar'],
    ['category_id' => 9,'name' => 'K/t heyvanları'],
    ['category_id' => 9,'name' => 'Dovşanlar'],
    ['category_id' => 9,'name' => 'Heyvanlar üçün məhsullar'],
    ['category_id' => 9,'name' => 'Atlar'],
    ['category_id' => 9,'name' => 'Gəmiricilər'],
    ['category_id' => 9,'name' => 'Digər heyvanlar'],
    ['category_id' => 10,'name' => 'Avadanlığın icarəsi'],
    ['category_id' => 10,'name' => 'Biznes üçün avadanlıq'],
    ['category_id' => 10,'name' => 'Avadanlıqların quraşdırılması'],
    ['category_id' => 10,'name' => 'Avtoservis və diaqnostika'],
    ['category_id' => 10,'name' => 'Foto və video çəkiliş xidmətləri'],
    ['category_id' => 10,'name' => 'Gözəllik, sağlamlıq'],
    ['category_id' => 10,'name' => 'Hüquq xidmətləri'],
    ['category_id' => 10,'name' => 'IT, internet, telekom'],
    ['category_id' => 10,'name' => 'Mebel yığılması və təmiri'],
    ['category_id' => 10,'name' => 'Musiqi, əyləncə və tədbirlər'],
    ['category_id' => 10,'name' => 'Mühasibat xidmətləri'],
    ['category_id' => 10,'name' => 'Nəqliyyat və logistika'],
    ['category_id' => 10,'name' => 'Qidalanma, keyterinq'],
    ['category_id' => 10,'name' => 'Reklam, dizayn və poliqrafiya'],
    ['category_id' => 10,'name' => 'Sığorta xidmətləri'],
    ['category_id' => 10,'name' => 'Təlim, hazırlıq kursları'],
    ['category_id' => 10,'name' => 'Təmir və tikinti'],
    ['category_id' => 10,'name' => 'Təmizlik'],
    ['category_id' => 10,'name' => 'Tərcümə'],
    ['category_id' => 10,'name' => 'Texnika təmiri'],
    ['category_id' => 10,'name' => 'Tibbi xidmətlər'],
    ['category_id' => 10,'name' => 'Digər'],
];

$sub_category_type = [
    ['sub_category_id' => 8,'name' => 'Oğlan uşaq geyimi'],
    ['sub_category_id' => 8,'name' => 'Qız uşaq geyimi'],
    ['sub_category_id' => 13,'name' => 'Dəftərxana ləvazimatları'],
    ['sub_category_id' => 13,'name' => 'Dərsliklər'],
    ['sub_category_id' => 13,'name' => 'Məktəbli çantaları'],
    ['sub_category_id' => 13,'name' => 'Məktəbli forması'],
    ['sub_category_id' => 13,'name' => 'Yaradıcılıq ləvazimatları'],
    ['sub_category_id' => 16,'name' => 'Qadın geyimləri'],
    ['sub_category_id' => 16,'name' => 'Kişi geyimləri'],
    ['sub_category_id' => 17,'name' => 'Saatlar'],
    ['sub_category_id' => 17,'name' => 'Bijuteriya'],
    ['sub_category_id' => 17,'name' => 'Zərgərlik məmulatları'],
    ['sub_category_id' => 18,'name' => 'Açarlıqlar'],
    ['sub_category_id' => 18,'name' => 'Alışqanlar'],
    ['sub_category_id' => 18,'name' => 'Çamadanlar'],
    ['sub_category_id' => 18,'name' => 'Çantalar'],
    ['sub_category_id' => 18,'name' => 'Eynəklər'],
    ['sub_category_id' => 18,'name' => 'Eynəklər'],
    ['sub_category_id' => 18,'name' => 'Hədiyyə və suvenirlər'],
    ['sub_category_id' => 18,'name' => 'Kəmərlər'],
    ['sub_category_id' => 18,'name' => 'Portmone və pul kisələri'],
    ['sub_category_id' => 18,'name' => 'Təsbehlər'],
    ['sub_category_id' => 19,'name' => 'Arıqlamaq üçün vasitələr'],
    ['sub_category_id' => 19,'name' => 'Fenlər'],
    ['sub_category_id' => 19,'name' => 'Vücuda qulluq'],
    ['sub_category_id' => 19,'name' => 'Kosmetika'],
    ['sub_category_id' => 19,'name' => 'Kosmetoloji avadanlıqlar'],
    ['sub_category_id' => 19,'name' => 'Ətriyyat'],
    ['sub_category_id' => 19,'name' => 'Taraş vasitələri və epilyatorlar'],
    ['sub_category_id' => 21,'name' => 'Elektron siqaretlər'],
    ['sub_category_id' => 21,'name' => 'Tütün qızdırıcıları'],
    ['sub_category_id' => 21,'name' => 'Mayelər, kartriclər və stiklər'],
    ['sub_category_id' => 21,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 22,'name' => 'Buxarılar və qızdırıcılar'],
    ['sub_category_id' => 22,'name' => 'Elektrik malları'],
    ['sub_category_id' => 22,'name' => 'Pəncərələr, qapılar, eyvanlar'],
    ['sub_category_id' => 22,'name' => 'Santexnika və sauna'],
    ['sub_category_id' => 22,'name' => 'Tikinti materialları'],
    ['sub_category_id' => 22,'name' => 'Təmir və tikinti alətləri'],
    ['sub_category_id' => 22,'name' => 'Təmir və tikinti alətləri'],
    ['sub_category_id' => 23,'name' => 'Bufetlər və servantlar'],
    ['sub_category_id' => 23,'name' => 'Çarpayılar'],
    ['sub_category_id' => 23,'name' => 'Dəhliz mebeli'],
    ['sub_category_id' => 23,'name' => 'Divanlar və kreslolar'],
    ['sub_category_id' => 23,'name' => 'Dolablar və komodlar'],
    ['sub_category_id' => 23,'name' => 'Döşəklər'],
    ['sub_category_id' => 23,'name' => 'Jalüz və pərdələr'],
    ['sub_category_id' => 23,'name' => 'Masalar və oturacaqlar'],
    ['sub_category_id' => 23,'name' => 'Mətbəx mebeli'],
    ['sub_category_id' => 23,'name' => 'Ofis mebeli'],
    ['sub_category_id' => 23,'name' => 'Puflar və banketkalar'],
    ['sub_category_id' => 23,'name' => 'Qonaq otağı mebeli'],
    ['sub_category_id' => 23,'name' => 'Rəflər'],
    ['sub_category_id' => 23,'name' => 'Tumbalar'],
    ['sub_category_id' => 23,'name' => 'Yataq otağı mebeli'],
    ['sub_category_id' => 24,'name' => 'Aspiratorlar'],
    ['sub_category_id' => 24,'name' => 'Blenderlər, mikserlər, mətbəx kombaynları'],
    ['sub_category_id' => 24,'name' => 'Blinçik və vafli aparatı'],
    ['sub_category_id' => 24,'name' => 'Elektrik çaydanlar və termopotlar'],
    ['sub_category_id' => 24,'name' => 'Elektrik samovarlar'],
    ['sub_category_id' => 24,'name' => 'Ətçəkən maşınlar'],
    ['sub_category_id' => 24,'name' => 'Fritürlar'],
    ['sub_category_id' => 24,'name' => 'Kondisionerlər'],
    ['sub_category_id' => 24,'name' => 'Mikrodalğalı sobalar'],
    ['sub_category_id' => 24,'name' => 'Mini sobalar'],
    ['sub_category_id' => 24,'name' => 'Multibişiricilər'],
    ['sub_category_id' => 24,'name' => 'Paltaryuyanlar'],
    ['sub_category_id' => 24,'name' => 'Plitələr'],
    ['sub_category_id' => 24,'name' => 'Qabyuyanlar'],
    ['sub_category_id' => 24,'name' => 'Qəhvədəmləyənlər və qəhvə maşınları'],
    ['sub_category_id' => 24,'name' => 'Qızdırıcılar'],
    ['sub_category_id' => 24,'name' => 'Quraşdırılan sobalar'],
    ['sub_category_id' => 24,'name' => 'Samovarlar'],
    ['sub_category_id' => 24,'name' => 'Sərinkeşlər'],
    ['sub_category_id' => 24,'name' => 'Soyuducular'],
    ['sub_category_id' => 24,'name' => 'Su dispenserləri və kulerləri'],
    ['sub_category_id' => 24,'name' => 'Su filterləri və pompaları'],
    ['sub_category_id' => 24,'name' => 'Süd separatorları'],
    ['sub_category_id' => 24,'name' => 'Termometrlər'],
    ['sub_category_id' => 24,'name' => 'Tərəzilər'],
    ['sub_category_id' => 24,'name' => 'Tikiş maşınları'],
    ['sub_category_id' => 24,'name' => 'Tosterlər və çörəkbişirənlər'],
    ['sub_category_id' => 24,'name' => 'Tozsoranlar'],
    ['sub_category_id' => 24,'name' => 'Ütülər'],
    ['sub_category_id' => 24,'name' => 'Vakuum paketləyicilər'],
    ['sub_category_id' => 25,'name' => 'Badələr və qədəhlər'],
    ['sub_category_id' => 25,'name' => 'Boşqablar'],
    ['sub_category_id' => 25,'name' => 'Çay və qəhvə servizləri'],
    ['sub_category_id' => 25,'name' => 'Çaydanlar və qəhvədanlar'],
    ['sub_category_id' => 25,'name' => 'Fincanlar'],
    ['sub_category_id' => 25,'name' => 'Kasalar və salat qabları'],
    ['sub_category_id' => 25,'name' => 'Konfet, qənd və mürəbbə qabları'],
    ['sub_category_id' => 25,'name' => 'Külqabılar'],
    ['sub_category_id' => 25,'name' => 'Meyvə qabları'],
    ['sub_category_id' => 25,'name' => 'Mətbəx məhsulları'],
    ['sub_category_id' => 25,'name' => 'Nahar servizləri'],
    ['sub_category_id' => 25,'name' => 'Nəlbəkilər'],
    ['sub_category_id' => 25,'name' => 'Qazanlar və tavalar'],
    ['sub_category_id' => 25,'name' => 'Qrafinlər və dolçalar'],
    ['sub_category_id' => 25,'name' => 'Sinilər və altlıqlar'],
    ['sub_category_id' => 25,'name' => 'Şirniyyat və çərəz qabları'],
    ['sub_category_id' => 25,'name' => 'Şorba qabları'],
    ['sub_category_id' => 25,'name' => 'Stəkanlar'],
    ['sub_category_id' => 25,'name' => 'Süfrə ləvazimatları'],
    ['sub_category_id' => 28,'name' => 'Xalçalar'],
    ['sub_category_id' => 28,'name' => 'Kilimlər'],
    ['sub_category_id' => 28,'name' => 'Palazlar'],
    ['sub_category_id' => 28,'name' => 'Hamam və tualet üçün xalçalar'],
    ['sub_category_id' => 28,'name' => 'Qapı qabağı xalçalar'],
    ['sub_category_id' => 29,'name' => 'Yataq tekstili'],
    ['sub_category_id' => 29,'name' => 'Dəsmallar'],
    ['sub_category_id' => 29,'name' => 'Mətbəx üçün tekstil'],
    ['sub_category_id' => 29,'name' => 'Pledlər, örtüklər'],
    ['sub_category_id' => 29,'name' => 'Yastıqlar'],
    ['sub_category_id' => 29,'name' => 'Yorğanlar'],
    ['sub_category_id' => 29,'name' => 'Yorğanlar'],
    ['sub_category_id' => 30,'name' => 'Tavan və asma çilçıraqlar'],
    ['sub_category_id' => 30,'name' => 'Divar çıraqları'],
    ['sub_category_id' => 30,'name' => 'Yerüstü və masaüstü çıraqlar'],
    ['sub_category_id' => 30,'name' => 'Küçə çıraqları'],
    ['sub_category_id' => 30,'name' => 'Lampalar'],
    ['sub_category_id' => 30,'name' => 'Projektorlar'],
    ['sub_category_id' => 30,'name' => 'Spotlar və trek çıraqlar'],
    ['sub_category_id' => 30,'name' => 'İşıqlandırılma üçün aksessuarlar'],
    ['sub_category_id' => 31,'name' => 'Bayram dekoru və aksesuarları'],
    ['sub_category_id' => 31,'name' => 'Fotoçərçivələr'],
    ['sub_category_id' => 31,'name' => 'Güldanlar'],
    ['sub_category_id' => 31,'name' => 'Güzgülər'],
    ['sub_category_id' => 31,'name' => 'Heykəlciklər və fiqurlar'],
    ['sub_category_id' => 31,'name' => 'Pul daxılları və mücrülər'],
    ['sub_category_id' => 31,'name' => 'Qapılar üçün stoperlər'],
    ['sub_category_id' => 31,'name' => 'Rəsmlər və pannolar'],
    ['sub_category_id' => 31,'name' => 'Saatlar, zəngli saatlar'],
    ['sub_category_id' => 31,'name' => 'Şamlar və şamdanlar'],
    ['sub_category_id' => 31,'name' => 'Süni güllər və meyvələr'],
    ['sub_category_id' => 32,'name' => 'Bağ ləvazimatları'],
    ['sub_category_id' => 32,'name' => 'Manqallar və aksesuarlar'],
    ['sub_category_id' => 32,'name' => 'Otbiçənlər və trimmerlər'],
    ['sub_category_id' => 32,'name' => 'Qamaklar, yelləncəklər və şezlonqlar'],
    ['sub_category_id' => 32,'name' => 'Su çənləri'],
    ['sub_category_id' => 32,'name' => 'Su nasosları'],
    ['sub_category_id' => 32,'name' => 'Suvarma, suyun çəkilməsi və drenaj avadanlıqları'],
    ['sub_category_id' => 32,'name' => 'Toxumlar və gübrələr'],
    ['sub_category_id' => 33,'name' => 'Dinamik və sabvuferlər'],
    ['sub_category_id' => 33,'name' => 'MP3-pleyerlər'],
    ['sub_category_id' => 33,'name' => 'Musiqi mərkəzləri, maqnitolalar'],
    ['sub_category_id' => 33,'name' => 'Musiqi və kinolar'],
    ['sub_category_id' => 33,'name' => 'Proyektorlar'],
    ['sub_category_id' => 33,'name' => 'Qulaqlıqlar'],
    ['sub_category_id' => 33,'name' => 'Video, DVD və Blu-ray pleyerlər'],
    ['sub_category_id' => 33,'name' => 'Videokameralar'],
    ['sub_category_id' => 34,'name' => 'Kabellər və adapterlar'],
    ['sub_category_id' => 34,'name' => 'Klaviaturalar və kompüter siçanları'],
    ['sub_category_id' => 34,'name' => 'Modemlər və routerlar'],
    ['sub_category_id' => 34,'name' => 'UPS'],
    ['sub_category_id' => 34,'name' => 'USB flaş və yaddaş kartları'],
    ['sub_category_id' => 34,'name' => 'Web kameralar'],
    ['sub_category_id' => 34,'name' => 'Şəbəkə avadanlıqları'],
    ['sub_category_id' => 35,'name' => 'Oyun konsolları'],
    ['sub_category_id' => 35,'name' => 'Konsollar üçün oyunlar'],
    ['sub_category_id' => 35,'name' => 'Kompüter oyunları'],
    ['sub_category_id' => 35,'name' => 'Oyun hesabları'],
    ['sub_category_id' => 35,'name' => 'Proqramlar'],
    ['sub_category_id' => 35,'name' => 'Sosial şəbəkələrdə səhifələr'],
    ['sub_category_id' => 35,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 37,'name' => 'Ana plataları'],
    ['sub_category_id' => 37,'name' => 'Batareyalar'],
    ['sub_category_id' => 37,'name' => 'CD, DVD və Blu-ray'],
    ['sub_category_id' => 37,'name' => 'Keyslər və korpuslar'],
    ['sub_category_id' => 37,'name' => 'Kulerlər və ventilyatorlar'],
    ['sub_category_id' => 37,'name' => 'Monitorlar və ekranlar'],
    ['sub_category_id' => 37,'name' => 'Operativ yaddaş (RAM)'],
    ['sub_category_id' => 37,'name' => 'Prosessorlar (CPU))'],
    ['sub_category_id' => 37,'name' => 'Qida blokları'],
    ['sub_category_id' => 37,'name' => 'Sərt disklər (HDD, SSD)'],
    ['sub_category_id' => 37,'name' => 'Video kartlar'],
    ['sub_category_id' => 38,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 38,'name' => 'Planşetlər'],178
    ['sub_category_id' => 38,'name' => 'Elektron kitablar'],
    ['sub_category_id' => 39,'name' => 'Acer'],
    ['sub_category_id' => 39,'name' => 'Apple Macbook'],
    ['sub_category_id' => 39,'name' => 'Asus'],
    ['sub_category_id' => 39,'name' => 'Casper'],
    ['sub_category_id' => 39,'name' => 'Dell'],
    ['sub_category_id' => 39,'name' => 'Fujitsu-Siemens'],
    ['sub_category_id' => 39,'name' => 'HP'],
    ['sub_category_id' => 39,'name' => 'LG'],
    ['sub_category_id' => 39,'name' => 'Lenovo'],
    ['sub_category_id' => 39,'name' => 'MSI'],
    ['sub_category_id' => 39,'name' => 'Nexus'],
    ['sub_category_id' => 39,'name' => 'Samsung'],
    ['sub_category_id' => 39,'name' => 'Sony'],
    ['sub_category_id' => 39,'name' => 'Toshiba'],
    ['sub_category_id' => 39,'name' => 'Digər'],
    ['sub_category_id' => 39,'name' => 'Noutbuklar üçün aksessuarlar'],

    ['sub_category_id' => 40,'name' => 'Surət çıxardan və skanerlər'],
    ['sub_category_id' => 40,'name' => 'Printerlər'],
    ['sub_category_id' => 40,'name' => 'İstehlak və aksesuarlar'],
    ['sub_category_id' => 40,'name' => 'Digər'],

    ['sub_category_id' => 41,'name' => 'Acer'],
    ['sub_category_id' => 41,'name' => 'Aiek'],
    ['sub_category_id' => 41,'name' => 'Alcatel'],
    ['sub_category_id' => 41,'name' => 'Apple iPhone'],
    ['sub_category_id' => 41,'name' => 'Asus'],
    ['sub_category_id' => 41,'name' => 'Blackberry'],
    ['sub_category_id' => 41,'name' => 'Doogee'],
    ['sub_category_id' => 41,'name' => 'Dublikat'],
    ['sub_category_id' => 41,'name' => 'Ericsson'],
    ['sub_category_id' => 41,'name' => 'Fly'],
    ['sub_category_id' => 41,'name' => 'Hisense'],
    ['sub_category_id' => 41,'name' => 'Hoffmann'],
    ['sub_category_id' => 41,'name' => 'Homtom'],
    ['sub_category_id' => 41,'name' => 'Honor'],
    ['sub_category_id' => 41,'name' => 'Hope'],
    ['sub_category_id' => 41,'name' => 'HTC'],
    ['sub_category_id' => 41,'name' => 'Huawei'],
    ['sub_category_id' => 41,'name' => 'Jinga'],
    ['sub_category_id' => 41,'name' => 'Keneksi'],
    ['sub_category_id' => 41,'name' => 'Kgtel'],
    ['sub_category_id' => 41,'name' => 'Leagoo'],
    ['sub_category_id' => 41,'name' => 'Lenovo'],
    ['sub_category_id' => 41,'name' => 'LG'],
    ['sub_category_id' => 41,'name' => 'Meizu'],
    ['sub_category_id' => 41,'name' => 'Motorola'],
    ['sub_category_id' => 41,'name' => 'Nokia'],
    ['sub_category_id' => 41,'name' => 'OnePlus'],
    ['sub_category_id' => 41,'name' => 'Oukitel'],
    ['sub_category_id' => 41,'name' => 'Philips'],
    ['sub_category_id' => 41,'name' => 'Realme'],
    ['sub_category_id' => 41,'name' => 'Samsung'],
    ['sub_category_id' => 41,'name' => 'Siemens'],
    ['sub_category_id' => 41,'name' => 'Sony'],
    ['sub_category_id' => 41,'name' => 'Sony Ericsson'],
    ['sub_category_id' => 41,'name' => 'Umi'],
    ['sub_category_id' => 41,'name' => 'Vertu'],
    ['sub_category_id' => 41,'name' => 'Xiaomi'],
    ['sub_category_id' => 41,'name' => 'ZTE'],
    ['sub_category_id' => 41,'name' => 'Stasionar telefonlar'],
    ['sub_category_id' => 41,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 41,'name' => 'Ehtiyat hissələri'],
    ['sub_category_id' => 41,'name' => 'Ehtiyat hissələri'],

    ['sub_category_id' => 42,'name' => 'Azercell'],
    ['sub_category_id' => 42,'name' => 'Bakcell'],
    ['sub_category_id' => 42,'name' => 'Nar'],
    ['sub_category_id' => 42,'name' => 'Naxtel'],
    ['sub_category_id' => 42,'name' => 'Katel CDMA'],

    ['sub_category_id' => 43,'name' => 'Binokl və teleskoplar'],
    ['sub_category_id' => 43,'name' => 'Fotoaparatlar'],
    ['sub_category_id' => 43,'name' => 'Avadanlıq və aksesuarlar'],
    ['sub_category_id' => 43,'name' => 'Linzalar'],

    ['sub_category_id' => 44,'name' => 'Kəmərlər, aksesuarlar'],
    ['sub_category_id' => 44,'name' => 'Smart qolbaqlar'],
    ['sub_category_id' => 44,'name' => 'Smart saatlar'],

    ['sub_category_id' => 45,'name' => 'Televizorlar'],
    ['sub_category_id' => 45,'name' => 'Antenlər'],
    ['sub_category_id' => 45,'name' => 'Kronşteynlər'],
    ['sub_category_id' => 45,'name' => 'Pultlar'],
    ['sub_category_id' => 45,'name' => 'Televizor altlıqları və stendlər'],
    ['sub_category_id' => 45,'name' => 'Tünerlər'],

    ['sub_category_id' => 46,'name' => 'Konsertlər'],
    ['sub_category_id' => 46,'name' => 'Teatr'],
    ['sub_category_id' => 46,'name' => 'Səyahət'],
    ['sub_category_id' => 46,'name' => 'Səyahət'],

    ['sub_category_id' => 47,'name' => 'BMX'],
    ['sub_category_id' => 47,'name' => 'Dağ'],
    ['sub_category_id' => 47,'name' => 'Yol'],
    ['sub_category_id' => 47,'name' => 'Ehtiyat hissələri və aksesuarlar'],

    ['sub_category_id' => 48,'name' => 'Qramplastinka'],
    ['sub_category_id' => 48,'name' => 'Nişanlar, medallar, döş nişanları'],
    ['sub_category_id' => 48,'name' => 'Kolleksiya silahları'],
    ['sub_category_id' => 48,'name' => 'Markalar'],
    ['sub_category_id' => 48,'name' => 'Rəsm əsərləri'],
    ['sub_category_id' => 48,'name' => 'Modellər'],
    ['sub_category_id' => 48,'name' => 'Pullar'],
    ['sub_category_id' => 48,'name' => 'Əl işləri'],

    ['sub_category_id' => 49,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 49,'name' => 'Gitara və digər simlilər'],
    ['sub_category_id' => 49,'name' => 'Studia və konsertlər üçün'],
    ['sub_category_id' => 49,'name' => 'Pianino və digər klavişnilər'],
    ['sub_category_id' => 49,'name' => 'Skripkalar və digər yaylılar'],
    ['sub_category_id' => 49,'name' => 'Zərb alətləri'],

    ['sub_category_id' => 50,'name' => 'Bilyard və boulinq'],
    ['sub_category_id' => 50,'name' => 'Fitnes və trenajorlar'],
    ['sub_category_id' => 50,'name' => 'İdman qidası və əlavələr'],
    ['sub_category_id' => 50,'name' => 'Masaüstü oyunlar'],
    ['sub_category_id' => 50,'name' => 'Qış idman növləri'],
    ['sub_category_id' => 50,'name' => 'Roliklər, skeytbordlar, segway'],
    ['sub_category_id' => 50,'name' => 'Su idmanı və hovuzlar'],
    ['sub_category_id' => 50,'name' => 'Topla oyunlar'],
    ['sub_category_id' => 50,'name' => 'Təkbətək döyüş'],

    ['sub_category_id' => 51,'name' => 'Jurnallar'],
    ['sub_category_id' => 51,'name' => 'Kitablar'],

    ['sub_category_id' => 55,'name' => 'Aksesuarlar'],
    ['sub_category_id' => 55,'name' => 'Audio və video texnika'],
    ['sub_category_id' => 55,'name' => 'Avto kosmetika və kimya'],
    ['sub_category_id' => 55,'name' => 'Diaqnostika cihazları'],
    ['sub_category_id' => 55,'name' => 'Ehtiyat hissələri'],
    ['sub_category_id' => 55,'name' => 'GPS-naviqatorlar'],
    ['sub_category_id' => 55,'name' => 'Qeydiyyat nişanları'],
    ['sub_category_id' => 55,'name' => 'Şinlər, disklər və təkərlər'],
    ['sub_category_id' => 55,'name' => 'Siqnalizasiyalar'],
    ['sub_category_id' => 55,'name' => 'Videoqeydiyyatçılar'],

    ['sub_category_id' => 56,'name' => 'Hidrosikllar'],
    ['sub_category_id' => 56,'name' => 'Ehtiyat hissələri və aksesuarlar'],
    ['sub_category_id' => 56,'name' => 'Katerlər və yaxtalar'],
    ['sub_category_id' => 56,'name' => 'Mühərrikli qayıqlar'],
    ['sub_category_id' => 56,'name' => 'Hava qayıqları'],

    ['sub_category_id' => 59,'name' => 'Traktorlar'],
    ['sub_category_id' => 59,'name' => 'Kombaynlar'],
    ['sub_category_id' => 59,'name' => 'Köməkçi qoşqular'],
    ['sub_category_id' => 59,'name' => 'Kultivatorlar'],
    ['sub_category_id' => 59,'name' => 'Motobloklar'],
    ['sub_category_id' => 59,'name' => 'Digər texnika'],

    ['sub_category_id' => 64,'name' => 'Satış'],
    ['sub_category_id' => 64,'name' => 'Kirayə'],
    ['sub_category_id' => 64,'name' => 'İcarə'],

    ['sub_category_id' => 68,'name' => 'Akita-inu'],
    ['sub_category_id' => 68,'name' => 'Alabay'],
    ['sub_category_id' => 68,'name' => 'Alman ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Belçika ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Buldoq'],
    ['sub_category_id' => 68,'name' => 'Çau-çau'],
    ['sub_category_id' => 68,'name' => 'Cek Rassel Teryer'],
    ['sub_category_id' => 68,'name' => 'Çixuaxua'],
    ['sub_category_id' => 68,'name' => 'Doberman'],
    ['sub_category_id' => 68,'name' => 'Doq'],
    ['sub_category_id' => 68,'name' => 'Haski'],
    ['sub_category_id' => 68,'name' => 'Kane Korso'],
    ['sub_category_id' => 68,'name' => 'Kanqal'],
    ['sub_category_id' => 68,'name' => 'Koker spaniel'],
    ['sub_category_id' => 68,'name' => 'Labrador Retriver'],
    ['sub_category_id' => 68,'name' => 'Malta bolonkası'],
    ['sub_category_id' => 68,'name' => 'Mastif'],
    ['sub_category_id' => 68,'name' => 'Pekines'],
    ['sub_category_id' => 68,'name' => 'Pitbul'],
    ['sub_category_id' => 68,'name' => 'Pudel'],
    ['sub_category_id' => 68,'name' => 'Qafqaz ovçarkası'],
    ['sub_category_id' => 68,'name' => 'Qurdbasar'],
    ['sub_category_id' => 68,'name' => 'Rotveyler'],
    ['sub_category_id' => 68,'name' => 'Samoyed'],
    ['sub_category_id' => 68,'name' => 'Şpits'],
    ['sub_category_id' => 68,'name' => 'Yorkşir teryer'],

    ['sub_category_id' => 69,'name' => 'Avropa'],
    ['sub_category_id' => 69,'name' => 'Benqal'],
    ['sub_category_id' => 69,'name' => 'Britan'],
    ['sub_category_id' => 69,'name' => 'Pers'],
    ['sub_category_id' => 69,'name' => 'Siam'],
    ['sub_category_id' => 69,'name' => 'Sibir'],['sub_category_id' => 23,'name' => 'Çarpayılar'],
    ['sub_category_id' => 69,'name' => 'Şotland'],
    ['sub_category_id' => 69,'name' => 'Türk anqorı'],

    ['sub_category_id' => 74,'name' => 'Baytarlıq apteki'],
    ['sub_category_id' => 74,'name' => 'Bio-tualetlər və doldurucular'],
    ['sub_category_id' => 74,'name' => 'Daşıma konteynerləri və çantaları'],
    ['sub_category_id' => 74,'name' => 'Oyuncaqlar və dırnaq itiləyənlər'],
    ['sub_category_id' => 74,'name' => 'Qəfəslər və yuvalar'],
    ['sub_category_id' => 74,'name' => 'Qidalar'],
    ['sub_category_id' => 74,'name' => 'Qruminq və qulluq'],
    ['sub_category_id' => 74,'name' => 'Xaltalar və qayışlar'],
    ['sub_category_id' => 74,'name' => 'Yem və su qabları'],
    ['sub_category_id' => 74,'name' => 'Yəhərlər'],

    ['sub_category_id' => 79,'name' => 'Gözəllik salonu üçün'],
    ['sub_category_id' => 79,'name' => 'Mağaza üçün'],
    ['sub_category_id' => 79,'name' => 'Ofis üçün'],
    ['sub_category_id' => 79,'name' => 'Restoran üçün'],
    ['sub_category_id' => 79,'name' => 'Sənaye'],
    ['sub_category_id' => 79,'name' => 'Tibbi avadanlıqlar'],

    ['sub_category_id' => 94,'name' => 'Dam və çardaq'],
    ['sub_category_id' => 94,'name' => 'Darvaza və avtomatik qapıların sifarişi'],
    ['sub_category_id' => 94,'name' => 'Dekor, dizayn, smeta və planlama'],
    ['sub_category_id' => 94,'name' => 'Divar kağızı işləri'],
    ['sub_category_id' => 94,'name' => 'Döşəmə və tavan işləri'],
    ['sub_category_id' => 94,'name' => 'Dülgər işləri'],
    ['sub_category_id' => 94,'name' => 'Elektrik xidmətləri'],
    ['sub_category_id' => 94,'name' => 'Fasad işləri'],
    ['sub_category_id' => 94,'name' => 'Hazır konstruksiyalar'],
    ['sub_category_id' => 94,'name' => 'Kafel-plitə işləri'],
    ['sub_category_id' => 94,'name' => 'Landşaft işləri'],
    ['sub_category_id' => 94,'name' => 'Metal-qaynaq işləri'],
    ['sub_category_id' => 94,'name' => 'Məhəccər və arakəsmələrin sifarişi'],
    ['sub_category_id' => 94,'name' => 'Mərmər sifarişi və mərmər işləri'],
    ['sub_category_id' => 94,'name' => 'Pəncərə, qapı, eyvan'],
    ['sub_category_id' => 94,'name' => 'Təmir xidmətləri'],
    ['sub_category_id' => 94,'name' => 'Tikinti xidmətləri'],

    ['sub_category_id' => 97,'name' => 'Audio və video cihazların təmiri'],
    ['sub_category_id' => 97,'name' => 'Kombi və su qızdırıcılarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Kompüter və noutbukların təmiri'],
    ['sub_category_id' => 97,'name' => 'Məişət texnikalarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Musiqi alətlərinin təmiri'],
    ['sub_category_id' => 97,'name' => 'Oyun konsollarının təmiri'],
    ['sub_category_id' => 97,'name' => 'Printer təmiri və kartric doldurulması'],
    ['sub_category_id' => 97,'name' => 'Telefon və planşetlərin təmiri'],
    ['sub_category_id' => 97,'name' => 'Televizorların təmiri'],
    ['sub_category_id' => 97,'name' => 'Tikinti alət və avadanlıqları təmiri'],
];
$sub_category_type_one = [
    ['sub_category_type_id' => 1,'name' => 'Ayaqqabılar'],
    ['sub_category_type_id' => 1,'name' => 'Kostyum və pencəklər'],
    ['sub_category_type_id' => 1,'name' => 'Kombinezon və bodi'],
    ['sub_category_type_id' => 1,'name' => 'Köynək və T-shirt'],
    ['sub_category_type_id' => 1,'name' => 'Şalvarlar və şortlar'],
    ['sub_category_type_id' => 1,'name' => 'Üst geyimlər'],
    ['sub_category_type_id' => 2,'name' => 'Ayaqqabılar'],
    ['sub_category_type_id' => 2,'name' => 'Don və ətəklər'],
    ['sub_category_type_id' => 2,'name' => 'Kombinezon və bodi'],
    ['sub_category_type_id' => 2,'name' => 'Köynək və T-shirt'],
    ['sub_category_type_id' => 2,'name' => 'Şalvarlar və şortlar'],
    ['sub_category_type_id' => 2,'name' => 'Üst geyimlər'],
    ['sub_category_type_id' => 8,'name' => 'Üst geyimləri'],
    ['sub_category_type_id' => 8,'name' => 'Gələcək analar üçün'],
    ['sub_category_type_id' => 8,'name' => 'Kombinezonlar'],
    ['sub_category_type_id' => 8,'name' => 'Polo və futbolkalar'],
    ['sub_category_type_id' => 8,'name' => 'İdman geyimləri'],
    ['sub_category_type_id' => 8,'name' => 'Hicab və niqablar'],
    ['sub_category_type_id' => 8,'name' => 'İş geyimləri'],
    ['sub_category_type_id' => 8,'name' => 'Baş geyimi və əlcəklər'],
    ['sub_category_type_id' => 8,'name' => 'Ev geyimləri'],
    ['sub_category_type_id' => 8,'name' => 'Alt geyimləri'],
    ['sub_category_type_id' => 8,'name' => 'Ayaqqabılar'],
    ['sub_category_type_id' => 8,'name' => 'Don və ətəklər'],
    ['sub_category_type_id' => 8,'name' => 'Köynəklər'],
    ['sub_category_type_id' => 8,'name' => 'Pencək və kostyumlar'],
    ['sub_category_type_id' => 8,'name' => 'Şalvarlar və şortlar'],
    ['sub_category_type_id' => 8,'name' => 'Çimərlik geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Üst geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Baş geyimi və əlcəklər'],
    ['sub_category_type_id' => 9,'name' => 'Ev geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Alt geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Ayaqqabılar'],
    ['sub_category_type_id' => 9,'name' => 'Pencək və kostyumlar'],
    ['sub_category_type_id' => 9,'name' => 'Kofta və jaketlər'],
    ['sub_category_type_id' => 9,'name' => 'Polo və futbolkalar'],
    ['sub_category_type_id' => 9,'name' => 'Şalvarlar və şortlar'],
    ['sub_category_type_id' => 9,'name' => 'İdman geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Köynəklər'],
    ['sub_category_type_id' => 9,'name' => 'Kombinezonlar'],
    ['sub_category_type_id' => 9,'name' => 'İş geyimləri'],
    ['sub_category_type_id' => 9,'name' => 'Qalstuk və kəpənəklər'],
    ['sub_category_type_id' => 42,'name' => 'Birnəfərlik'],
    ['sub_category_type_id' => 42,'name' => 'İkinəfərlik'],
    ['sub_category_type_id' => 42,'name' => 'Qatlanan'],
    ['sub_category_type_id' => 42,'name' => 'Çarpayı hissələri'],
    ['sub_category_type_id' => 45,'name' => 'Dolablar'],
    ['sub_category_type_id' => 45,'name' => 'Komodlar'],
    ['sub_category_type_id' => 46,'name' => 'Hava döşəkləri'],
    ['sub_category_type_id' => 46,'name' => 'Adi döşəklər'],
    ['sub_category_type_id' => 46,'name' => 'Ortopedik döşəklər'],
    ['sub_category_type_id' => 110,'name' => 'Döşək üzləri'],
    ['sub_category_type_id' => 110,'name' => 'Yastıq üzləri'],
    ['sub_category_type_id' => 110,'name' => 'Yataq dəstləri'],
    ['sub_category_type_id' => 110,'name' => 'Yorğan üzləri'],
    ['sub_category_type_id' => 112,'name' => 'Süfrələr və salfetlər'],
    ['sub_category_type_id' => 112,'name' => 'Mətbəx dəsmalları'],
    ['sub_category_type_id' => 112,'name' => 'Önlüklər'],
    ['sub_category_type_id' => 112,'name' => 'Mətbəx əlcəkləri, tutacaqlar'],
    ['sub_category_type_id' => 114,'name' => 'Yastıqlar'],
    ['sub_category_type_id' => 114,'name' => 'Boyun üçün yastıqlar'],
    ['sub_category_type_id' => 114,'name' => 'Dekorativ yastıqlar'],
    ['sub_category_type_id' => 128,'name' => 'Masaüstü güzgülər'],
    ['sub_category_type_id' => 128,'name' => 'Divar güzgüləri'],
    ['sub_category_type_id' => 133,'name' => 'Masaüstü və yerüstü saatlar'],
    ['sub_category_type_id' => 133,'name' => 'Divar saatları'],
    ['sub_category_type_id' => 133,'name' => 'Elektron saatlar, zəngli saatla'],
    ['sub_category_type_id' => 136,'name' => 'Bağ alətləri dəsti'],
    ['sub_category_type_id' => 136,'name' => 'Bağban qayçıları və doğrayıcıları'],
    ['sub_category_type_id' => 136,'name' => 'Dırmıqlar'],
    ['sub_category_type_id' => 136,'name' => 'Kolkəsənlər'],
    ['sub_category_type_id' => 136,'name' => 'Kürəklər'],
    ['sub_category_type_id' => 136,'name' => 'Qiyməkeşlər və toxalar'],
    ['sub_category_type_id' => 136,'name' => 'Yabalar, külünglər və kultivatorlar'],
    ['sub_category_type_id' => 178,'name' => 'Acer'],75
    ['sub_category_type_id' => 178,'name' => 'Alcatel'],
    ['sub_category_type_id' => 178,'name' => 'Allview'],
    ['sub_category_type_id' => 178,'name' => 'Amazon'],
    ['sub_category_type_id' => 178,'name' => 'Archos'],
    ['sub_category_type_id' => 178,'name' => 'BlackBerry'],
    ['sub_category_type_id' => 178,'name' => 'BLU'],
    ['sub_category_type_id' => 178,'name' => 'BQ'],
    ['sub_category_type_id' => 178,'name' => 'Celkon'],
    ['sub_category_type_id' => 178,'name' => 'Dell'],
    ['sub_category_type_id' => 178,'name' => 'Google'],
    ['sub_category_type_id' => 178,'name' => 'Honor'],
    ['sub_category_type_id' => 178,'name' => 'HP'],
    ['sub_category_type_id' => 178,'name' => 'HTC'],
    ['sub_category_type_id' => 178,'name' => 'Huawei'],
    ['sub_category_type_id' => 178,'name' => 'Icemobile'],
    ['sub_category_type_id' => 178,'name' => 'Lenovo'],
    ['sub_category_type_id' => 178,'name' => 'LG'],
    ['sub_category_type_id' => 178,'name' => 'Maxwest'],
    ['sub_category_type_id' => 178,'name' => 'Micromax'],
    ['sub_category_type_id' => 178,'name' => 'Microsoft'],
    ['sub_category_type_id' => 178,'name' => 'Motorola'],
    ['sub_category_type_id' => 178,'name' => 'Nokia'],
    ['sub_category_type_id' => 178,'name' => 'Panasonic'],
    ['sub_category_type_id' => 178,'name' => 'Prestigio'],
    ['sub_category_type_id' => 178,'name' => 'QMobile'],
    ['sub_category_type_id' => 178,'name' => 'Samsung'],
    ['sub_category_type_id' => 178,'name' => 'Sony'],
    ['sub_category_type_id' => 178,'name' => 'TCL'],
    ['sub_category_type_id' => 178,'name' => 'Toshiba'],
    ['sub_category_type_id' => 178,'name' => 'Xiaomi'],
    ['sub_category_type_id' => 178,'name' => 'ZTE'],
];



$woman_clothing_type = [
    ['sub_category_type_one_id' => 13,'name' => 'Dublyonkalar'],
    ['sub_category_type_one_id' => 13,'name' => 'Gödəkcələr'],
    ['sub_category_type_one_id' => 13,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 13,'name' => 'Kürklər'],
    ['sub_category_type_one_id' => 13,'name' => 'Paltolar'],
    ['sub_category_type_one_id' => 13,'name' => 'Pelerin və ponço'],
    ['sub_category_type_one_id' => 13,'name' => 'Plaşlar'],

    ['sub_category_type_one_id' => 16,'name' => 'Futbolkalar'],
    ['sub_category_type_one_id' => 16,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 16,'name' => 'Polo'],
    ['sub_category_type_one_id' => 16,'name' => 'Top-koftalar'],

    ['sub_category_type_one_id' => 20,'name' => 'Əlcəklər'],
    ['sub_category_type_one_id' => 20,'name' => 'Kepkalar'],
    ['sub_category_type_one_id' => 20,'name' => 'Papaqlar'],
    ['sub_category_type_one_id' => 20,'name' => 'Şərflər'],
    ['sub_category_type_one_id' => 20,'name' => 'Şlyapalar'],
    ['sub_category_type_one_id' => 20,'name' => 'Yaylıqlar'],

    ['sub_category_type_one_id' => 21,'name' => 'Penüarlar'],
    ['sub_category_type_one_id' => 21,'name' => 'Pijamalar'],
    ['sub_category_type_one_id' => 21,'name' => 'Xələtlər'],

    ['sub_category_type_one_id' => 22,'name' => 'Alt paltarı'],
    ['sub_category_type_one_id' => 22,'name' => 'Bodi'],
    ['sub_category_type_one_id' => 22,'name' => 'Büstqalterlər'],
    ['sub_category_type_one_id' => 22,'name' => 'Corablar'],
    ['sub_category_type_one_id' => 22,'name' => 'Korsetlər'],

    ['sub_category_type_one_id' => 23,'name' => 'Yastıdaban ayaqqabılar'],
    ['sub_category_type_one_id' => 23,'name' => 'Çəkələklər'],
    ['sub_category_type_one_id' => 23,'name' => 'Çəkmələr'],
    ['sub_category_type_one_id' => 23,'name' => 'Ev ayaqqabıları'],
    ['sub_category_type_one_id' => 23,'name' => 'Hündürdaban ayaqqabılar'],
    ['sub_category_type_one_id' => 23,'name' => 'İdman ayaqqabıları'],
    ['sub_category_type_one_id' => 23,'name' => 'Kedlər'],
    ['sub_category_type_one_id' => 23,'name' => 'Uzunboğaz çəkmələr'],

    ['sub_category_type_one_id' => 24,'name' => 'Ətəklər'],
    ['sub_category_type_one_id' => 24,'name' => 'Gəlinliklər'],
    ['sub_category_type_one_id' => 24,'name' => 'Gündəlik donlar'],
    ['sub_category_type_one_id' => 24,'name' => 'Sarafanlar'],
    ['sub_category_type_one_id' => 24,'name' => 'Ziyafət donları'],

    ['sub_category_type_one_id' => 25,'name' => 'Cemperlər və sviterlər'],
    ['sub_category_type_one_id' => 25,'name' => 'Hudi və svitşotlar'],
    ['sub_category_type_one_id' => 25,'name' => 'Jaketlər'],
    ['sub_category_type_one_id' => 25,'name' => 'Koftalar və bluzlar'],
    ['sub_category_type_one_id' => 25,'name' => 'Uzunboğaz kofta'],

    ['sub_category_type_one_id' => 27,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 27,'name' => 'Kostyumlar'],
    ['sub_category_type_one_id' => 27,'name' => 'Pencəklər'],

    ['sub_category_type_one_id' => 28,'name' => 'Bricilər və kaprilər'],
    ['sub_category_type_one_id' => 28,'name' => 'Cinslər'],
    ['sub_category_type_one_id' => 28,'name' => 'Losinlər'],
    ['sub_category_type_one_id' => 28,'name' => 'Şalvarlar'],
    ['sub_category_type_one_id' => 28,'name' => 'Şortlar'],
];
$woman_clothing_type_size = [
    ['sub_category_type_one_id' => 13,'size' => '34 (XS) və daha az'],
    ['sub_category_type_one_id' => 13,'size' => '36 (S)'],
    ['sub_category_type_one_id' => 13,'size' => '38 (M)'],
    ['sub_category_type_one_id' => 13,'size' => '40 (L)'],
    ['sub_category_type_one_id' => 13,'size' => '42 (XL)'],
    ['sub_category_type_one_id' => 13,'size' => '44 (XXL)'],
    ['sub_category_type_one_id' => 13,'size' => '46 (XXXL) və daha çox'],
];
$woman_clothing_type_pants_size = [
    ['sub_category_type_one_id' => 28,'name' => '24 və daha az'],
    ['sub_category_type_one_id' => 28,'name' => '25'],
    ['sub_category_type_one_id' => 28,'name' => '26'],
    ['sub_category_type_one_id' => 28,'name' => '27'],
    ['sub_category_type_one_id' => 28,'name' => '28'],
    ['sub_category_type_one_id' => 28,'name' => '29'],
    ['sub_category_type_one_id' => 28,'name' => '30'],
    ['sub_category_type_one_id' => 28,'name' => '31'],
    ['sub_category_type_one_id' => 28,'name' => '32'],
    ['sub_category_type_one_id' => 28,'name' => '33'],
    ['sub_category_type_one_id' => 28,'name' => '34'],
    ['sub_category_type_one_id' => 28,'name' => '35'],
    ['sub_category_type_one_id' => 28,'name' => '36'],
    ['sub_category_type_one_id' => 28,'name' => '37'],
    ['sub_category_type_one_id' => 28,'name' => '38'],
    ['sub_category_type_one_id' => 28,'name' => '39'],
    ['sub_category_type_one_id' => 28,'name' => '40'],
    ['sub_category_type_one_id' => 28,'name' => '41'],
    ['sub_category_type_one_id' => 28,'name' => '42'],
    ['sub_category_type_one_id' => 28,'name' => '43'],
    ['sub_category_type_one_id' => 28,'name' => '44 və daha çox'],
];
$woman_clothing_type_shoe_size = [
    ['sub_category_type_one_id' => 23,'name' => '34 və daha az'],
    ['sub_category_type_one_id' => 23,'name' => '35'],
    ['sub_category_type_one_id' => 23,'name' => '36'],
    ['sub_category_type_one_id' => 23,'name' => '37'],
    ['sub_category_type_one_id' => 23,'name' => '38'],
    ['sub_category_type_one_id' => 23,'name' => '39'],
    ['sub_category_type_one_id' => 23,'name' => '40'],
    ['sub_category_type_one_id' => 23,'name' => '41'],
    ['sub_category_type_one_id' => 23,'name' => '42'],
    ['sub_category_type_one_id' => 23,'name' => '43'],
    ['sub_category_type_one_id' => 23,'name' => '43 və daha çox'],
];
$woman_clothing_brand = [
    ['sub_category_type_id' => 8,'name' => 'Adidas'],
    ['sub_category_type_id' => 8,'name' => 'AdL'],
    ['sub_category_type_id' => 8,'name' => 'Adolfo Dominguez'],
    ['sub_category_type_id' => 8,'name' => 'Armani Collezioni'],
    ['sub_category_type_id' => 8,'name' => 'Armani Exchange'],
    ['sub_category_type_id' => 8,'name' => 'Armani Jeans'],
    ['sub_category_type_id' => 8,'name' => 'Armonika'],
    ['sub_category_type_id' => 8,'name' => 'Asos'],
    ['sub_category_type_id' => 8,'name' => 'Banana Republic'],
    ['sub_category_type_id' => 8,'name' => 'Bebe'],
    ['sub_category_type_id' => 8,'name' => 'Bebe Plus'],
    ['sub_category_type_id' => 8,'name' => 'Benetton'],
    ['sub_category_type_id' => 8,'name' => 'Bershka'],
    ['sub_category_type_id' => 8,'name' => 'Burberry'],
    ['sub_category_type_id' => 8,'name' => 'Calvin Klein'],
    ['sub_category_type_id' => 8,'name' => 'Carolina Herrera'],
    ['sub_category_type_id' => 8,'name' => 'Chanel'],
    ['sub_category_type_id' => 8,'name' => 'Citizen'],
    ['sub_category_type_id' => 8,'name' => 'Colin'],
    ['sub_category_type_id' => 8,'name' => 'Collezione'],
    ['sub_category_type_id' => 8,'name' => 'Columbia'],
    ['sub_category_type_id' => 8,'name' => 'Cool Sexy'],
    ['sub_category_type_id' => 8,'name' => 'Dericlub'],
    ['sub_category_type_id' => 8,'name' => 'Dilvin'],
    ['sub_category_type_id' => 8,'name' => 'Dkny'],
    ['sub_category_type_id' => 8,'name' => 'Donna Karan'],
    ['sub_category_type_id' => 8,'name' => 'EA7'],
    ['sub_category_type_id' => 8,'name' => 'Elie Saab'],
    ['sub_category_type_id' => 8,'name' => 'Emporio Armani'],
    ['sub_category_type_id' => 8,'name' => 'Escada'],
    ['sub_category_type_id' => 8,'name' => 'Faik Sönmez'],
    ['sub_category_type_id' => 8,'name' => 'Faik Sönmez'],
    ['sub_category_type_id' => 8,'name' => 'Fila'],
    ['sub_category_type_id' => 8,'name' => 'Fullamoda'],
    ['sub_category_type_id' => 8,'name' => 'GAP'],
    ['sub_category_type_id' => 8,'name' => 'Guess'],
    ['sub_category_type_id' => 8,'name' => 'H&M'],
    ['sub_category_type_id' => 8,'name' => 'H&Helly Hansen'],
    ['sub_category_type_id' => 8,'name' => 'Hugo Boss'],
    ['sub_category_type_id' => 8,'name' => 'Hummel'],
    ['sub_category_type_id' => 8,'name' => 'İnci'],
    ['sub_category_type_id' => 8,'name' => 'İpekyol'],
    ['sub_category_type_id' => 8,'name' => 'Just Cavalli'],
    ['sub_category_type_id' => 8,'name' => 'Kappa'],
    ['sub_category_type_id' => 8,'name' => 'Karen Millen'],
    ['sub_category_type_id' => 8,'name' => 'Karl Lagerfeld'],
    ['sub_category_type_id' => 8,'name' => 'Kenzo'],
    ['sub_category_type_id' => 8,'name' => 'Kinetix'],
    ['sub_category_type_id' => 8,'name' => 'Koton'],
    ['sub_category_type_id' => 8,'name' => 'Lanvin'],
    ['sub_category_type_id' => 8,'name' => 'LC Waikiki'],
    ['sub_category_type_id' => 8,'name' => "Levi's"],
    ['sub_category_type_id' => 8,'name' => 'Loft'],
    ['sub_category_type_id' => 8,'name' => 'Ltb'],
    ['sub_category_type_id' => 8,'name' => 'Lumberjack'],
    ['sub_category_type_id' => 8,'name' => 'Mango'],
    ['sub_category_type_id' => 8,'name' => 'Marks & Spencer'],
    ['sub_category_type_id' => 8,'name' => 'Massimo Dutti'],
    ['sub_category_type_id' => 8,'name' => 'Mavi'],
    ['sub_category_type_id' => 8,'name' => 'Michael Kors'],
    ['sub_category_type_id' => 8,'name' => 'Miss Ipekyol'],
    ['sub_category_type_id' => 8,'name' => 'Moncler'],
    ['sub_category_type_id' => 8,'name' => 'Nike'],
    ['sub_category_type_id' => 8,'name' => 'Olalook'],
    ['sub_category_type_id' => 8,'name' => 'Oysho'],
    ['sub_category_type_id' => 8,'name' => 'Penti'],
    ['sub_category_type_id' => 8,'name' => 'Pierre Cardin'],
    ['sub_category_type_id' => 8,'name' => 'Pimkie'],
    ['sub_category_type_id' => 8,'name' => 'Pull & Bear'],
    ['sub_category_type_id' => 8,'name' => 'Puma'],
    ['sub_category_type_id' => 8,'name' => 'Reebok'],
    ['sub_category_type_id' => 8,'name' => 'Robin'],
    ['sub_category_type_id' => 8,'name' => 'Sisley'],
    ['sub_category_type_id' => 8,'name' => 'Stradivarius'],
    ['sub_category_type_id' => 8,'name' => 'The North Face'],
    ['sub_category_type_id' => 8,'name' => 'Tiffany'],
    ['sub_category_type_id' => 8,'name' => 'Tom Ford'],
    ['sub_category_type_id' => 8,'name' => 'Tommy Hilfiger'],
    ['sub_category_type_id' => 8,'name' => 'Tonny Black'],
    ['sub_category_type_id' => 8,'name' => 'Trendyol Modest'],
    ['sub_category_type_id' => 8,'name' => 'Trendyolmilla'],
    ['sub_category_type_id' => 8,'name' => 'Twist'],
    ['sub_category_type_id' => 8,'name' => 'US Polo Assn'],
    ['sub_category_type_id' => 8,'name' => 'Vans'],
    ['sub_category_type_id' => 8,'name' => 'Vero Moda'],
    ['sub_category_type_id' => 8,'name' => 'Versace'],
    ['sub_category_type_id' => 8,'name' => 'Waggon'],
    ['sub_category_type_id' => 8,'name' => 'Wilson'],
    ['sub_category_type_id' => 8,'name' => 'XHAN'],
    ['sub_category_type_id' => 8,'name' => 'Zara']
];


$man_clothing_type = [
    ['sub_category_type_one_id' => 29,'name' => 'Dublyonkalar'],
    ['sub_category_type_one_id' => 29,'name' => 'Gödəkcələr'],
    ['sub_category_type_one_id' => 29,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 29,'name' => 'Paltolar'],
    ['sub_category_type_one_id' => 29,'name' => 'Plaşlar'],

    ['sub_category_type_one_id' => 30,'name' => 'Əlcəklər'],
    ['sub_category_type_one_id' => 30,'name' => 'Kepkalar və beysbolkalar'],
    ['sub_category_type_one_id' => 30,'name' => 'Papaqlar'],
    ['sub_category_type_one_id' => 30,'name' => 'Şərflər'],
    ['sub_category_type_one_id' => 30,'name' => 'Şlyapalar'],

    ['sub_category_type_one_id' => 31,'name' => 'Pijamalar'],
    ['sub_category_type_one_id' => 31,'name' => 'Xələtlər'],

    ['sub_category_type_one_id' => 32,'name' => 'Alt paltarı'],
    ['sub_category_type_one_id' => 32,'name' => 'Corablar'],
    ['sub_category_type_one_id' => 32,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 32,'name' => 'Termal alt paltarları'],

    ['sub_category_type_one_id' => 33,'name' => 'Çəkələklər'],
    ['sub_category_type_one_id' => 33,'name' => 'Çəkmələr'],
    ['sub_category_type_one_id' => 33,'name' => 'Ev ayaqqabıları'],
    ['sub_category_type_one_id' => 33,'name' => 'İdman ayaqqabıları'],
    ['sub_category_type_one_id' => 33,'name' => 'Kedlər'],
    ['sub_category_type_one_id' => 33,'name' => 'Klassik ayaqqabılar'],
    ['sub_category_type_one_id' => 33,'name' => 'Mokasinlər'],
    ['sub_category_type_one_id' => 33,'name' => 'Səndəllər'],
    ['sub_category_type_one_id' => 33,'name' => 'Uzunboğaz çəkmələr'],

    ['sub_category_type_one_id' => 34,'name' => 'Jiletlər'],
    ['sub_category_type_one_id' => 34,'name' => 'Kostyumlar'],
    ['sub_category_type_one_id' => 34,'name' => 'Pencəklər'],

    ['sub_category_type_one_id' => 35,'name' => 'Cemperlər və sviterlər'],
    ['sub_category_type_one_id' => 35,'name' => 'Hudi və svitşotlar'],
    ['sub_category_type_one_id' => 35,'name' => 'Jaketlər'],
    ['sub_category_type_one_id' => 35,'name' => 'Koftalar'],
    ['sub_category_type_one_id' => 35,'name' => 'Uzunboğaz koftalar'],

    ['sub_category_type_one_id' => 36,'name' => 'Futbolkalar'],
    ['sub_category_type_one_id' => 36,'name' => 'Maykalar'],
    ['sub_category_type_one_id' => 36,'name' => 'Polo'],

    ['sub_category_type_one_id' => 37,'name' => 'Cinslər'],
    ['sub_category_type_one_id' => 37,'name' => 'Şalvarlar'],
    ['sub_category_type_one_id' => 37,'name' => 'Şortlar'],
    ['sub_category_type_one_id' => 37,'name' => 'Şortlar'],
];
$man_clothing_type_size = [
    ['sub_category_type_one_id' => 34,'size' => '34 (XS) və daha az'],
    ['sub_category_type_one_id' => 34,'size' => '36 (S)'],
    ['sub_category_type_one_id' => 34,'size' => '38 (M)'],
    ['sub_category_type_one_id' => 34,'size' => '40 (L)'],
    ['sub_category_type_one_id' => 34,'size' => '42 (XL)'],
    ['sub_category_type_one_id' => 34,'size' => '44 (XXL)'],
    ['sub_category_type_one_id' => 34,'size' => '48 (4XL) və daha çox'],
];
$man_clothing_type_pants_size = [
    ['sub_category_type_one_id' => 37,'name' => '28 və daha az'],
    ['sub_category_type_one_id' => 37,'name' => '29'],
    ['sub_category_type_one_id' => 37,'name' => '30'],
    ['sub_category_type_one_id' => 37,'name' => '31'],
    ['sub_category_type_one_id' => 37,'name' => '32'],
    ['sub_category_type_one_id' => 37,'name' => '33'],
    ['sub_category_type_one_id' => 37,'name' => '34'],
    ['sub_category_type_one_id' => 37,'name' => '35'],
    ['sub_category_type_one_id' => 37,'name' => '36'],
    ['sub_category_type_one_id' => 37,'name' => '37'],
    ['sub_category_type_one_id' => 37,'name' => '38'],
    ['sub_category_type_one_id' => 37,'name' => '39'],
    ['sub_category_type_one_id' => 37,'name' => '40'],
    ['sub_category_type_one_id' => 37,'name' => '41'],
    ['sub_category_type_one_id' => 37,'name' => '42'],
    ['sub_category_type_one_id' => 37,'name' => '43'],
    ['sub_category_type_one_id' => 37,'name' => '44'],
    ['sub_category_type_one_id' => 37,'name' => '45'],
    ['sub_category_type_one_id' => 37,'name' => '46'],
    ['sub_category_type_one_id' => 37,'name' => '47'],
    ['sub_category_type_one_id' => 37,'name' => '48'],
    ['sub_category_type_one_id' => 37,'name' => '49'],
    ['sub_category_type_one_id' => 37,'name' => '50 və daha çox'],
];
$man_clothing_type_shoe_size = [
    ['sub_category_type_one_id' => 33,'name' => '36 və daha az'],
    ['sub_category_type_one_id' => 33,'name' => '37'],
    ['sub_category_type_one_id' => 33,'name' => '38'],
    ['sub_category_type_one_id' => 33,'name' => '39'],
    ['sub_category_type_one_id' => 33,'name' => '40'],
    ['sub_category_type_one_id' => 33,'name' => '41'],
    ['sub_category_type_one_id' => 33,'name' => '42'],
    ['sub_category_type_one_id' => 33,'name' => '43'],
    ['sub_category_type_one_id' => 33,'name' => '44'],
    ['sub_category_type_one_id' => 33,'name' => '45'],
    ['sub_category_type_one_id' => 33,'name' => '46 və daha çox'],
];
$man_clothing_brand = [
    ['sub_category_type_id' => 9,'name' => 'Baldinini'],
    ['sub_category_type_id' => 9,'name' => 'Adidas'],
    ['sub_category_type_id' => 9,'name' => 'Armani'],
    ['sub_category_type_id' => 9,'name' => 'Asos'],
    ['sub_category_type_id' => 9,'name' => 'Avva'],
    ['sub_category_type_id' => 9,'name' => 'Bershka'],
    ['sub_category_type_id' => 9,'name' => 'Calvin Klein'],
    ['sub_category_type_id' => 9,'name' => 'Colin’s'],
    ['sub_category_type_id' => 9,'name' => 'Collezione'],
    ['sub_category_type_id' => 9,'name' => 'Defacto'],
    ['sub_category_type_id' => 9,'name' => 'Derimod'],
    ['sub_category_type_id' => 9,'name' => 'Dior'],
    ['sub_category_type_id' => 9,'name' => 'Dsquared'],
    ['sub_category_type_id' => 9,'name' => 'DSquared2'],
    ['sub_category_type_id' => 9,'name' => 'Emporio Armani'],
    ['sub_category_type_id' => 9,'name' => 'ETRO'],
    ['sub_category_type_id' => 9,'name' => 'Fendi'],
    ['sub_category_type_id' => 9,'name' => 'Fullamoda'],
    ['sub_category_type_id' => 9,'name' => 'Galvanni'],
    ['sub_category_type_id' => 9,'name' => 'Gucci'],
    ['sub_category_type_id' => 9,'name' => 'H&M'],
    ['sub_category_type_id' => 9,'name' => 'Hatemoğlu'],
    ['sub_category_type_id' => 9,'name' => 'Hugo Boss'],
    ['sub_category_type_id' => 9,'name' => 'Hummel'],
    ['sub_category_type_id' => 9,'name' => 'Hunter'],
    ['sub_category_type_id' => 9,'name' => 'Jack Jones'],
    ['sub_category_type_id' => 9,'name' => 'Kappa'],
    ['sub_category_type_id' => 9,'name' => 'Kenzo'],
    ['sub_category_type_id' => 9,'name' => 'Kiğılı'],
    ['sub_category_type_id' => 9,'name' => 'Kinetix'],
    ['sub_category_type_id' => 9,'name' => 'Koton'],
    ['sub_category_type_id' => 9,'name' => 'Lacoste'],
    ['sub_category_type_id' => 9,'name' => 'LC Waikiki'],
    ['sub_category_type_id' => 9,'name' => "Levi's"],
    ['sub_category_type_id' => 9,'name' => "Ltb"],
    ['sub_category_type_id' => 9,'name' => "Lumberjack"],
    ['sub_category_type_id' => 9,'name' => "Mango"],
    ['sub_category_type_id' => 9,'name' => "Massimo Dutti"],
    ['sub_category_type_id' => 9,'name' => "Mavi"],
    ['sub_category_type_id' => 9,'name' => "Milan"],
    ['sub_category_type_id' => 9,'name' => "Moncler"],
    ['sub_category_type_id' => 9,'name' => "New Balance"],
    ['sub_category_type_id' => 9,'name' => "Nike"],
    ['sub_category_type_id' => 9,'name' => "Philipp Plein"],
    ['sub_category_type_id' => 9,'name' => "Pierre Cardin"],
    ['sub_category_type_id' => 9,'name' => "Prada"],
    ['sub_category_type_id' => 9,'name' => "Puma"],
    ['sub_category_type_id' => 9,'name' => "Ramsey"],
    ['sub_category_type_id' => 9,'name' => "Reebok"],
    ['sub_category_type_id' => 9,'name' => "Rodi Jeans"],
    ['sub_category_type_id' => 9,'name' => "Süvari"],
    ['sub_category_type_id' => 9,'name' => "Ted Baker"],
    ['sub_category_type_id' => 9,'name' => "The North Face"],
    ['sub_category_type_id' => 9,'name' => "Timberland"],
    ['sub_category_type_id' => 9,'name' => "Tommy Hilfiger"],
    ['sub_category_type_id' => 9,'name' => "Trendyol Man"],
    ['sub_category_type_id' => 9,'name' => "US Polo Assn"],
    ['sub_category_type_id' => 9,'name' => "Versace"],
    ['sub_category_type_id' => 9,'name' => "XHAN"],
    ['sub_category_type_id' => 9,'name' => "Zara"],
    ['sub_category_type_id' => 9,'name' => "Zara"],
];


$season = [
    ['sub_category_id' => 16, 'name' => 'Yarım mövsüm'],
    ['sub_category_id' => 16, 'name' => 'Yay'],
    ['sub_category_id' => 16, 'name' => 'Qış']
];

$child_suits_and_jacket_size = [
    ['sub_category_type_one_id' => 2,'size' => '0-3 ay'],
    ['sub_category_type_one_id' => 2,'size' => '3-6 ay'],
    ['sub_category_type_one_id' => 2,'size' => '6-9 ay'],
    ['sub_category_type_one_id' => 2,'size' => '9-12 ay'],
    ['sub_category_type_one_id' => 2,'size' => '12-18 ay'],
    ['sub_category_type_one_id' => 2,'size' => '18-24 ay'],
    ['sub_category_type_one_id' => 2,'size' => '2-3 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '3-4 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '4-5 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '5-6 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '7-8 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '8-9 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '9-10 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '10-11 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '11-12 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '12-13 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '13-14 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '14-15 yaş'],
    ['sub_category_type_one_id' => 2,'size' => '15-16 yaş'],
];
$child_shoe_size = [
    ['size' => 16],
    ['size' => 17],
    ['size' => 18],
    ['size' => 19],
    ['size' => 20],
    ['size' => 21],
    ['size' => 22],
    ['size' => 23],
    ['size' => 24],
    ['size' => 25],
    ['size' => 26],
    ['size' => 27],
    ['size' => 28],
    ['size' => 29],
    ['size' => 30],
    ['size' => 31],
    ['size' => 32],
    ['size' => 33],
    ['size' => 34],
    ['size' => 35],
    ['size' => 36],
];


$color = [
    ['name' => 'Ağ'],
    ['name' => 'Bej'],
    ['name' => 'Bənövşəyi'],
    ['name' => 'Boz'],
    ['name' => 'Çəhrayı'],
    ['name' => 'Göy'],
    ['name' => 'Gümüşü'],
    ['name' => 'Mavi'],
    ['name' => 'Narıncı'],
    ['name' => 'Qara'],
    ['name' => 'Qəhvəyi'],
    ['name' => 'Qırmızı'],
    ['name' => 'Qızılı'],
    ['name' => 'Sarı'],
    ['name' => 'Tünd qırmızı'],
    ['name' => 'Yaş Asfalt'],
    ['name' => 'Yaşıl'],
];

$fuel_type = [
    ['name' => 'Benzin'],
    ['name' => 'Dizel'],
    ['name' => 'Qaz'],
    ['name' => 'Elektro'],
    ['name' => 'Hibrid'],
];
$transmission = [
    ['name' => 'Mexaniki'],
    ['name' => 'Avtomat'],
    ['name' => 'Robotlaşdırılmış'],
    ['name' => 'Variator'],
];
$body_type = [
    ['name' => 'Sedan'],
    ['name' => 'Universal'],
    ['name' => 'Hetçbek'],
    ['name' => 'Kupe'],
    ['name' => 'Rodster'],
    ['name' => 'Mikroavtobus'],
    ['name' => 'Pikap'],
    ['name' => 'Limuzin'],
    ['name' => 'Krosover'],
    ['name' => 'Miniven'],
    ['name' => 'Kabriolet'],
    ['name' => 'Offroader'],
];
$motorbikeType = [
    ['subcategory_id' => 57,'name' => 'Baqqi'],
    ['subcategory_id' => 57,'name' => 'Kvadrosikllar'],
    ['subcategory_id' => 57,'name' => 'Mopedlər'],
    ['subcategory_id' => 57,'name' => 'Motosikletlər'],
    ['subcategory_id' => 57,'name' => 'Motosikletlər'],
    ['subcategory_id' => 57,'name' => 'Skuterlər'],
];
$motorbikeMarka = [
    ['subcategory_id' => 57,'name' => 'ABM'],
    ['subcategory_id' => 57,'name' => 'AMC'],
    ['subcategory_id' => 57,'name' => 'Aprilia'],
    ['subcategory_id' => 57,'name' => 'Arctic Cat'],
    ['subcategory_id' => 57,'name' => 'ATV'],
    ['subcategory_id' => 57,'name' => 'Baotian'],
    ['subcategory_id' => 57,'name' => 'BMW'],
    ['subcategory_id' => 57,'name' => 'Buell'],
    ['subcategory_id' => 57,'name' => 'Can-Am'],
    ['subcategory_id' => 57,'name' => 'CFMOTO'],
    ['subcategory_id' => 57,'name' => 'Changan'],
    ['subcategory_id' => 57,'name' => 'Chery'],
    ['subcategory_id' => 57,'name' => 'Chevrolet'],
    ['subcategory_id' => 57,'name' => 'Chituma'],
    ['subcategory_id' => 57,'name' => 'CZ'],
    ['subcategory_id' => 57,'name' => 'Dayun'],
    ['subcategory_id' => 57,'name' => 'Dnepr'],
    ['subcategory_id' => 57,'name' => 'Ducati'],
    ['subcategory_id' => 57,'name' => 'Foton'],
    ['subcategory_id' => 57,'name' => 'Gabro'],
    ['subcategory_id' => 57,'name' => 'Geely'],
    ['subcategory_id' => 57,'name' => 'Gilera'],
    ['subcategory_id' => 57,'name' => 'Great Wall'],
    ['subcategory_id' => 57,'name' => 'GUSİDE'],
    ['subcategory_id' => 57,'name' => 'Hamtaz'],
    ['subcategory_id' => 57,'name' => 'Haojue'],
    ['subcategory_id' => 57,'name' => 'Harley-Davidson'],
    ['subcategory_id' => 57,'name' => 'Haval'],
    ['subcategory_id' => 57,'name' => 'Hisun - motocars'],
    ['subcategory_id' => 57,'name' => 'Honda'],
    ['subcategory_id' => 57,'name' => 'Huzhou'],
    ['subcategory_id' => 57,'name' => 'Hyosung'],
    ['subcategory_id' => 57,'name' => 'Hyundai'],
    ['subcategory_id' => 57,'name' => 'IJ'],
    ['subcategory_id' => 57,'name' => 'Infiniti'],
    ['subcategory_id' => 57,'name' => 'Jawa'],
    ['subcategory_id' => 57,'name' => 'Jiajue'],
    ['subcategory_id' => 57,'name' => 'Jinan'],
    ['subcategory_id' => 57,'name' => 'Jinbei'],
    ['subcategory_id' => 57,'name' => 'Jonway'],
    ['subcategory_id' => 57,'name' => 'Kawasaki'],
    ['subcategory_id' => 57,'name' => 'Kayo'],
    ['subcategory_id' => 57,'name' => 'Kia'],
    ['subcategory_id' => 57,'name' => 'Kinroad'],
    ['subcategory_id' => 57,'name' => 'KTM'],
    ['subcategory_id' => 57,'name' => 'LADA (VAZ)'],
    ['subcategory_id' => 57,'name' => 'Land Rover'],
    ['subcategory_id' => 57,'name' => 'Lexus'],
    ['subcategory_id' => 57,'name' => 'Marseille'],
    ['subcategory_id' => 57,'name' => 'Mazda'],
    ['subcategory_id' => 57,'name' => 'Megelli'],
    ['subcategory_id' => 57,'name' => 'Mercedes'],
    ['subcategory_id' => 57,'name' => 'Minsk'],
    ['subcategory_id' => 57,'name' => 'Mitsubishi'],
    ['subcategory_id' => 57,'name' => 'Mondial'],
    ['subcategory_id' => 57,'name' => 'Muravey'],
    ['subcategory_id' => 57,'name' => 'MV Agusta'],
    ['subcategory_id' => 57,'name' => 'Neoplan'],
    ['subcategory_id' => 57,'name' => 'Neptun'],
    ['subcategory_id' => 57,'name' => 'Nissan'],
    ['subcategory_id' => 57,'name' => 'NIU'],
    ['subcategory_id' => 57,'name' => 'Opel'],
    ['subcategory_id' => 57,'name' => 'Parvaz'],
    ['subcategory_id' => 57,'name' => 'Piaggio'],
    ['subcategory_id' => 57,'name' => 'Polaris'],
    ['subcategory_id' => 57,'name' => 'QAZ'],
    ['subcategory_id' => 57,'name' => 'Rialli'],
    ['subcategory_id' => 57,'name' => 'Riga'],
    ['subcategory_id' => 57,'name' => 'Shineray'],
    ['subcategory_id' => 57,'name' => 'Skyline'],
    ['subcategory_id' => 57,'name' => 'Sport'],
    ['subcategory_id' => 57,'name' => 'Suzuki'],
    ['subcategory_id' => 57,'name' => 'SYM'],
    ['subcategory_id' => 57,'name' => 'Toyota'],
    ['subcategory_id' => 57,'name' => 'Triumph'],
    ['subcategory_id' => 57,'name' => 'UAZ'],
    ['subcategory_id' => 57,'name' => 'Ural'],
    ['subcategory_id' => 57,'name' => 'Vespa'],
    ['subcategory_id' => 57,'name' => 'Volkswagen'],
    ['subcategory_id' => 57,'name' => 'Vosxod'],
    ['subcategory_id' => 57,'name' => 'Vyatka'],
    ['subcategory_id' => 57,'name' => 'Yadea'],
    ['subcategory_id' => 57,'name' => 'Yamaha'],
    ['subcategory_id' => 57,'name' => 'Zongshen'],
    ['subcategory_id' => 57,'name' => 'Zontes'],
];
$busType = [
    ['sub_category_id' => 58, 'name' => 'Avtobuslar'],
    ['sub_category_id' => 58, 'name' => 'Avtokranlar'],
    ['sub_category_id' => 58, 'name' => 'Yük maşınları'],
    ['sub_category_id' => 58, 'name' => 'Qoşqular'],
    ['sub_category_id' => 58, 'name' => 'Tikinti texnikası'],
];
$bus_marka = [
    ['sub_category_id' => 58, 'name' => 'AMMANN'],
    ['sub_category_id' => 58, 'name' => 'Belarus'],
    ['sub_category_id' => 58, 'name' => 'Bobcat'],
    ['sub_category_id' => 58, 'name' => 'Bomag'],
    ['sub_category_id' => 58, 'name' => 'Cat'],
    ['sub_category_id' => 58, 'name' => 'Daf'],
    ['sub_category_id' => 58, 'name' => 'DongFeng'],
    ['sub_category_id' => 58, 'name' => 'FAW'],
    ['sub_category_id' => 58, 'name' => 'Fiat'],
    ['sub_category_id' => 58, 'name' => 'Ford'],
    ['sub_category_id' => 58, 'name' => 'Foton'],
    ['sub_category_id' => 58, 'name' => 'Hidromek'],
    ['sub_category_id' => 58, 'name' => 'Hitachi'],
    ['sub_category_id' => 58, 'name' => 'Howo'],
    ['sub_category_id' => 58, 'name' => 'Hyundai'],
    ['sub_category_id' => 58, 'name' => 'Isuzu'],
    ['sub_category_id' => 58, 'name' => 'Iveco'],
    ['sub_category_id' => 58, 'name' => 'JAC'],
    ['sub_category_id' => 58, 'name' => 'JCB'],
    ['sub_category_id' => 58, 'name' => 'Jungheinrich'],
    ['sub_category_id' => 58, 'name' => 'Kamaz'],
    ['sub_category_id' => 58, 'name' => 'Komatsu'],
    ['sub_category_id' => 58, 'name' => 'Kraz'],
    ['sub_category_id' => 58, 'name' => 'Liebherr'],
    ['sub_category_id' => 58, 'name' => 'Linde'],
    ['sub_category_id' => 58, 'name' => 'MAN'],
    ['sub_category_id' => 58, 'name' => 'Mack'],
    ['sub_category_id' => 58, 'name' => 'Maz'],
    ['sub_category_id' => 58, 'name' => 'Mercedes Benz'],
    ['sub_category_id' => 58, 'name' => 'Mitsubishi'],
    ['sub_category_id' => 58, 'name' => 'Otocar'],
    ['sub_category_id' => 58, 'name' => 'Qazel'],
    ['sub_category_id' => 58, 'name' => 'RAF'],
    ['sub_category_id' => 58, 'name' => 'Renault'],
    ['sub_category_id' => 58, 'name' => 'Scania'],
    ['sub_category_id' => 58, 'name' => 'Shacman'],
    ['sub_category_id' => 58, 'name' => 'Sumitomo'],
    ['sub_category_id' => 58, 'name' => 'T-seriya'],
    ['sub_category_id' => 58, 'name' => 'Tatra'],
    ['sub_category_id' => 58, 'name' => 'Volvo'],
    ['sub_category_id' => 58, 'name' => 'Wirtgen'],
    ['sub_category_id' => 58, 'name' => 'Zil'],
    ['sub_category_id' => 58, 'name' => 'Zoomlion'],
];

$sale_type = [
    ['name' => 'Satılır'],
    ['name' => 'Kirayə verilir'],
];
$apartmentType = [
    ['sub_category_id' => 60, 'name' => 'Yeni tikili'],
    ['sub_category_id' => 60, 'name' => 'Köhnə tikili'],
];
$villa_property_type = [
    ['sub_category_id' => 61, 'name' => 'Bağ evi'],
    ['sub_category_id' => 61, 'name' => 'Həyət evi'],
    ['sub_category_id' => 61, 'name' => 'Villa'],
];
$objects_and_offices = [
    ['sub_category_id' => 65, 'name' => 'Ofis'],
    ['sub_category_id' => 65, 'name' => 'Obyekt'],
    ['sub_category_id' => 65, 'name' => 'Mağaza'],
];


//saat ve zinet esiyslari bashla











